<div class="row">
    <div class="col-md-2">{thumbnail}</div>
    <div class="col-md-10">
        <h4>{item-heading}</h4>
        <div class="row">
            <div class="col-md-2">{field-label}:</div>
            <div class="col-md-10">{field-value}:</div>
        </div>
        <div class="row">
            <div class="col-md-2">{field-label}:</div>
            <div class="col-md-10">{field-value}:</div>
        </div>
        <div class="row">
            <div class="col-md-2">{field-label}:</div>
            <div class="col-md-10">{field-value}:</div>
        </div>
    </div>
</div>
