<?php if (null !== $this->esperson()->getDisplayName()): ?>
    <?php $this->headTitle($this->esperson()->getDisplayName()); ?>
    <?php if (null !== $this->esperson()->getLifetime()): ?>
        <h1 class="title"><?= $this->esperson()->getDisplayName(); ?> <?= $this->esperson()->getLifetime(); ?></h1>
    <?php else: ?>
        <h1 class="title"><?= $this->esperson()->getDisplayName(); ?></h1>
    <?php endif; ?>
<?php endif; ?>

