<ul class="metadata">
    <?= $this->context($this)->renderInContext(
        'knowledgecard/common/metadata/list.phtml', ['list' => $this->esperson()->getMetadata()->getList('job', 'birth', 'death', 'nationality')]
    )
    ?>

    <? if ($this->esperson()->hasAbstract()): ?>
        <? $abstractInfo = $this->esperson()->getAbstractInfo(); ?>

        <li class="entry section-start">
            <span class="entry-label"><?= $abstractInfo['label']; ?></span>
            <span class="entry-value"><?= $abstractInfo['text']; ?></span>
            <? if ($abstractInfo['truncated']): ?>
                <span class="ellipsis"></span>
                <?= $this->esperson()->getDetailPageLink('<a class="ref external more" data-lightbox-ignore href="%s">%s</a>', 'card.knowledge.common.more') ?>
            <? endif; ?>
        </li>
    <? endif; ?>

    <? if ($this->essubjectcollection()->hasSubjectsInCollection()): ?>
        <li class="entry section-start">
            <span class="entry-label"><?= $this->esperson()->getRelatedSubjectsLabel(); ?></span>
            <span class="entry-value"><?= $this->essubjectcollection()->getSubjectCollectionLinkList('<a class="ref nowrap" href="%s">%s</a>'); ?></span>
        </li>
    <? endif; ?>
</ul>