<?php
/** @var \Laminas\Form\Element $field */
$readonly = isset($readonly) && $readonly;
$noSelectedOptionLabel = $noSelectedOptionLabel ?? '-';
?>
<div class="form-group">
    <label class="col-sm-3 control-label">
        <?php if ($field->getLabel() !== null): ?>
            <?= $this->transEsc($field->getLabel()) ?>
        <?php endif; ?>
    </label>
    <div class="col-sm-9">
        <?php switch($field->getAttribute('type')):
           case 'text': case 'tel': case 'email':?>
            <input class="form-control"
                   type="<?= $this->escapeHtmlAttr($field->getAttribute('type')) ?>"
                   name="<?= $this->escapeHtmlAttr($field->getAttribute('name')) ?>"
                   value="<?= $this->escapeHtmlAttr($field->getValue()) ?>"
                <?= $readonly ? ' readonly' : '' ?>>
            <?php break; ?>
        <?php case 'textarea': ?>
            <textarea class="form-control" name="<?= $this->escapeHtmlAttr($field->getAttribute('name')) ?>"><?= $this->escapeHtml($field->getValue()) ?></textarea>
            <?php break; ?>
        <?php case 'select': ?>
            <select class="form-control" name="<?= $this->escapeHtmlAttr($field->getAttribute('name')) ?>">
                <?php $fieldValue = $field->getValue(); ?>
                <?php if (empty($fieldValue)): ?>
                    <option value="">
                        <?= $this->transEsc($noSelectedOptionLabel) ?>
                    </option>
                <?php endif; ?>
                <?php foreach ($field->getOptions()['value_options'] as $key => $value): ?>
                    <option value="<?=$this->escapeHtmlAttr($key)?>" <?= $key === $fieldValue ? ' selected' : '' ?>>
                        <?=$this->transEsc($value)?>
                    </option>
                <?php endforeach; ?>
            </select>
            <?php break; ?>
        <?php case 'radio': ?>
            <?php $idCount = 0 ?>
            <?php $fieldValue = $field->getValue(); ?>
            <?php if (empty($fieldValue)): ?>
                <?php $fieldValue = reset($field->getOptions()['value_options']) ?>
            <?php endif; ?>
            <?php foreach ($field->getOptions()['value_options'] as $key => $value): ?>
                <input type="<?= $this->escapeHtmlAttr($field->getAttribute('type')) ?>"
                       name="<?= $this->escapeHtmlAttr($field->getAttribute('name')) ?>"
                       value="<?= $this->escapeHtmlAttr($value) ?>"
                       id="feedbackform-radio-<?= $field->getName() . '-' . $idCount ?>"
                       <?= $value === $fieldValue ? ' checked' : ''?>>
                <label class="label-radio" for="feedbackform-radio-<?= $field->getName() . '-' . $idCount++ ?>">
                    <?= $this->transEsc($key) ?>
                </label><br>
            <?php endforeach; ?>
            <?php break; ?>
        <?php endswitch; ?>
        <div class="help-block with-errors">
            <?php foreach($field->getMessages() as $message): ?>
                <?= $this->transEsc($message) ?><br>
            <?php endforeach; ?>
        </div>
    </div>
</div>