<li><a class="help-link" data-lightbox href="<?=$this->url('help-home')?>?topic=search"><?= $this->transEsc('Search Tips') ?></a></li>
<li><a href="<?= $this->url('help-page', ['topic' => 'about_swissbib']); ?>"><?= $this->transEsc('menu.service.information') ?></a></li>
<li><a title="<?= $this->transEsc('menu.feedback') ?>" href="" id="feedback"><?= $this->transEsc('menu.feedback') ?></a></li>
<li><a title="<?= $this->transEsc('swissbib Blog') ?>" href="https://swissbib.blogspot.ch" id="swissbib blog" target="_blank"><?= $this->transEsc('Blog') ?></a></li>