<div class="home-content-box">
    <h2 class="lead">swisscovery - nuovo portale di ricerca</h2>
    <p>
        Dal 7 dicembre 2020 jusbib verrà sostituito dal catalogo <a href="https://www.swisscovery.org/" target="_blank">swisscovery</a> della nuova rete di biblioteche svizzere SLSP (Swiss Library Service Platform). swisscovery rende visibili in un’unica interfaccia di scoperta le collezioni scientifiche di più di 475 istituzioni.</p>
    <p>Maggiori informazioni sono disponibili sui siti Web di <a href="https://slsp.ch/it"  target="_blank">SLSP</a> e dell’<a href="http://lawlibraries.ch"  target="_blank">ABGS</a>.</p>
</div>
