<?php $name = $this->esorganisation()->getDisplayName() ?>
<?php $link = $this->url('page-detail-organisation', ['id' => $this->esorganisation()->getDriver()->getUniqueID()]) ?>

<div class="row result-item">
    <div class="item-thumbnail hidden-xs col-sm-2 no-gutter hidden-print">
        <a href="<?= $link ?>" class="img-responsive">
            <?= $this->render('thumbnail.phtml') ?>
        </a>
    </div>
    <div class="col-sm-10">
        <div class="item-info">
            <div class="row">
                <div class="col-md-12">
                    <a href="<?= $link ?>" alt="<?= $name ?>"><?= $name ?></a>
                </div>
            </div>
        </div>
    </div>
</div>