<?php // @var $m  Swissbib\RecordDriver\SolrMarc ?>
<?php $record = $this->record($item); ?>
<div class="row result-item">
    <div class="item-thumbnail hidden-xs col-sm-2 no-gutter hidden-print">
        <?= $this->render('/detailpage/medias/item/thumbnail.phtml') ?>
    </div>
    <div class="col-sm-10">
        <div class="item-info">
            <div class="row">
                <div class="col-md-12">
                    <h4>
                        <a href="<?=$this->recordLink()->getUrl($item)?>" class="title singleLinkForBulk" title="<?= $this->escapeHtml($item->getShortTitle()) ?>">
                            <?= $this->escapeHtml($item->getShortTitle()) ?>
                        </a>
                    </h4>
                </div>
            </div>
            <div class="row">
                <div class="col-md-2 hidden-xs"><?= $this->transEsc('page.detail.media.item.author')
                    ?>:</div>
                <div class="col-md-10"><?= $this->escapeHtml($record->getResponsible($item->getTitleStatement(true), $item)) ?></div>
            </div>
            <?php if ($item->getHumanReadablePublicationDates()): ?>
            <div class="row">
                <div class="col-md-2 hidden-xs"><?= $this->transEsc('Year') ?>:</div>
                <div class="col-md-10"><?= $this->escapeHtml($item->getHumanReadablePublicationDates()[0]) ?></div>
            </div>
            <?php endif; ?>
            <?php if (!empty($record->getFormatList())): ?>
            <div class="row">
                <div class="col-md-2 hidden-xs"><?= $this->transEsc('Format') ?>:</div>
                <div class="col-md-10"><?= $record->getFormatList() ?></div>
            </div>
            <?php endif; ?>
        </div>
    </div>
</div>
