<? // @var $m  Swissbib\RecordDriver\SolrMarc ?>
<div class="row">
    <div class="col-md-2">
        <?= $this->render('/detailpage/medias/item/thumbnail.phtml') ?>
    </div>
    <div class="col-md-10">
        <h4><?= $item->getTitle() ?></h4>
        <div class="row">
            <div class="col-md-2">{field-label}:</div>
            <div class="col-md-10">{field-value}:</div>
        </div>
        <div class="row">
            <div class="col-md-2">{field-label}:</div>
            <div class="col-md-10">{field-value}:</div>
        </div>
        <div class="row">
            <div class="col-md-2">{field-label}:</div>
            <div class="col-md-10">{field-value}:</div>
        </div>
    </div>
</div>
