<div class="home-content-box">
    <h2 class="lead">Dataset</h2>
    <p>
        Currently the following data is available here:
        <br><br>
        IDSBB: data until 30.8.2020
        <br>
        IDSLU: data until 30.8.2020
        <br>
        IDSSG: data until 27.8.2020
        <br>
        NEBIS: data until 28.8.2020
        <br>
        RERO: data until 27.8.2020
        <br>
        SBT: data until 10.12.2019
    </p>
    <br>
    <p>
        The deduplication configuration has been adapted for a last internal test phase before GoLive.
    </p>
</div>
