<div class="home-content-box">
  <h2 class="lead">Recherche dans le catalogue, basée sur les informations de Wikipedia au sujet des personnes</h2>
  <p>Vous êtes vous déjà rendu dans une bibliothèque, à la recherche d'un livre publié récemment et écrit par un prix Nobel de littérature ? Ou par un conseiller fédéral ? Ou par une personne née ou morte dans votre commune de domicile ? Comment en obtenir la liste ?</p>
  <a href="https://swissbib.blogspot.com/2020/07/auf-wikipediawikidata-basierende-suchen.html" target="_blank" class="btn btn-link">Plus d'informations</a>
</div>