<div class="home-content-box">
    <h2 class="lead">Was ist neu in swissbib?</h2>
    <p>Wir haben in diesem Jahr eine Menge neuer Funktionen eingeführt, die wir Ihnen in einem Überblick auf unserem Blog vorstellen möchten.</p>
    <a href="<?= $this->redirectProtocolWrapper()->getWrappedURL('http://swissbib.blogspot.ch/2017/12/was-ist-neu-in-swissbib.html') ?>" target="_blank" class="btn btn-link">Mehr Informationen</a>
</div>