<div class="home-content-box">
    <h2 class="lead">Personen- und Themeninformationen in swissbib</h2>
    <p>Auf swissbib.ch stehen mit Knowledge Cards und Informationsseiten zu Personen und Themen sowie der erweiterten Autocomplete-Funktion drei neue Elemente zur Verfügung.</p>
    <a href="<?= $this->redirectProtocolWrapper()->getWrappedURL('https://swissbib.blogspot.com/2018/03/swissbib-mit-personen-und.html') ?>" target="_blank" class="btn btn-link">Mehr Informationen</a>
</div>