<?php // Proof of Concept: Copied from themes/sbvfrd/templates/RecordDriver/DefaultRecord/core.phtml ?>
<!--<h1>SwissCollections</h1>-->
<!-- <?php echo APPLICATION_ENV; ?>-->
<?php
/** @var SwissCollections\RecordDriver\SolrMarc $record */
$record = $this->driver;
/** @var Swissbib\View\Helper\Record $viewRecord */
$viewRecord = $this->record($record);
/**
 * @var \SwissCollections\RenderConfig\RenderGroupConfig[]
 */
$renderConfig = $record->getRenderConfig();

$id = $record->getUniqueId();
$shortTitle = $record->getShortTitle();
$titleStatement = $record->getTitleStatement(true);
$subtitle = $viewRecord->getSubtitle($titleStatement);
$responsible = $viewRecord->getResponsible($titleStatement, $record);
$publications = $record->getPublicationDetails();
$physicalDescriptions = $record->getPhysicalDescriptions(false);
$edition = $record->getEdition();
$cartMathData = $record->getCartMathData();
$formats = $viewRecord->getFormatList();
$hierarchicalLevel = $record->getHierachicalLevel();
$hostItems = $record->getHostItemEntry();
$journalTitle = $record->getContainerTitle();
$ref = $record->getContainerReference();
$highlightedFulltext = $record->getHighlightedFulltext();

$showFRBR = $this->configAccess()->Site->displayFrbr;
$groupID = $this->driver->getGroup(true);

$urls = $viewRecord->getExtendedLinkDetails();

$nl = null;
if ($searchClassId != "Summon") {
    try {
        $nl = $this->nationalLicences()->getUrl($record);
    } catch (\Exception $e) {
        //this is the case for swissbib orange and jusbib
        $nl = null;
    }
}
if ($nl) {
    $linkNL = ['url' => $nl['url'], 'desc' => "Get it Online (National Licence)"];
    array_push($urls, $linkNL);
}
$link360 = $viewRecord->getLink360();
$linkSFX = $viewRecord->getLinkSFX();

?>
<div class="" vocab="http://schema.org/" resource="#record"
     typeof="<?= $this->driver->getSchemaOrgFormats() ?> Product">

    <div style="border-top: 1px solid #bbbbbb; margin-top: 1rem; margin-bottom: 1rem;"></div>
    <?php
    if ($renderConfig) {
        /**
         * @var array $subMap
         * @var File_MARC_Data_Field $field
         * @var \SwissCollections\RenderConfig\AbstractRenderConfigEntry $renderConfig
         * @var bool $isFirst compound entry
         * @var bool $isLast compound entry
         * @var bool $firstListEntry
         * @var bool $lastListEntry
         */
        $renderer = function ($subMap, $field, $renderConfig, $isFirst, $isLast, $firstListEntry, $lastListEntry) {
            if ($renderConfig->repeated && $firstListEntry && $isFirst) {
                echo "\t\t<ul>\n";
                echo "\t\t<li>\n";
            }
            if ($renderConfig->repeated && !$firstListEntry && $isFirst) {
                echo "\t\t</li>\n";
                echo "\t\t<li>\n";
            }
            if ($renderConfig->isLineRenderMode()) {
                echo "\t\t<div class='field-value field-value-" . $renderConfig->labelKey . "'>";
            } else if ($renderConfig->isInlineRenderMode()) {
                if ($isFirst) {
                    echo "\t\t<div class='field-value field-value-compound field-value-" . $renderConfig->labelKey . "'>\n";
                } else {
                    echo ",\n";
                }
                echo "\t\t\t<span class='field-entry field-entry-" . $renderConfig->labelKey . "'>";
            }
            echo "\t\t<!-- marcInfo=" . $renderConfig . " -->";
            if ($subMap['escHtml']) {
                echo $this->escapeHtml($subMap['value']);
            } else {
                echo $subMap['value'];
            }
            if ($renderConfig->isLineRenderMode()) {
                echo "\t\t</div>\n";
            } else if ($renderConfig->isInlineRenderMode()) {
                echo "</span>";
                if ($isLast) {
                    echo "\n\t\t</div>\n";
                }
            }
            if ($renderConfig->repeated && $lastListEntry && $isLast) {
                echo "\t\t</li>\n";
                echo "\t\t</ul>\n";
            }
        };
        /**
         * @var \SwissCollections\RenderConfig\RenderGroupConfig $renderGroupConfig
         */
        foreach ($renderConfig as $renderGroupConfig) {
            if (!$record->isEmptyGroup($renderGroupConfig)) {
                $groupName = $renderGroupConfig->getName();
                $groupAnchor = str_replace(' ', '_', $groupName);
                echo "<a name='$groupAnchor'>";
                echo "<h2>" . $this->translate('page.detail.group.label.' . $groupName) . "</h2>";
                echo "</a>";
                /**
                 * @var \SwissCollections\RenderConfig\AbstractRenderConfigEntry $renderElem
                 */
                foreach ($renderGroupConfig->entries() as $renderElem) {
                    if (!$record->isEmptyField($renderElem->marcIndex, $renderElem)) {
                        echo "\n<div class='row'>\n";
                        echo "\t<div class='field-label field-label-" . $renderElem->labelKey . " col-md-3'>\n";
                        echo $this->translate('page.detail.field.label.' . $renderElem->labelKey);
                        echo "\t</div>\n";
                        echo "\t<div class='col-md-9'>\n";
                        $record->applyRenderer($renderElem->marcIndex, $renderElem, $renderer);
                        echo "\t</div>\n";
                        echo "</div>\n";
                    }
                }
                echo "<div style=\"border-top: 1px solid #bbbbbb; margin-top: 1rem; margin-bottom: 1rem;\"></div>";
            }
        }
    }
    ?>
</div>