<?php

namespace SwissCollections\templates\RecordDriver\SolrMarc;

use SwissCollections\Formatter\FieldFormatter;
use SwissCollections\Formatter\FieldFormatterData;
use SwissCollections\RecordDriver\FieldRenderContext;

class InlineFormatter extends FieldFormatter {

    public function getName(): String {
        return "inline";
    }

    /**
     * @param String $fieldName
     * @param FieldFormatterData[] $fieldDataList
     * @param FieldRenderContext $context
     */
    public function render($fieldName, $fieldDataList, $context): void {
        echo "\t\t<div class='field-value field-value-compound field-value-" . $fieldName . "'>\n";
        foreach ($fieldDataList as $index => $fd) {
            if ($index > 0) {
                echo ",\n";
            }
            echo "\t\t\t<!-- marcInfo=" . $fd->renderConfig . " -->";
            echo "\t\t\t<span class='field-entry field-entry-" . $fd->renderConfig->labelKey . "'>";
            $this->outputValue($fd);
            echo "</span>\n";
        }
        echo "\t\t</div>\n";
    }
}