<?
// Set up page title:
$this->headTitle($this->translate('pura.remoteAccessForPrivateUsers'));

// Set up breadcrumbs:
$this->layout()->breadcrumbs = '<li><a href="' . $this->url('myresearch-home') . '">' . $this->transEsc('Your Account') . '</a></li> <li class="active">' . $this->transEsc('pura.remoteAccessForPrivateUsers') . '</li>';
?>

<div class="<?= $this->layoutClass('mainbody') ?>">

    <h2><?= $this->institution["label"][$this->layout()->userLang] ?></h2>


    <h2>Before registration : </h2>
    <p>To access remotely some of the e-resources of the <?= $this->institution["label"][$this->layout()->userLang] ?>, you need to print this page and bring it to the ZB Desk, along with your ID and Library Card. You can also show this screen on your mobile phone or laptop.</p>
    


    <table>
        <tr>
            <td>Name:&nbsp;</td>
            <td><?= $this->firstname ? $this->escapeHtml($this->firstname . ' ' . $this->lastname) : ''; ?></td>
        </tr>
        <tr>
            <td>Email:&nbsp;</td>
            <td><?= $this->email ? $this->escapeHtml($this->email) : ''; ?></td>
        </tr>
        <tr>
            <td>Barcode:&nbsp;</td>
            <td><?= $this->token ? $this->escapeHtml($this->token) : ''; ?></td>
        </tr>
    </table>


    <p>&nbsp;</p>

    <p><img src="<?= $this->url('pura/barcode', ['token' => $this->token]) ?>"></p>

    <p>Hiermit beantrage ich Zugang auf die digitalen Angebote
        der Zentralbibliothek Zürich über SWITCH edu-ID.</p>

    <button class="btn btn-primary" onClick="window.print()">
        <?= $this->transEsc('Print') ?>
    </button>



    <h2>After registration : </h2>

    <p>You are registered for this service.</p>
    <p>Your account is valid until <?= $this->user->getExpirationDate()->format('j.n.Y') ?>.</p>
    <p>Access e-resourcen : </p>

    <ul>
    <?php foreach ($this->publishers as $publisher) : ?>

    <li><a href="<?= $publisher["url"] ?>"><?= $publisher["name"] ?></a></li>

    <?php endforeach; ?>
    </ul>

    <h4>Help ?</h4>
        <?= $institution['label'][$this->layout()->userLang] ?>
        <address>
            <? if (!empty($institution['address'])): ?>
                <p><?= $institution['address'] ?></p>
            <? endif; ?>
            <? if (!empty($institution['city']) && !empty($institution['zip'])): ?>
                <? $canton = !empty($institution['canton']) ? ' (' . strtoupper($institution['canton']) . ')' : ''; ?>
                <p><?= $institution['zip'] . ' ' . $institution['city'] . $canton ?></p>
            <? endif; ?>
            <? if (!empty($institution['email'])): ?>
                <p><a href="mailto:<?= $institution['email'] ?>" ><?= $this->transEsc('Email') ?></a></p>
            <? endif; ?>

            <? if (!empty($institution['website'])): ?>
                <a href="<?= $institution['website'] ?>" class="color"
                   target="_blank"><?= $this->transEsc('libraries.website') ?></a>
            <? else: ?>
                <? if (!empty($institution['url']) && is_array($institution['url'])): ?>
                    <? $url = $institution['url'][$this->layout()->userLang]; ?>
                    <a href="<?= $url ?>" class="color"
                       target="_blank"><?= $this->transEsc('Library_Information') ?></a>
                <? endif; ?>
            <? endif; ?>

        </address>
    




</div>

<div class="<?= $this->layoutClass('sidebar') ?>">
    <?= $this->context($this)->renderInContext("myresearch/menu.phtml", ['active' => 'pura']) ?>
</div>