<?= $institution['name'][$this->layout()->userLang] ?><br/>

<?php if (!empty($institution['address'])): ?>
    <?= $institution['address'] ?><br/>
<?php endif; ?>
<?php if (!empty($institution['city']) && !empty($institution['zip'])): ?>
    <?php $canton = !empty($institution['canton']) ? ' (' . strtoupper($institution['canton']) . ')' : ''; ?>
    <?= $institution['zip'] . ' ' . $institution['city'] . $canton ?><br/>
<?php endif; ?>
    <br/>
<?php if (!empty($institution['email'])): ?>
    <p><?= $this->transEsc('Email') ?>: <a href="mailto:<?= $institution['email'] ?>" ><?= $institution['email'] ?></a></p>
<?php endif; ?>

<?php if (!empty($institution['website'])): ?>
    <?= $this->transEsc('libraries.website') ?>: <a href="<?= $institution['website'] ?>" class="color"
                                                    target="_blank"><?= $institution['website'] ?></a>
<?php else: ?>
    <p><?php if (!empty($institution['url']) && is_array($institution['url'])): ?>
        <?php $url = $institution['url'][$this->layout()->userLang]; ?>
        <?= $this->transEsc('libraries.website') ?>: <a href="<?= $url ?>" class="color"
                                                        target="_blank"><?= $url ?></a></p>
    <?php endif; ?>
<?php endif; ?>
<?php if (!empty($institution['phone'])): ?>
    <p><?= $this->transEsc('Phone Number') ?>: <?= $institution['phone'] ?></p>
<?php endif; ?>