<?php

namespace SwissCollections\templates\RecordDriver\SolrMarc\FieldGroupFormatter;

use SwissCollections\Formatter\FieldGroupFormatter;
use SwissCollections\RecordDriver\FieldGroupRenderContext;
use SwissCollections\RecordDriver\FieldRenderContext;
use SwissCollections\RenderConfig\AbstractRenderConfigEntry;

class DefaultFormatter extends FieldGroupFormatter {

    public static $NAME = "default";

    public function getName(): String {
        return DefaultFormatter::$NAME;
    }

    /**
     * @param AbstractRenderConfigEntry[] $fieldDataList
     * @param FieldGroupRenderContext $context
     */
    public function render(&$fieldDataList, &$context): void {
        echo "\n<div class='row'>\n";
        echo "\t<div class='field-label field-label-" . $this->labelKeyAsCssClass($fieldDataList[0]->labelKey) . " col-md-3'>\n";
        echo $this->translateLabelKey($fieldDataList[0]->labelKey);
        echo "\t</div>\n";
        echo "\t<div class='col-md-9'>\n";
        foreach ($fieldDataList as $renderElem) {
            // sets list element tags for repeated fields (see $this->outputField() call below)
            $renderElem->setListHtml("\t\t<li class='field-values-element'>\n", "\t\t</li>\n");
            $this->outputField($renderElem,
                $context, "\t\t<ul class='field-values'>\n", "\t\t</ul>\n");
        }
        echo "\t</div>\n";
        echo "</div>\n";
    }
}