<!-- <?php

use SwissCollections\Formatter\FieldGroupFormatter\DefaultFormatter;
use SwissCollections\Formatter\FieldGroupFormatter\SucheinstiegePerson;
use SwissCollections\RecordDriver\FieldGroupRenderContext;
use SwissCollections\RecordDriver\FieldRenderContext;
use SwissCollections\RenderConfig\AbstractRenderConfigEntry;

/** @var AbstractRenderConfigEntry[] $fieldDataList */
/** @var SucheinstiegePerson $formatter */
/** @var FieldGroupRenderContext $context */
/** @var FieldRenderContext $fieldContext */
/** @var string $unknownRoleLabelKey */
/** @var string $personLabelKey */
/** @var string[] $roles */
/** @var array $personsWithRole */
?> -->
<div class='row row-sucheinstiege-person'>
    <div class='field-label field-label-<?php echo SucheinstiegePerson::$RENDER_CONFIG_PERSON_KEY; ?> col-md-3'>
        <?php echo $formatter->translateLabelKey($personLabelKey, $context); ?>
    </div>
    <div class='col-md-9'>
        <?php
        foreach ($roles as $role) {
            if ($role !== "unknown") {
                echo $this->render(
                    '/RecordDriver/SolrMarc/FieldGroupFormatter/SucheinstiegePersonRoleGroup',
                    [
                        'context' => $fieldContext,
                        'unknownRoleLabelKey' => $unknownRoleLabelKey,
                        'role' => $role,
                        'personsWithRole' => $personsWithRole,
                        'formatter' => $formatter,
                        'groupContext' => $context
                    ]
                );
            }
        }
        echo $this->render(
            '/RecordDriver/SolrMarc/FieldGroupFormatter/SucheinstiegePersonRoleGroup',
            [
                'context' => $fieldContext,
                'unknownRoleLabelKey' => $unknownRoleLabelKey,
                'role' => "unknown",
                'personsWithRole' => $personsWithRole,
                'formatter' => $formatter,
                'groupContext' => $context
            ]
        );
        ?>
    </div>
</div>
