<div class="detailpage-common">
    <a id="detailpage-common"></a>
    <div class="row">
        <div class="col-sm-12">
            <div class="row">
                <div class="col-sm-12">
                    <h2 class="subject"><?= $this->essubject()->getDisplayName() ?></h2>
                    <?= $this->render('common/metadata.phtml') ?>
                </div>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-sm-12">
            <?= $this->render('common/medias/medias.phtml') ?>
        </div>
    </div>
</div>
