<? $availableReferences = $this->driver->getSameAs(); ?>
<? if (is_array($availableReferences) && count($availableReferences) > 0): ?>
<div class="record-references hidden-xs hidden-sm">
    <h1><?= $this->translate('page.detail.subject.more') ?></h1>
    <div class="list">
        <ul id="detailpage-subject-references">
            <? foreach ($availableReferences as $link): ?>
            <?= $this->essubject()->getRecordReference('<li><a href="%s">%s</a></li>', $link, $this->references->record->references) ?>
            <? endforeach; ?>
        </ul>
    </div>
</div>
<? endif; ?>
