<? $configuredReferences = $this->references->record->references ?>
<? if ($this->essubject()->hasMatchingRecordReferences($configuredReferences)): ?>
    <div class="record-references hidden-xs hidden-sm">
        <h1 class="title"><?= $this->translate('page.detail.person.more') ?></h1>
        <div class="list">
            <ul id="detailpage-person-references">
                <? foreach ($this->essubject()->getSameAs() as $link): ?>
                    <?= $this->essubject()->getRecordReference('<li><a href="%s">%s</a></li>', $link, $configuredReferences) ?>
                <? endforeach; ?>
            </ul>
        </div>
    </div>
<? endif; ?>
