<div class="row">
    <div class="col-xs-12">
        <?= $this->render('relations/authors.phtml') ?>
    </div>
</div>
<? if (isset($this->parentMedias) && $this->parentMedias->getResultTotal() > 0): ?>
<div class="separator"></div>
<div class="row">
    <div class="col-xs-12">
        <div class="detailpage-media-list-wrapper">
            <?= $this->render('common/medias/parents.phtml') ?>
        </div>
    </div>
</div>
<? endif; ?>
<? if (isset($this->childrenMedias) && $this->childrenMedias->getResultTotal() > 0): ?>
<div class="separator"></div>
<div class="row">
    <div class="col-xs-12">
        <div class="detailpage-media-list-wrapper">
            <?= $this->render('common/medias/children.phtml') ?>
        </div>
    </div>
</div>
<? endif; ?>
