<a id="detailpage-common"></a>
<? if ($this->esperson()->hasThumbnail()): ?>
    <?= $this->render('common/with-thumbnail.phtml') ?>
<? else: ?>
    <?= $this->render('common/without-thumbnail.phtml') ?>
<? endif; ?>

<div class="row">
    <div class="col-sm-12">
        <?= $this->context($this)->renderInContext(
            '/detailpage/medias.phtml', [
                'type' => 'person',
                'headline' => 'page.detail.person.media.list.title'
            ]
        ) ?>
    </div>
</div>
