<? $this->esperson()->setPerson($this->driver) ?>
<? $this->essubjectcollection()->setCollection($this->subjects) ?>

<div class="container">
    <div class="row">
        <div class="col-sm-4 col-sm-push-8">
            <?= $this->render('navigation.phtml') ?>
        </div>
        <div class="col-sm-8 col-sm-pull-4">
            <?= $this->render('common.phtml') ?>
        </div>
    </div>
</div>

<?= $this->render('relations.phtml') ?>
