<div class="container">
    <div class="row">
        <div class="col-xs-12">
            <?= $this->render('slider.phtml') ?>
        </div>
    </div>
    <div class="row">
        <div class="col-xs-12">
            <?= $this->render('slider.phtml') ?>
        </div>
    </div>
    <div class="row">
        <div class="col-xs-12">
            <?= $this->render('slider.phtml') ?>
        </div>
    </div>
    <div class="row">
        <div class="col-xs-12">
            <?= $this->render('subjects.phtml') ?>
        </div>
    </div>
</div>
