<?php if ($this->esorganisation()->hasAbstract()): ?>
    <?php $abstractInfo = $this->esorganisation()->getAbstractInfo(false, 100, 2000); ?>
    <div class="row metadata">
        <div class="col-sm-2"><?= $abstractInfo->label ?></div>
        <div class="col-sm-10">
            <span class="abstract-text"><?= $abstractInfo->text ?></span>
            <?php if ($abstractInfo->truncated): ?>
                <?= $this->render('/organisationdetailpage/common/metadata/abstract-overflow.phtml', ['overflow' => $abstractInfo->overflow]) ?>
            <?php endif; ?>
        </div>
    </div>
<?php endif; ?>
