<?php if ($this->esorganisation()->hasAlternateName()): ?>
    <?php $alternateName = $this->esorganisation()->getAlternateNameInfo(false, 100, 200); ?>
    <div class="row metadata">
        <div class="col-sm-3"><?= $alternateName->label ?></div>
        <div class="col-sm-9">
            <span class="abstract-text"><?= $alternateName->text ?></span>
            <?php if ($alternateName->truncated): ?>
                <?= $this->render('/organisationdetailpage/common/metadata/alternatename-overflow.phtml', ['overflow' => $alternateName->overflow]) ?>
            <?php endif; ?>
        </div>
    </div>
<?php endif; ?>
