<div class="home-content-box">
    <h2 class="lead">swisscovery - neuer Sucheinstieg</h2>
    <p>
        Ab dem 7. Dezember 2020 wird jusbib durch den Katalog swisscovery des neuen Schweizer Bibliotheksverbundsystems SLSP (Swiss Library Service Platform) abgelöst. swisscovery macht die wissenschaftlichen Bestände von mehr als 475 Institutionen in einem Discovery sichtbar.</p>
       <p>Weiterführende Infos finden Sie auf den Webseiten von <a href="https://slsp.ch/de"  target="_blank">SLSP</a> und der <a href="http://lawlibraries.ch"  target="_blank">VJBS</a>.
    </p>
</div>