<?php
/** @var SwissCollections\RecordDriver\SolrMarc $record */
$record = $this->driver;
/**
 * @var \SwissCollections\RenderConfig\RenderGroupConfig[]
 */
$renderConfig = $record->getRenderConfig();
?>
    <h2><?= $this->translate('page.detail.group') ?></h2>
<?php
/**
 * @var \SwissCollections\RenderConfig\RenderGroupConfig $renderGroupConfig
 */
foreach ($renderConfig as $renderGroupConfig) {
    if (!$record->isEmptyGroup($renderGroupConfig)) {
        $groupName = $renderGroupConfig->getName();
        $groupAnchor = str_replace(' ', '_', $groupName);
        echo "<div class='anchor'>";
        echo "<a href='#$groupAnchor'>";
        echo "<div class='icon-arrow-accordion'></div>";
        echo "<span class='anchor-label'>" . $this->translate('page.detail.group.label.' . $groupName) . "</span></a>";
        echo "</div>";
    }
}
?>