<?php
/**
 * @var SwissCollections\RecordDriver\SolrMarc $record 
 */

use SwissCollections\RenderConfig\RenderConfig;

$record = $this->driver;
/**
 * @var RenderConfig $renderConfig
 */
$renderConfig = $this->renderConfig();
/**
 * @var \SwissCollections\RenderConfig\RenderGroupConfig[]
 */
$renderConfigGroups = $renderConfig->entries();
?>
    <h2><?php echo $this->translate('page.detail.group') ?></h2>
<?php
/**
 * @var \SwissCollections\RenderConfig\RenderGroupConfig $renderGroupConfig
 */
foreach ($renderConfigGroups as $renderGroupConfig) {
    if (!$renderGroupConfig->isEmpty($record, $renderConfig)) {
        $groupName = $renderGroupConfig->getName();
        $groupAnchor = str_replace(' ', '_', $groupName);
        echo "<div class='anchor'>";
        echo "<a href='#$groupAnchor'>";
        echo "<div class='icon-arrow-accordion'></div>";
        echo "<span class='anchor-label'>" . $this->translate('page.detail.group.label.' . $groupName) . "</span></a>";
        echo "</div>";
    }
}
?>