sudo: false
language: php
php:
  - 7.0
  - 7.1

env:
  - VUFIND_HOME=$PWD VUFIND_LOCAL_DIR=$PWD/local

before_script:
  - phpenv config-rm xdebug.ini
  - phpenv rehash
  - composer install
  - npm install
  - npm install -g eslint@"<3.0.0"

cache:
  directories:
    - downloads
    - $HOME/.composer/cache

script:
  - vendor/bin/phing phpunitfast phpcs-console php-cs-fixer-dryrun eslint
  - npm run test
  - npm run build