<div class="container">
    <div class="row">
        <div class="col-xs-12">
            <?= $this->render('detailpage/person/slider') ?>
        </div>
    </div>
    <div class="row">
        <div class="col-xs-12">
            <?= $this->render('detailpage/person/slider') ?>
        </div>
    </div>
    <div class="row">
        <div class="col-xs-12">
            <?= $this->render('detailpage/person/slider') ?>
        </div>
    </div>
    <div class="row">
        <div class="col-xs-12">
            <?= $this->render('detailpage/person/subjects.phtml') ?>
        </div>
    </div>
</div>
