<h2>{subjects-headline}</h2>
<p>{subjects-tag-cloud}</p>
<?
$minFontSize = 12;
$maxFontSize = 24;
$weighting = ($maxFontSize - $minFontSize) + $minFontSize;
?>
<? foreach ($subjects as $name => $val): ?>
    <?
    /** @var \ElasticSearch\VuFind\RecordDriver\ESSubject $subject */
    $subject = $val["subject"];
    $searchUrl =
        $this->url('search-results')
        . '?lookfor='
        . urlencode($subject->getName())
        . '&amp;type=Subject';
    ?>
    <a href="<?= $searchUrl ?>"
       style="font-size: <?= $val["weight"] * $weighting ?>px"><?= $name ?></a>
    <? if ($subject->hasSufficientData()): ?>
        <a href="<?= $this->url(
            'card-knowledge-subject',
            ["id" => $subject->getUniqueID()]
        ) ?>" data-lightbox>
            <span class="fa fa-info-circle fa-lg" style="display: inline;"</span>
        </a>
    <? endif; ?>
<? endforeach; ?>
