<?
    // Set default value if necessary:
    if (!isset($this->searchClassId)) {
        $this->searchClassId = 'Solr';
    }

    // Load search actions and settings (if any):
    $options = $this->searchOptions($this->searchClassId);
    $handlers = $this->searchbox()->getHandlers(
        $this->searchClassId,
        isset($this->searchIndex) ? $this->searchIndex : null
    );
    $handlerCount = count($handlers);
    $basicSearch = $this->searchbox()->combinedHandlersActive() ? 'combined-searchbox' : $options->getSearchAction();
    $searchHome = $options->getSearchHomeAction();
    $advSearch = $options->getAdvancedSearchAction();
    $lastSort = $this->searchMemory()->getLastSort($this->searchClassId);
    $lastLimit = $this->searchMemory()->getLastLimit($this->searchClassId);
    $searchtabs = $this->searchtabs($this->searchClassId, $this->lookfor, $this->searchIndex, $this->searchType);

?>
<a style="display: block" href="<?=$this->url('card-knowledge-person', ['id' => '145a6d92-7afa-3589-aba8-28e9aec9b03d']) ?>" data-lightbox>empty</a>
<a style="display: block" href="<?=$this->url('card-knowledge-person', ['id' => 'ba2caead-4d66-344e-80d5-ddc6c1b87523']) ?>" data-lightbox>Jennifer Ehle</a>
<a style="display: block" href="<?=$this->url('card-knowledge-person', ['id' => '5f679432-5f41-3bd8-a19f-8a20c4431aea']) ?>" data-lightbox>David Bamber</a>
<a style="display: block" href="<?=$this->url('card-knowledge-person', ['id' => 'd792881e-1e3e-36df-8489-a6c3ba957e24']) ?>" data-lightbox>Jane Austen</a>
<a style="display: block" href="<?=$this->url('card-knowledge-subject', ['id' => '4156468-6']) ?>" data-lightbox>Gemäldegalerie - Thema</a>
<a style="display: block" href="<?=$this->url('card-knowledge-person', ['id' => '66f120d2-5d83-31dc-92dd-3ef48bd3a7c3']) ?>" data-lightbox>Andrew Davis</a>
<a style="display: block" href="<?=$this->url('card-knowledge-person', ['id' => '85d9afdd-b7bf-34ba-a5c7-a4c1df5c0b04']) ?>" data-lightbox>Nick Dear</a>
<a style="display: block" href="<?=$this->url('card-knowledge-person', ['id' => '76100df3-36d4-301f-b0ad-15912eba659d']) ?>" data-lightbox>Diarmuid Lawrence</a>
<a style="display: block" href="<?=$this->url('card-knowledge-person', ['id' => 'aed5dd75-7b3b-369c-93bb-97a6f41d344c']) ?>" data-lightbox>Delia Fine</a>
<a style="display: block" href="<?=$this->url('card-knowledge-person', ['id' => '93a0ddb8-7b96-3b6d-8424-68f5ec63680d']) ?>" data-lightbox>Remi Adefarasin</a>
<a style="display: block" href="<?=$this->url('card-knowledge-person', ['id' => 'f2c6034e-2636-32e2-9db8-5737a263061c']) ?>" data-lightbox>Dominic Muldowney</a>
<? if ($this->searchType == 'advanced'): ?>
  <div id="searchForm">
    <div class="search-tabs-box">
    <?
        //initialize variable, otherwise we will get a notice in log
        $withTabsClass = '';
    ?>
    <? if (count($searchtabs) > 0): ?>
      <?= $this->context($this)->renderInContext('search/searchTabs', ['searchTabs' => $searchtabs]); ?>

      <? $withTabsClass = ' tabsVisible' ?>
    <? endif; ?>
      <div class="advancedSearchHeaderBox<?= $withTabsClass ?>">
        <div class="row">
          <div class="col-sm-4">
            <a class="navbar-text advancedSearchLink edit" href="<?=$this->url($advSearch)?>?edit=<?=$this->escapeHtmlAttr($this->searchId)?>"><?=$this->transEsc("Edit this Advanced Search")?></a>
          </div>
          <div class="col-sm-4">
            <a class="navbar-text advancedSearchLink new" href="<?=$this->url($advSearch)?>"><?=$this->transEsc("Start a new Advanced Search")?></a>
          </div>
          <div class="col-sm-4">
            <a class="navbar-text simpleSearchLink" href="<?=$this->url($searchHome)?>"><?=$this->transEsc("Start a new Basic Search")?></a>
          </div>
        </div>
        <!--<div class="row">
          <div class="col-sm-12">
            <p class="navbar-text"><?/*=$this->transEsc("Your search terms")*/?> : "<strong><?/*=$this->escapeHtml($this->lookfor)*/?>"</strong></p>
          </div>
        </div>-->
      </div>
    </div>
  </div>
<? else: ?>
  <form role="search" class="navbar-form navbar-left" method="get" action="<?=$this->url($basicSearch)?>" name="searchForm" id="searchForm" autocomplete="off">

    <div class="search-tabs-box">
    <? if (count($searchtabs) > 0): ?>
      <?= $this->context($this)->renderInContext('search/searchTabs', ['searchTabs' => $searchtabs]); ?>

    <? endif; ?>
    </div>
    <div class="input-group">
        <span class="searchBoxWrapper">
           <label class="sr-only" for="searchForm_lookfor"><?=$this->transEsc("Search For")?></label>
           <input class="form-control search-query<? if($this->searchbox()->autocompleteEnabled($this->searchClassId)):?> autocomplete searcher:<?=$this->escapeHtmlAttr($this->searchClassId) ?><? endif ?>" id="searchForm_lookfor" type="text" name="lookfor" value="<?=$this->escapeHtmlAttr($this->lookfor)?>"/>
        </span>
        <span class="input-group-btn">
           <span id="remove-search-text" class="fa fa-remove"></span>
           <button type="submit" class="btn btn-primary"><i class="fa fa-search"></i></button>
            <? if ($advSearch): ?>
              <a href="<?=$this->url($advSearch)?>" class="btn btn-link advancedSearchLink"><?=$this->transEsc("Advanced Search")?></a>
            <? endif; ?>
        </span>
        <? if ($handlerCount > 1): ?>
            <select class="form-control" id="searchForm_type" name="type" data-native-menu="false">
                <? foreach ($handlers as $handler): ?>
                    <option value="<?=$this->escapeHtmlAttr($handler['value'])?>"<?=$handler['selected'] ? ' selected="selected"' : ''?>><?=$handler['indent'] ? '-- ' : ''?><?=$this->transEsc($handler['label'])?></option>
                <? endforeach; ?>
            </select>
        <? elseif ($handlerCount == 1): ?>
            <input type="hidden" name="type" value="<?=$this->escapeHtmlAttr($handlers[0]['value'])?>" />
        <? endif; ?>
    </div>

    <? $shards = $options->getShards(); if ($options->showShardCheckboxes() && !empty($shards)): ?>
      <?
      $selectedShards = isset($this->selectedShards)
          ? $this->selectedShards : $options->getDefaultSelectedShards();
      ?>
      <br />
      <? foreach ($shards as $shard => $val): ?>
        <? $isSelected = empty($selectedShards) || in_array($shard, $selectedShards); ?>
          <input type="checkbox" <?=$isSelected ? 'checked="checked" ' : ''?>name="shard[]" value='<?=$this->escapeHtmlAttr($shard)?>' /> <?=$this->transEsc($shard)?>
      <? endforeach; ?>
    <? endif; ?>
    <?
      $filterDetails = $this->searchbox()->getFilterDetails(
          isset($this->filterList) && is_array($this->filterList) ? $this->filterList : array(),
          isset($this->checkboxFilters) && is_array($this->checkboxFilters) ? $this->checkboxFilters : array()
      );
    ?>
    <? if ((isset($hasDefaultsApplied) && $hasDefaultsApplied) || !empty($filterDetails)): ?>
      <? $defaultFilterState = $options->getRetainFilterSetting() ? ' checked="checked"' : ''; ?>
      <label class="checkbox">
        <input onChange="$('.applied-filter').click()" type="checkbox"<?=$defaultFilterState?> id="searchFormKeepFilters"/>
        <?=$this->transEsc("basic_search_keep_filters")?>
      </label>
      <div class="hidden">
        <? foreach ($filterDetails as $current): ?>
          <input class="applied-filter" id="<?=$this->escapeHtmlAttr($current['id'])?>" type="checkbox"<?=$defaultFilterState?> name="filter[]" value="<?=$this->escapeHtmlAttr($current['value'])?>" />
          <label for="<?=$this->escapeHtmlAttr($current['id'])?>"><?=$this->escapeHtml($current['value'])?></label>
        <? endforeach; ?>
        <? if (isset($hasDefaultsApplied) && $hasDefaultsApplied): ?>
          <!-- this is a hidden element that flags whether or not default filters have been applied;
               it is intentionally unlabeled, as users are not meant to manipulate it directly. -->
          <input class="applied-filter" id="dfApplied" type="checkbox" name="dfApplied" value="1"<?=$defaultFilterState?> />
        <? endif; ?>
      </div>
    <? endif; ?>
    <?
      /* Show hidden field for active search class when in combined handler mode. */
      if ($this->searchbox()->combinedHandlersActive()) {
        echo '<input type="hidden" name="activeSearchClassId" value="' . $this->escapeHtmlAttr($this->searchClassId) . '" />';
      }
      /* Load hidden limit preference from Session */
      if (!empty($lastLimit)) {
        echo '<input type="hidden" name="limit" value="' . $this->escapeHtmlAttr($lastLimit) . '" />';
      }
      if (!empty($lastSort)) {
        echo '<input type="hidden" name="sort" value="' . $this->escapeHtmlAttr($lastSort) . '" />';
      }
    ?>
  </form>
<? endif; ?>
