<?php if((!isset($this->layout()->showBreadcrumbs) || $this->layout()->showBreadcrumbs == true)
   && !empty($this->layout()->breadcrumbs)
   && $this->layout()->breadcrumbs !== false
 ): ?>
   <ul class="breadcrumb hidden-print">
   <?php if(is_array($this->layout()->breadcrumbs)): ?>
     <?php if(count($this->layout()->breadcrumbs) > 1): ?>
       <?=$this->render('breadcrumbs/multi.phtml', [
           'parents' => $this->layout()->breadcrumbs,
           'title' => $this->layout()->title,
           'end' => $this->layout()->breadcrumbEnd,
           'from' => $this->layout()->from
         ]) ?>
     <?php else: ?>
       <?=$this->render('breadcrumbs/default.phtml', [
           'parents' => $this->layout()->breadcrumbs,
           'title' => $this->layout()->title
         ]) ?>
     <?php endif; ?>
   <?php else: ?>
     <?=$this->layout()->breadcrumbs ?>
   <?php endif; ?>
   </ul>
 <?php endif; ?>
