<?php
///** @var \Swissbib\RecordDriver\SolrMarc		$record  */
$record = $this->driver;
/** @var \VuFind\View\Helper\Root\Record $viewRecord */
$viewRecord = $this->record($record);

// TODO reactivate when VuFind migration is finished
/*
$authors    = $record->getDeduplicatedAuthors();
$hasAuthors = !empty($authors['primary']) || !empty($authors['secondary']) || !is_null($authors['corporate']) && !empty($authors['corporate']);

if (!$hasAuthors) {
  return '';
}

*/
?>

  <? $this->headScript()->appendFile("swissbib/swissbib.ts.js"); ?>

  <h4 class="list-group-item title"><?= $this->transEsc('Author') ?></h4>
  <ul class="list-group">

    <?php if (!empty($authors['primary'])): ?>

      <li class="list-group-item">
        <? reset($authors['primary']); $authorMain = key($authors['primary']); ?>
        <a href="<? $authorMain ?><?= $viewRecord->getLink('author', $authorMain) ?>"
           title="<? $authorMain ?><?= $this->escapeHtml($authorMain) ?>"><?= $this->escapeHtml($authorMain) ?></a>
      </li>
    <?php endif; ?>

  </ul>



