<?php
///** @var \Swissbib\RecordDriver\SolrMarc		$record  */
$record = $this->driver;
/** @var \VuFind\View\Helper\Root\Record $viewRecord */
$viewRecord = $this->record($record);

$authors = $record->getDeduplicatedAuthors();
$hasAuthors = !empty($authors['primary']) || !empty($authors['secondary'])
    || null !== $authors['corporate'] && !empty($authors['corporate']);

if (!$hasAuthors) {
    return '';
}
?>
<div class="record-related-searches hidden">
    <h1 class="title"><?= $this->transEsc('Author') ?></h1>
    <ul class="list-group author list">
        <?php if (!empty($authors['primary'])): ?>

            <li class="list-group-item">
                <?php reset($authors['primary']); $authorMain = key($authors['primary']); ?>
                <a href="<?php $authorMain ?><?= $viewRecord->getLink('author', $authorMain) ?>"
                   title="<?php $authorMain ?><?= $this->escapeHtml($authorMain) ?>"><?= $this->escapeHtml($authorMain) ?></a>
            </li>
        <?php endif; ?>

        <?php if (!empty($authors['secondary'])): ?>
            <?php $tauthors = []; //de-dublication in PHP style...?>

            <?php foreach ($authors['secondary'] as $secondaryAuthor => $secondaryAuthorRoles): ?>
                <?php $tauthors[$secondaryAuthor] = $secondaryAuthor ?>
            <?php endforeach; ?>

            <?php foreach ($tauthors as $secondaryAuthor): ?>
                <li class="list-group-item">
                    <a href="<?= $viewRecord->getLink('author', $secondaryAuthor) ?>" title="<?= $this->escapeHtml($secondaryAuthor) ?>">
                        <?= $this->escapeHtml($secondaryAuthor) ?>
                    </a>
                </li>
            <?php endforeach; ?>
        <?php endif; ?>

        <?php if (null !== $authors['corporate'] && !empty($authors['corporate'])): ?>
            <?php if (!is_array($authors['corporate'])): ?>
                <?php $authors['corporate'] = [$authors['corporate']];?>
            <?php endif; ?>

            <?php foreach ($authors['corporate'] as $corporateAuthor => $corporateAuthorRoles): ?>
                <li class="list-group-item">
                    <a href="<?= $viewRecord->getLink('author', $corporateAuthor) ?>" title="<?= $this->escapeHtml($corporateAuthor) ?>">
                        <?= $this->escapeHtml($corporateAuthor) ?>
                    </a>
                </li>
            <?php endforeach; ?>
        <?php endif; ?>
    </ul>
</div>
