<?php
///** @var \Swissbib\RecordDriver\SolrMarc		$record  */
$record = $this->driver;
/** @var \VuFind\View\Helper\Root\Record $viewRecord */
$viewRecord = $this->record($record);

$authors = $record->getDeduplicatedAuthors();
$hasAuthors = !empty($authors['primary']) || !empty($authors['secondary'])
    || !is_null($authors['corporate']) && !empty($authors['corporate']);

if (!$hasAuthors) {
    return '';
}
?>
<div class="hidden">
    <h4 class="list-group-item author title"><?= $this->transEsc('Author') ?></h4>
    <ul class="list-group author"></ul>
</div>


