<? if (!is_null($this->driver->getMovement())): ?>
<h1><?= $this->translate('page.detail.authors.movements') ?></h1>
<?= $this->render(
    'carousel.phtml', [
        'id' => 'movements',
        'pagination' => ['xs' => 2, 'sm' => 2, 'md' => 4, 'lg' => 6],
        'template' => $this->ajax()->url([
            'method' => 'getSameMovementAuthors',
            'movement' => $this->escapeUrl($this->driver->getMovement()),
            'page' => '{page}',
            'size' => '{size}'
        ], '{}')
    ]
) ?>
<? endif; ?>