<? if ($this->esperson()->hasAbstract()): ?>
    <? $abstractInfo = $this->esperson()->getAbstractInfo(false, 100, 2000); ?>
    <div class="row metadata">
        <div class="col-sm-2"><?= $abstractInfo->label ?></div>
        <div class="col-sm-10">
            <span class="abstract-text"><?= $abstractInfo->text ?></span>
            <? if ($abstractInfo->truncated): ?>
                <?= $this->render('/persondetailpage/common/metadata/abstract-overflow.phtml', ['overflow' => $abstractInfo->overflow]) ?>
            <? endif; ?>
        </div>
    </div>
<? endif; ?>
