<div id="results-carousel-<?= $this->id ?>" class="carousel" data-ride="carousel">
    <div class="carousel-inner" role="listbox"></div>

    <a class="left carousel-control" href="#results-carousel-<?= $this->id ?>" role="button" data-slide="prev">
        <span class="icon-prev" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
    </a>

    <a class="right carousel-control" href="#results-carousel-<?= $this->id ?>" role="button" data-slide="next">
        <span class="icon-next" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
    </a>
</div>

<script type="text/javascript">
    window.swissbib.carousel.add("<?= $this->id ?>", "<?= $this->template ?>", <?= json_encode($this->pagination) ?>);
</script>
