<? $this->accessor = $this->accessor ?? 'medias' ?>
<? $results = $this->{$this->accessor} ?>

<? if ($results->getResultTotal() > 0): ?>

    <? if (isset($this->name)): ?>
        <a id="detailpage-medias-<?= $this->name ?>"></a>
    <? else: ?>
        <a id="detailpage-medias"></a>
    <? endif; ?>

    <? $helper = sprintf('es%s', $this->type) ?>

    <h2><?= $this->{$helper}()->resolveLabelWithDisplayName($this->headline) ?></h2>
    <h3><?= $this->{$helper}()->getResultsCountingInfoLabel($results) ?></h3>

    <?= $this->context($this)->renderInContext(
        '/detailpage/medias/results.phtml', ['accessor' => $this->accessor]
    ) ?>
    <? if ($results->getResultTotal() > 1): ?>
        <?= $this->{$helper}()->getMediaSearchLink(
            '<a class="btn btn-primary" href="%s">%s</a>',
            'common.show.results.all.long', true
        ) ?>
    <? endif; ?>
<? endif; ?>