<? $this->esperson()->setPerson($this->driver) ?>
<? $this->essubjectcollection()->setCollection($this->subjects) ?>

<div class="container"></div>
<div class="container">
    <div class="row">
        <div class="col-sm-3 col-sm-push-9">
            <?= $this->render('detailpage/person/navigation.phtml') ?>
        </div>
        <div class="col-sm-9 col-sm-pull-3">
            <?= $this->render('detailpage/person/common.phtml') ?>
        </div>
    </div>
</div>

<?= $this->render('detailpage/person/relations.phtml') ?>
