<div class="row">
  <?php $account = $this->auth()->getManager(); ?>
  <?php $user = $this->auth()->isLoggedIn(); ?>
  <?php $displayTestSystem = $this->configAccess()->Site->displayTestSystem; ?>
  <?php $displayTestSystem = !empty($displayTestSystem) && ($displayTestSystem == "true" || $displayTestSystem == "1") ? "1" : 0; ?>
  <?php if (!isset($this->layout()->renderingError)): ?>
    <div class="col-md-12">
      <div class="row">
        <div class="row">
          <div style="background-color:#C56614;padding:5px;text-align:center;border-radius:3px">
            <div style="background-color:#C56614;padding:5px;text-align:center;border-radius:3px; color:white;">
              <span><i class="fa fa-exclamation-circle"></i></span>
              <span>
              <?php if ($this->layout()->userLang == "de"): ?>
                Deutsch Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam bibendum dui ut gravida condimentum. Aenean purus felis, euismod sed convallis et, semper vestibulum lectus. Vestibulum luctus dui eget lectus dapibus euismod. Pellentesque faucibus enim sem, a feugiat neque posuere id. Etiam id lobortis dui, et condimentum orci. Ut interdum orci nec elit viverra volutpat. Pellentesque porta, quam id finibus hendrerit, sapien tortor pulvinar dolor, eu mollis ante lacus eu risus.
              <?php elseif ($this->layout()->userLang == "fr"): ?>
                français
              <?php elseif ($this->layout()->userLang == "it"): ?>
                italien
              <?php else: ?>
                english
              <?php endif; ?>
              </span>
            </div>
          </div>
        </div>
      </div>

      <div class="collapse navbar-collapse" id="header-collapse">


        <ul role="navigation" class="nav navbar-nav navbar-right">
          <?php if ($displayTestSystem): ?>
            <li class="alert alert-danger">Testsystem!!!</li>
          <?php endif; ?>

          <?php $cart = $this->cart();
          if ($cart->isActive()): ?>
            <li id="cartSummary">
              <a id="cartItems" class="modal-link" title="<?= $this->transEsc('View Book Bag') ?>"
                 href="<?= $this->url('cart-home') ?>"><i class="fa fa-suitcase"></i>
                <strong><?= count($cart->getItems()) ?></strong> <?= $this->transEsc('items') ?><?= $cart->isFull() ? ' (' . $this->transEsc('bookbag_full') . ')' : '' ?>
              </a>
            </li>
          <?php endif; ?>
            <li>
                <div class="row needs-js">
                chat loading...
                </div>
            </li>

          <?php if (is_object($account) && $account->loginEnabled()): // hide login/logout if unavailable ?>
            <li class="logoutOptions<?php if (!$account->isLoggedIn()): ?> hidden<?php endif ?>">
              <a href="<?= $this->url('myresearch-home', [], ['query' => ['redirect' => 0]]) ?>"
                 class="modal-link" title="<?= $this->transEsc("Your Account") ?>"><i
                    class="fa fa-user"></i><?= $this->transEsc("Your Account") ?>: <?= $user ? $this->escapeHtml($user->firstname . ' ' . $user->lastname) : ''; ?>
              </a>
            </li>
            <li class="logoutOptions<?php if (!$account->isLoggedIn()): ?> hidden<?php endif ?>">
              <a href="<?= $this->url('myresearch-logout') ?>" class="modal-link"
                 title="<?= $this->transEsc("Log Out") ?>"><i
                    class="fa fa-sign-out"></i><?= $this->transEsc("Log Out") ?></a>
            </li>
            <li id="loginOptions"<?php if ($account->isLoggedIn()): ?> class="hidden"<?php endif ?>>
              <?php if ($sessionInitiator = $account->getSessionInitiator($this->serverUrl($this->url('myresearch-home')))): ?>
                <a href="<?= $this->escapeHtmlAttr($sessionInitiator) ?>"><i
                      class="fa fa-sign-in"></i><?= $this->transEsc("Institutional Login") ?></a>
              <?php else: ?>
                  <?php $useModalPopupClass = $this->auth()->isAjaxLoginAllowed() ? 'class="modal-link"' : '' ?>
                <a href="<?= $this->url('myresearch-userlogin') ?>" <?= $useModalPopupClass ?>
                   title="<?= $this->transEsc("Login") ?>"><i
                      class="fa fa-sign-in"></i><?= $this->transEsc("Login") ?></a>
              <?php endif; ?>
            </li>
          <?php endif; ?>

          <?php if (isset($this->layout()->themeOptions) && count($this->layout()->themeOptions) > 1): ?>
            <li class="dropdown">
              <form method="post" name="themeForm" action="" id="themeForm">
                <input type="hidden" name="ui"/>
              </form>
              <a href="#" class="dropdown-toggle" data-toggle="dropdown"><?= $this->transEsc("Theme") ?> <b
                    class="caret"></b></a>
              <ul class="dropdown-menu">
                <?php foreach ($this->layout()->themeOptions as $current): ?>
                  <li<?= $current['selected'] ? ' class="active"' : '' ?>><a href="#"
                                                                             onClick="document.themeForm.ui.value='<?= $this->escapeHtmlAttr($current['name']) ?>';document.themeForm.submit()"><?= $this->transEsc($current['desc']) ?></a>
                  </li>
                <?php endforeach; ?>
              </ul>
            </li>
          <?php endif; ?>

          <?php if (isset($this->layout()->allLangs) && count($this->layout()->allLangs) > 1): ?>
            <li class="dropdown">
              <form method="post" name="langForm" action="" id="langForm">
                <input type="hidden" name="mylang"/>
              </form>
              <a href="#" class="dropdown-toggle" data-toggle="dropdown"><?= $this->transEsc("Language") ?> <b
                    class="caret"></b></a>
              <ul class="dropdown-menu">
                <?php foreach ($this->layout()->allLangs as $langCode => $langName): ?>
                  <li<?= $this->layout()->userLang == $langCode ? ' class="active"' : '' ?>>
                    <a href="#" onClick="document.langForm.mylang.value='<?= $langCode ?>';document.langForm.submit()">
                      <span class="visible-xs"><?= $this->displayLanguageOption($langName) ?></span>
                      <span class="hidden-xs"><?= strtoupper(trim($langCode)) ?></span>
                    </a>
                  </li>
                <?php endforeach; ?>
              </ul>
            </li>
          <?php endif; ?>
        </ul>
      </div>
    </div>
  <?php endif; ?>
  <div class="navbar-header col-sm-4 col-xs-10 col-lg-3">
    <div class="row">
      <a role="logo" class="navbar-brand" href="<?= $this->url('home') ?>">VuFind</a>
    </div>
  </div>
  <div class="col-xs-2">
    <div class="row">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#header-collapse">
        <span class="sr-only">Toggle navigation</span>
        <i class="fa fa-bars"></i>
      </button>
    </div>
  </div>
  <?php if ($this->layout()->searchbox !== false): ?>
    <section class="col-sm-8 col-xs-12 col-lg-9">
      <div class="row">
        <?= $this->layout()->searchbox ?>
      </div>
    </section>
  <?php endif; ?>
</div>


<!-- Chatfunktion zum Testen -->

<!-- Place this script as near to the end of your BODY as possible. -->
<script type="text/javascript">
    (function() {
        var x = document.createElement("script"); x.type = "text/javascript"; x.async = true;
        x.src = (document.location.protocol === "https:" ? "https://" : "http://") + "eu.libraryh3lp.com/js/libraryh3lp.js?828";
        var y = document.getElementsByTagName("script")[0]; y.parentNode.insertBefore(x, y);
    })();
</script>