<?= $this->render('/detailpage/common/metadata/list.phtml',
    ['list' => $this->esorganisation()->getMetadata()->getList('abbreviatedNameForTheCorporateBody', 'alternateNames', 'temporaryNameOfTheCorporateBody', 'temporaryNameOfTheConferenceOrEvent', 'dateOfEstablishment', 'dateOfTermination', 'dateOfConferenceOrEvent', 'location', 'country', 'legalForm', 'directorManager', 'biographicalOrHistoricalInformation', 'genre', 'notableWork', 'inception', 'dissolvedAbolishedDemolished', 'description', 'definition')]) ?>

<?= $this->render('common/metadata/abstract.phtml') ?>
