<div class="row">
  <?php $account = $this->auth()->getManager(); ?>
  <?php $user = $this->auth()->isLoggedIn(); ?>
  <?php $displayTestSystem = $this->configAccess()->Site->displayTestSystem; ?>
  <?php $displayTestSystem = !empty($displayTestSystem) && ($displayTestSystem == "true" || $displayTestSystem == "1") ? "1" : 0; ?>
  <?php if (!isset($this->layout()->renderingError)): ?>
    <div class="col-md-12">
      <?php if (isset($this->configAccess()->Survey)): ?>
        <?php
          if ($this->layout()->userLang == "en") $surveyUrl = $this->configAccess()->Survey->url_en;
          elseif ($this->layout()->userLang == "de") $surveyUrl = $this->configAccess()->Survey->url_de;
          elseif ($this->layout()->userLang == "fr") $surveyUrl = $this->configAccess()->Survey->url_fr;
          elseif ($this->layout()->userLang == "it") $surveyUrl = $this->configAccess()->Survey->url_it;
        ?>
        <?php $cookieName = $this->configAccess()->Survey->cookieName; ?>
        <?php $cookiePersistenceInDays = $this->configAccess()->Survey->cookiePersistenceInDays; ?>
        <?php if (isset($surveyUrl) && !isset($_COOKIE[$cookieName])): ?>
          <?php $expires = date("D, d M Y H:i:s", strtotime("+" . $cookiePersistenceInDays . "days")); ?>
          <div class="row">
            <div style="background-color:#fdeb18;padding:5px;text-align:center;border-radius:3px">
              <a style="color:green;" href="<?=$surveyUrl?>" target="_blank" onclick="document.cookie='<?=$cookieName?>=clicked; expires=<?=$expires?>; path=/'">
                <?= $this->transEsc("survey.notification") ?>
              </a>
            </div>
          </div>
        <?php endif; ?>
      <?php endif; ?>
        <div class="row">
            <div class="row" style="border-top-width: 10px;border-top-style: solid;color: #50BF9E;">
                <div style="background-color:#127D60;padding:5px;text-align:center;border-radius:3px">
                    <div style="background-color:#127D60;padding:5px;text-align:center;border-radius:3px;color:white">
                        <span><i class="fa fa-exclamation-circle"></i></span>
                        <span>
                            <?php if ($this->layout()->userLang == "de"): ?>
                                Einstellung von swissbib: Die Daten auf swissbib sind seit dem 7. Dezember 2020 nur noch teilweise aktualisiert. <br/> swissbib steht noch bis zum 31. März 2021 zur Verfügung, weitere <a href="https://swissbib.blogspot.com/2020/11/zur-einstellung-der-swissbib.html" style="text-decoration: underline">Informationen im Blog</a>.
                            <?php elseif ($this->layout()->userLang == "fr"): ?>
                                Fin d'activité de swissbib : Depuis le 7 décembre 2020, les données dans swissbib ne sont plus que partiellement actualisées. <br/> swissbib reste à disposition jusqu'au 31 mars 2021. <a href="https://swissbib.blogspot.com/2020/11/zur-einstellung-der-swissbib.html" style="text-decoration: underline">Plus d'informations sur notre blog</a>.
                            <?php elseif ($this->layout()->userLang == "it"): ?>
                                Switch-off of swissbib: As of December 7th 2020 data on swissbib will only be updated partially. swissbib will remain online until March 31st 2021, further <a href="https://swissbib.blogspot.com/2020/11/zur-einstellung-der-swissbib.html" style="text-decoration: underline">information in the blog</a>.
                            <?php else: ?>
                                Switch-off of swissbib: As of December 7th 2020 data on swissbib will only be updated partially. <br/> swissbib will remain online until March 31st 2021, further <a href="https://swissbib.blogspot.com/2020/11/zur-einstellung-der-swissbib.html" style="text-decoration: underline">information in the blog</a>.
                            <?php endif; ?>
                        </span>
                    </div>
                </div>
            </div>
        </div>
      <div class="collapse navbar-collapse" id="header-collapse">


        <ul role="navigation" class="nav navbar-nav navbar-right">
          <?php if ($displayTestSystem): ?>
            <li class="alert alert-danger">Testsystem!!!</li>
          <?php endif; ?>

          <?php $cart = $this->cart();
          if ($cart->isActive()): ?>
            <li id="cartSummary">
              <a id="cartItems" class="modal-link" title="<?= $this->transEsc('View Book Bag') ?>"
                 href="<?= $this->url('cart-home') ?>"><i class="fa fa-suitcase"></i>
                <strong><?= count($cart->getItems()) ?></strong> <?= $this->transEsc('items') ?><?= $cart->isFull() ? ' (' . $this->transEsc('bookbag_full') . ')' : '' ?>
              </a>
            </li>
          <?php endif; ?>
          <?php if (is_object($account) && $account->loginEnabled()): // hide login/logout if unavailable ?>
            <li class="logoutOptions<?php if (!$account->isLoggedIn()): ?> hidden<?php endif ?>">
              <a href="<?= $this->url('myresearch-home', [], ['query' => ['redirect' => 0]]) ?>"
                 class="modal-link" title="<?= $this->transEsc("Your Account") ?>"><i
                    class="fa fa-user"></i><?= $this->transEsc("Your Account") ?>: <?= $user ? $this->escapeHtml($user->firstname . ' ' . $user->lastname) : ''; ?>
              </a>
            </li>
            <li class="logoutOptions<?php if (!$account->isLoggedIn()): ?> hidden<?php endif ?>">
              <a href="<?= $this->url('myresearch-logout') ?>" class="modal-link"
                 title="<?= $this->transEsc("Log Out") ?>"><i
                    class="fa fa-sign-out"></i><?= $this->transEsc("Log Out") ?></a>
            </li>
            <li id="loginOptions"<?php if ($account->isLoggedIn()): ?> class="hidden"<?php endif ?>>
              <?php if ($sessionInitiator = $account->getSessionInitiator($this->serverUrl($this->url('myresearch-home')))): ?>
                <a href="<?= $this->escapeHtmlAttr($sessionInitiator) ?>"><i
                      class="fa fa-sign-in"></i><?= $this->transEsc("Login") ?></a>
              <?php else: ?>
                  <?php $useModalPopupClass = $this->auth()->isAjaxLoginAllowed() ? 'class="modal-link"' : '' ?>
                <a href="<?= $this->url('myresearch-userlogin') ?>" <?= $useModalPopupClass ?>
                   title="<?= $this->transEsc("Login") ?>"><i
                      class="fa fa-sign-in"></i><?= $this->transEsc("Login") ?></a>
              <?php endif; ?>
            </li>
          <?php endif; ?>

          <?php if (isset($this->layout()->themeOptions) && count($this->layout()->themeOptions) > 1): ?>
            <li class="dropdown">
              <form method="post" name="themeForm" action="" id="themeForm">
                <input type="hidden" name="ui"/>
              </form>
              <a href="#" class="dropdown-toggle" data-toggle="dropdown"><?= $this->transEsc("Theme") ?> <b
                    class="caret"></b></a>
              <ul class="dropdown-menu">
                <?php foreach ($this->layout()->themeOptions as $current): ?>
                  <li<?= $current['selected'] ? ' class="active"' : '' ?>><a href="#"
                                                                             onClick="document.themeForm.ui.value='<?= $this->escapeHtmlAttr($current['name']) ?>';document.themeForm.submit()"><?= $this->transEsc($current['desc']) ?></a>
                  </li>
                <?php endforeach; ?>
              </ul>
            </li>
          <?php endif; ?>

          <?php if (isset($this->layout()->allLangs) && count($this->layout()->allLangs) > 1): ?>
            <li class="dropdown">
              <form method="post" name="langForm" action="" id="langForm">
                <input type="hidden" name="mylang"/>
              </form>
              <a href="#" class="dropdown-toggle" data-toggle="dropdown"><?= $this->transEsc("Language") ?> <b
                    class="caret"></b></a>
              <ul class="dropdown-menu">
                <?php foreach ($this->layout()->allLangs as $langCode => $langName): ?>
                  <li<?= $this->layout()->userLang == $langCode ? ' class="active"' : '' ?>>
                    <a href="#" onClick="document.langForm.mylang.value='<?= $langCode ?>';document.langForm.submit()">
                      <span class="visible-xs"><?= $this->displayLanguageOption($langName) ?></span>
                      <span class="hidden-xs"><?= strtoupper(trim($langCode)) ?></span>
                    </a>
                  </li>
                <?php endforeach; ?>
              </ul>
            </li>
          <?php endif; ?>
        </ul>
      </div>
    </div>
  <?php endif; ?>
  <div class="navbar-header col-sm-4 col-xs-10 col-lg-3">
    <div class="row">
      <a role="logo" class="navbar-brand" href="<?= $this->url('home') ?>">VuFind</a>
    </div>
  </div>
  <div class="col-xs-2">
    <div class="row">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#header-collapse">
        <span class="sr-only">Toggle navigation</span>
        <i class="fa fa-bars"></i>
      </button>
    </div>
  </div>
  <?php if ($this->layout()->searchbox !== false): ?>
    <section class="col-sm-8 col-xs-12 col-lg-9">
      <div class="row">
        <?= $this->layout()->searchbox ?>
      </div>
    </section>
  <?php endif; ?>
</div>
