<div class="common">
    <? if ($this->esperson()->hasThumbnail()): ?>
    <img class="avatar" src="<?= $this->esperson()->getThumbnailPath(); ?>" />
    <? endif; ?>

    <? # render details about the author ?>
    <? $metadataList = $this->esperson()->getMetadataList('job', 'birth', 'death', 'nationality'); ?>
    <? if (count($metadataList) > 0): ?>
        <ul class="metadata">
            <? foreach ($metadataList as $entry): ?>
                <li class="entry <?= $entry['cssClass']; ?>">
                    <span class="entry-label"><?= $entry['label']; ?></span>
                    <span class="entry-value"><?= $entry['value']; ?></span>
                </li>
            <? endforeach; ?>

            <? if ($this->esperson()->hasAbstract()): ?>
                <? $abstractInfo = $this->esperson()->getAbstractInfo(); ?>

                <li class="entry section-start">
                    <span class="entry-label"><?= $abstractInfo['label']; ?></span>
                    <span class="entry-value"><?= $abstractInfo['text']; ?></span>
                    <? if ($abstractInfo['truncated']): ?>
                        <span class="ellipsis"></span>
                        <?= $this->esperson()->getDetailPageLink('<a class="ref external more" data-lightbox-ignore href="%s">%s</a>', 'card.knowledge.common.more') ?>
                    <? endif; ?>
                </li>
            <? endif; ?>

            <? if ($this->essubject()->hasSubjectsInCollection()): ?>
                <li class="entry section-start">
                    <span class="entry-label"><?= $this->esperson()->getRelatedSubjectsLabel(); ?></span>
                    <span class="entry-value"><?= $this->essubject()->getSubjectCollectionLinkList('<a href="%s">%s</a>'); ?></span>
                </li>
            <? endif; ?>
        </ul>
    <? endif; ?>
</div>