<?php
/**
 * SwissCollections: Date.phtml
 *
 * PHP version 7
 *
 * Copyright (C) project swissbib, University Library Basel, Switzerland
 * http://www.swisscollections.org  / http://www.swisscollections.ch / http://www.ub.unibas.ch
 *
 * Date: 1/12/20
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License version 2,
 * as published by the Free Software Foundation.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301  USA
 *
 * @category SwissCollections_VuFind
 * @package  SwissCollections\templates\RecordDriver\SolrMarc\SubfieldFormatter
 * @author   Lionel Walter <lionel.walter@unibas.ch>
 * @license  http://opensource.org/licenses/gpl-2.0.php GNU General Public License
 * @link     http://www.swisscollections.org Project Wiki
 */

namespace SwissCollections\templates\RecordDriver\SolrMarc\SubfieldFormatter;

use SwissCollections\Formatter\FieldFormatter;
use SwissCollections\Formatter\FieldFormatterData;
use SwissCollections\Formatter\SubfieldFormatter;
use SwissCollections\RecordDriver\FieldRenderContext;

/**
 * Formats Dates (a little bit).
 *
 * @category SwissCollections_VuFind
 * @package  SwissCollections\templates\RecordDriver\SolrMarc\SubfieldFormatter
 * @author   Lionel Walter <lionel.walter@unibas.ch>
 * @license  http://opensource.org/licenses/gpl-2.0.php GNU General Public License
 * @link     https://vufind.org/wiki/development Wiki
 */
class Date extends SubfieldFormatter
{
    /**
     * Get the formatter's name.
     *
     * @return string
     */
    public function getName(): string
    {
        return "date";
    }

    /**
     * Render a subfield value to html.
     *
     * @param string             $fieldName the field's name
     * @param FieldFormatterData $data      the subfield's value
     * @param FieldRenderContext $context   the render context
     *
     * @return void
     */
    public function render($fieldName, $data, $context): void
    {
        echo "<span class='subfield-formatter-" . $this->getName() . "'>";
        $text = $data->subfieldRenderData->value;
        $text = trim($text);

        // reformat "XXX-" to "XXX - …"
        if (str_ends_with($text, "-")) {
            $text = trim(substr($text, 0, strlen($text) - 1)) . " - …";
        }
        if ($data->subfieldRenderData->escHtml) {
            echo $this->phpRenderer->escapeHtml($text);
        } else {
            echo $text;
        }
        echo "</span>";
    }
}