<!-- <?php

use SwissCollections\Formatter\FieldFormatterData;
use SwissCollections\Formatter\SubfieldFormatter\Simple;
use SwissCollections\RecordDriver\FieldRenderContext;
use SwissCollections\RenderConfig\FormatterConfig;

/** @var FieldFormatterData $fieldData */
/** @var string $fieldName */
/** @var Simple $formatter */
/** @var FieldRenderContext $context */
/** @var FormatterConfig $formatterConfig */
?> -->
<?php $shortClassName = (new \ReflectionClass($formatter))->getShortName(); ?>
<<?php echo $formatter->getTag() ?> class='subfield-formatter-<?php echo $shortClassName; ?>'>
<?php
$text = $fieldData->subfieldRenderData->value;
if ($fieldData->subfieldRenderData->escHtml) {
    $text = $formatter->getHtml($text, $formatterConfig, $context);
}
echo $text;
?>
</<?php echo $formatter->getTag(); ?>>