<?php

namespace SwissCollections\templates\RecordDriver\SolrMarc\SubfieldFormatter;

use SwissCollections\Formatter\FieldFormatter;
use SwissCollections\Formatter\FieldFormatterData;
use SwissCollections\Formatter\SubfieldFormatter;
use SwissCollections\RecordDriver\FieldRenderContext;

class Simple extends SubfieldFormatter {

    public function getName(): String {
        return "simple";
    }

    /**
     * @param String $fieldName
     * @param FieldFormatterData $data
     * @param FieldRenderContext $context
     */
    public function render($fieldName, $data, $context): void {
        echo "<span class='subfield-formatter-" . $this->getName() . "'>";
        if ($data->subfieldRenderData->escHtml) {
            echo $this->phpRenderer->escapeHtml($data->subfieldRenderData->value);
        } else {
            echo $data->subfieldRenderData->value;
        }
        echo "</span>";
    }
}