<? # TODO loop over metadata list of person ?>

<?= $this->render('detailpage/common/metadata/list.phtml',
    ['list' => $this->esperson()->getMetadata()->getList('job', 'birth', 'death', 'nationality')]) ?>

<?= $this->render('detailpage/person/common/metadata/abstract.phtml') ?>

<div class="row">
    <div class="col-sm-3">{field-label}:</div>
    <div class="col-sm-9">{field-value}</div>
</div>
<div class="row">
    <div class="col-sm-3">{field-label}:</div>
    <div class="col-sm-9">{field-value}</div>
</div>
<div class="row">
    <div class="col-sm-3">{field-label}:</div>
    <div class="col-sm-9">{field-value}</div>
</div>
