<? # TODO loop over metadata list of person ?>
<div class="row">
    <div class="col-sm-3">{field-label}:</div>
    <div class="col-sm-9">{field-value}</div>
</div>
<div class="row">
    <div class="col-sm-3">{field-label}:</div>
    <div class="col-sm-9">{field-value}</div>
</div>
<div class="row">
    <div class="col-sm-3">{field-label}:</div>
    <div class="col-sm-9">{field-value}</div>
</div>
