<?php
/** @var Array[] $holdings */
/** @var String $record */
/** @var String $recordTitle */
/** @var String $institution */
$idTable = 'holdings-holding-' . $record . '-' . $institution;
$flippedContent = '';

$headers = [
  'actions' => '&nbsp;',
  'availability' => $this->transEsc('Availability'),
  'location' => $this->transEsc('Location'),
  'callnr' => $this->transEsc('Call Number'),
  'description' => $this->transEsc('Description')
];

?>
<table class="table table-striped holdings-holding holdingTable hidden-xs hidden-sm" id="<?= $this->escapeHtml($idTable) ?>">
    <thead>
    <tr>
        <th class="actions">&nbsp;</th>
        <th class="availability"><?= $this->transEsc('Availability') ?></th>
        <th class="location"><?= $this->transEsc('Location') ?></th>
        <th class="callnr"><?= $this->transEsc('Call Number') ?></th>
        <th class="description"><?= $this->transEsc('Description') ?></th>
    </tr>
    </thead>
    <tbody>
    <?php
    $index = 0;
    if (!empty($holdings)) {
        foreach ($holdings as $holding) {
            echo $this->render(
                'Holdings/holding-holding.phtml',
                [
                    'holding' => $holding,
                    'record' => $record,
                    'recordTitle' => $recordTitle
                ]
            );
            $flippedContent .= $this->render(
                'Holdings/holding-holding-flipped.phtml',
                [
                    'holding' => $holding,
                    'record' => $record,
                    'recordTitle' => $recordTitle,
                    'headers' => $headers,
                    'even' => (0 === $index++ % 2)
                ]
            );
        }
    }
    if (!empty($items)) {
        foreach ($items as $item) {
            echo $this->render(
                'Holdings/holding-item.phtml',
                [
                    'item' => $item,
                    'driver' => $driver,
                    'record' => $record,
                    'recordTitle' => $recordTitle,
                    'institution' => $institution
                ]
            );

            $flippedContent .= $this->render(
                'Holdings/holding-item-flipped.phtml',
                [
                    'item' => $item,
                    'driver' => $driver,
                    'record' => $record,
                    'recordTitle' => $recordTitle,
                    'institution' => $institution,
                    'headers' => $headers,
                    'even' => (0 === $index++ % 2)
                ]
            );
        }
    }
    ?>
    </tbody>
</table>
<?= $flippedContent; ?>