<?php
/** @var String $listClass */
/** @var String $networkAndInstitutionCode */
/** @var Array[] $actions */
if (count($actions) > 0):
?>
<ul class="holdingActions <?=$listClass?>">

   <?php foreach($actions as $key => $action): ?>

		<li class="<?=$action['class']?>">
			<a href="<?=$action['href']?>" <?php if(isset($action['target'])): ?>target="<?=$action['target']?>"<?php endif; ?> title="<?=$this->escapeHtml($action['label'])?>"
				<?php if($action['class'] === 'sign_in'): ?> data-lightbox-ignore onclick="window.sessionStorage.setItem('expandlib', '<?= $networkAndInstitutionCode ?>')" <?php else: ?> onclick="swissbib.trackLink('<?= $this->escapeHtml($action['href']) ?>')" <?php endif; ?>>
				<span><?=$this->escapeHtml($action['label'])?></span>
			</a>
		</li>

   <?php endforeach; ?>
</ul>
<?php endif; ?>