<?php
/** @var Array $item */
/** @var String $record */
/** @var String $recordTitle */
/** @var Array $headers */
/** @var Boolean $even */
/** @var Boolean $showInAllViewPorts */
$mapLink = '';
$showInAllViewPorts = isset($showInAllViewPorts) && $showInAllViewPorts;

// Description (last column)
$description = !empty($item['description']) ? $item['description'] . '. ' : '';
if (!empty($item['public_note'])) {
  $description .= $item['public_note'] . '. ';
}
if (!empty($item['opac_note'])) {
  $description .= $item['opac_note'];
}

if (isset($item['locationMap']) && $item['locationMap']) {
  $mapLink = '<a href="' . $item['locationMap'] . '" title="' . $this->transEsc('Show_Location_Map') . '" class="holdingMapLink">' . '<i class="fa fa-map-marker"></i></a>';
}

if (!isset($institution)) $institution = '';

?>
<table class="table table-flipped holdings-holding holdingTable <?= ($showInAllViewPorts ? '' : 'hidden-md hidden-lg ') . 'table-' . ($even ? 'even' : 'odd') ?>">
<tbody>
<?php
$holdingActionsContent = $this->holdingActions($item, 'holdingActionsItem', $record);
if (preg_match('/[\s\S]*<ul[\s\S]*<\/ul>[\s\S]*/', $holdingActionsContent)): ?>
  <tr>
    <th><?= $headers['action'] ?? '' ?></th>
    <td>
    <?php if ($institution == 'NATIONALLICENCE'): ?>
      <?php $nlUrl = $this->nationalLicences()->getUrl($driver)['url']; ?>
      <a href="<?= $this->escapeHtml($nlUrl) ?>" target="_blank" title="<?=$this->transEsc('Library_Information')?>" onclick="swissbib.trackLink('<?=$this->escapeHtml($nlUrl)?>')">Get it Online</a>
    <?php else: ?>
      <?= $holdingActionsContent ?>
    <?php endif; ?>
    </td>
  </tr>
<?php endif; ?>
<tr>
  <th><?= $headers['availability'] ?></th>
  <td><?= $this->availabilityInfo($item['availability'], $institution) ?>
    <?php if (($item['network'] === 'IDSBB') && (isset($item['holding_status']) | isset($item['process_status'])) && (($item['holding_status'] === '55') | ($item['process_status'] === 'ES'))): ?>
      <?php $addressURL = 'http://aleph.unibas.ch/F/?func=item-loan&adm_library=DSV51&doc_number=' . $item['localid'] . '&item_sequence=' . $item['sequencenumber'] ?>
      <a href="<?= $this->escapeHtml($addressURL)?>" target="_blank" title="<?= $this->transEsc('Address') ?>" onclick="swissbib.trackLink('<?=$this->escapeHtml($addressURL)?>')"><?= $this->transEsc('Address') ?></a>
    <?php endif; ?>
  </td>
</tr>
<tr>
  <th><?= $headers['location'] ?></th>
  <td>
    <?= $this->escapeHtml($item['locationLabel']) ?>
    <?= $mapLink ?>
    <?php if (isset($item['institutionUrl'])): ?>
      <a href="<?= $this->escapeHtml($item['institutionUrl']) ?>" target="_blank" title="<?=$this->transEsc('Library_Information')?>" data-lightbox-ignore onclick="swissbib.trackLink('<?=$this->escapeHtml($item['institutionUrl'])?>')"> <i class="fa fa-info-circle"></i></a>
    <?php endif; ?>
  </td>
</tr>
<tr>
  <th><?= $headers['callnr'] ?></th>
  <td><?= $this->escapeHtml($item['signature']) ?></td>
</tr>
<tr>
  <th><?= $headers['description'] ?></th>
  <td><?= $this->escapeHtml($description) ?></td>
</tr>
</tbody>
</table>