<?= $this->render('/detailpage/common/metadata/list.phtml',
    ['list' => $this->esperson()->getMetadata()->getList('job', 'birth', 'death', 'nationality')]) ?>

<?= $this->render('common/metadata/abstract.phtml') ?>

<?= $this->render('/detailpage/common/metadata/list.phtml',
    ['list' => $this->esperson()->getMetadata()->getList('notable.work', 'genre', 'names', 'pseudonym', 'spouse', 'influencers', 'influenced')]) ?>
