<?= $this->render('/detailpage/common/metadata/list.phtml',
    ['list' => $this->esperson()->getMetadata()->getList('job', 'birth', 'death', 'nationality', 'periodOfActivity')]) ?>

<?= $this->render('common/metadata/abstract.phtml') ?>

<?= $this->render('/detailpage/common/metadata/list.phtml',
    ['list' => $this->esperson()->getMetadata()->getList('awardReceived', 'positionHeld', 'playedInstrument', 'fieldOfStudy', 'notable.work', 'nationality', 'religion', 'nativeLanguage', 'languageSpoken', 'genre', 'affiliation', 'relatedCorporateBody', 'employer', 'memberOfPoliticalParty', 'educatedAt', 'participantOf', 'names', 'pseudonym', 'realIdentity', 'spouse', 'child', 'parent', 'sibling', 'influencers', 'influenced', 'acquaintanceshipOrFriendship', 'professionalRelationship')]) ?>
