<div class="row">
    <div class="col-sm-2">
        <h2 class="name visible-xs-block"><?= $this->esperson()->getDisplayName() ?></h2>
        <?= $this->render('common/thumbnail.phtml') ?>
    </div>
    <div class="col-sm-10">
        <div class="row">
            <div class="col-sm-12">
                <h2 class="name hidden-xs"><?= $this->esperson()->getDisplayName() ?></h2>
                <?= $this->render('common/metadata.phtml') ?>
            </div>
        </div>
    </div>
</div>