#'@parent_yaml': "local/config/vufind/detail-view-field-structure.yaml"

# "name" matches "Gruppierungsname / Oberbegriff"
# "labelKey" matches "Bezeichnung"
# "entries" matches "Unterbezeichnung"

structure:
  "Basisinformationen":
    "Titel":
      type: compound
      mode: line
      entries:
        - "Titel"
        - "Untertitel"
        - "Autor"
    "Signatur":
      type: compound
      mode: inline
      repeated: true
      entries:
        - "institution-code"
        - "standort code"
        - "Signatur1"
        - "Signatur2"
  "Sucheinstiege":
    "Person1":
    "Person2":
    "Ort":
  "Thema":
    "Formschlagwort":
    "Alternativtitel":
    "Sachbegriff":
      repeated: true
  "Inhalt und innere Ordnung":
    "Inhalt-505":
      type: sequences
      sequences: # from Swissbib/RecordDriver/SolrMarc.php getTableOfContent()
        - [ "g", "t", "r" ]
        - [ "g", "t" ]
        - [ "g", "r" ]
        - [ "t", "r" ]
        - [ "t" ]
        - [ "r" ]
        - [ "a" ]
