#'@parent_yaml': "local/config/vufind/detail-view-field-structure.yaml"

# "name" matches "Gruppierungsname / Oberbegriff"
# "labelKey" matches "Bezeichnung"
# "entries" matches "Unterbezeichnung"

structure:
  "Basisinformationen":
    fields:
      "Signatur":
        type: compound
        formatter:
          name: inline
          separator: "; " # for inline formatter only
          repeated: true
          entries:
            - name: "institution-code"
            - name: "standort code"
            - name: "Signatur1"
            - name: "Signatur2"
      "Dokumenttyp":
      "Art der Ressource":
      "Digitalisat":
      "Titel":
        type: compound
        formatter:
          name: line
          entries:
            - name: "Titel"
            - name: "Untertitel"
            - name: "Autor"
      "Entstehungsangaben":
      "Erscheinungsangaben":
      "Vertriebsangabe":
      "Herstellungsangaben":
      "Copyrightjahr":
      "Verzeichnungsstufe":
      "Auflage / Ausgabenvermerk /Entstehungsstufe":
      "Kartendaten und Karteninformationen":
      "Physische Beschreibung":
      "Physische Beschaffenheit":
      "Serie":
      "Enthalten in:":
  "Inhalt und innere Ordnung":
    fields:
      "Inhalt-505":
        type: sequences
        formatter:
          # without "entries:" the order of the applied sequence is used (see "sequences:" below)
          entries:
            - name: "Inhalt3-r"
            - name: "Inhalt3-t"
            - name: "Inhalt3-g"
            - name: "Inhalt3-a"
        # note that "sequences:" entries are sorted to guarantee the "longest" match
        # use "entries:" (see above) for another order of sequences
        sequences: # from Swissbib/RecordDriver/SolrMarc.php getTableOfContent()
          - [ "g", "t", "r" ]
          - [ "g", "t" ]
          - [ "g", "r" ]
          - [ "t", "r" ]
          - [ "t" ]
          - [ "r" ]
          - [ "a" ]
      "Ordnung":
      "Begleitmaterial":
      "Lokale Sacherschliessung Bibliographie / Fachcodes":
      "Lokale Sacherschliessung Bibliographie":
  "Anmerkungen":
    fields:
      "Allgemeine Anmerkung":
      "Sprache, Schrift, Notation":
      "Anmerkung Musik":
      "Originalausgabe":
      "Anmerkung zur Reproduktion":
      "Mitwirkende Film":
      "Darsteller":
      "Datum und Ort der Aufzeichnung":
      "Identifikation des Exemplars":
      "Identifikator":
      "Fingerprint Identifikator":
      "Verlagsbestellnummer":
      "ISBN":
      "Bibliographischer Nachweis":
  "Geschichte":
    fields:
      "Entstehungs-, Besitz- und Sammlungsgeschichte":
      "Neuzugänge":
      "Akzession":
      "Geschichte des Aktenbildners":
      "Ausstellungen":
      "Ehemalige Signatur":
  "Angaben zum Objekt":
    fields:
      "Anmerkungen zum Exemplar":
  "Einband":
    fields:
      "Einband":
  "Buchblock":
    fields:
      "Beschreibstoff":
      "Lagen":
      "Zählungen":
  "Ausstattung":
    fields:
      "Rubrizierungen":
      "Initialen":
      "Miniaturen / Zeichnungen":
      "Einrichtung":
      "Schrift":
      "Zusätze":
  "Hinweise":
    fields:
      "Bibliographischer Nachweis":
      "Literatur":
      "Verwandte Ressource":
      "Verwandtes Material":
      "Zusätzliche Publikationsformen":
  "Bearbeitungsstand":
    fields:
      "Interne Bearbeitung":
  "Klassifikationen":
    fields:
      "Klassifikation":
  "Code":
    fields:
      "Code Bibliographie":
  "Identifikatoren":
    fields:
      "Systemnummer":
      "alte Systemnummer":
      "alte Inventarnummer":
  "Zugriffs- und Benutzungsbestimmungen":
    fields:
      "Zugangsbestimmungen":
      "Schutz- und Sperrfristen":
      "Hinweise auf Findmittel":
      "Gesetzliche Bestimmungen":
      "Urheberrecht Objekt":
      "Urheberrecht Metadaten":
  "Sucheinstiege":
    groups:
      "Person":
        formatter:
          name: "sucheinstiege-person" # handle all fields "Person" with this formatter
          roleOrder: # all other roles are printed at the end
            - "cmp"
            - "wpr"
            - "edt"
          roleMarcSubfields: # specific for "sucheinstiege-person"
            - "4"
            - "4rcp"
          hiddenMarcSubfields: # specific for "sucheinstiege-person"
            - "4"
            - "4rcp"
            - "e"
    fields:
      "Person":
        type: compound # expected by "sucheinstiege-person" formatter, because "entries" are needed too
        formatter:
          name: inline
          separator: " / "
          entries:
            - name: "Person-a"
            - name: "Person-t"
            - name: "Person-k"
            - name: "Person-d"
              formatter:
                name: "date"
            - name: "Person-0"
      "Körperschaft":
      "Kongress":
      "Werktitel":
      "Eintragung Ort":
      "Ort":
  "Thema":
    fields:
      "Person":
      "Körperschaft":
      "Kongress":
      "Sachbegriff":
        formatter:
          repeated: true
      "Geografikum":
      "Werktitel":
      "Zeit / Zeitspanne als Schlagwort":
      "Formschlagwort":
      "Form des Werks":
      "Besetzung":
      "Schlagwort Musik":
      "Alternativtitel":
      "Früherer Titel":
      "Bevorzugter Titel / Zitiertitel":
      "Einheitstitel":
      "Originaltitel":
  "Spezialsucheinstiege Handschriften":
    fields:
      "Initien":
      "Gebetsinitien (dt.)":
      "Ikonografie":
      "Repertorien":
