#'@parent_yaml': "local/config/vufind/detail-view-field-structure.yaml"

# "name" matches "Gruppierungsname / Oberbegriff"
# "labelKey" matches "Bezeichnung"
# "entries" matches "Unterbezeichnung"

structure:
  "Basisinformationen":
    "Titel":
      type: compound
      mode: line
      entries:
        - "Titel"
        - "Untertitel"
        - "Autor"
    "Signatur":
      type: compound
      mode: inline
      entries:
        - "institution-code"
        - "standort code"
        - "Signatur1"
        - "Signatur2"
  "Sucheinstiege":
    "Person1":
    "Person2":
    "Ort":
  "Thema":
    "Formschlagwort":
    "Alternativtitel":