<div class="home-content-box">
  <h2 class="lead">Come comminciare?</h2>
  <p>Introduzione di swissbib Basel Bern</p>
  <p><a href="https://tube.switch.ch/videos/bf25f32d" target="_blank" class="btn btn-link"><i class="fa fa-video-camera"></i> Come ricercare?</a></p>
  <p><a href="https://tube.switch.ch/videos/d2f4ff5e" target="_blank" class="btn btn-link"><i class="fa fa-video-camera"></i> Come richiedere?</a></p>
  <p><a href="https://tube.switch.ch/videos/0542438f" target="_blank" class="btn btn-link"><i class="fa fa-video-camera"></i> Articoli & più</a></p>
  <a href="<?= $this->url('help-page', array('topic' => 'faq')); ?>" class="btn btn-link"><?= $this->transEsc('helppage') ?></a>
</div>
