<div class="home-content-box">
    <h2 class="lead">"UBH Ap II 18920"? - erfolgreich nach Signaturen suchen</h2>
    <p>Haben Sie sich nur die Signatur gemerkt und möchten Sie das Buch in swissbib Basel Bern gerne wiederfinden?</p>

    <a href="<?= $this->redirectProtocolWrapper()->getWrappedURL('http://swissbib-baselbern.blogspot.ch/search/label/Tipp') ?>" target="_blank" class="btn btn-link">Mehr Informationen im Blog</a>
</div>
