<div class="home-content-box">
    <h2 class="lead">Auf Einschränkungen folgen zahlreiche Optionen</h2>
    <p> Ab dem 7. Dezember haben Kund*innen Zugriff auf das Rechercheportal swisscovery. Dieses löst die bisherigen Bibliothekskataloge ab, so auch swissbib Basel Bern. 
    </p>

    <a href="http://swissbib-baselbern.blogspot.ch/search/label/Tipp" target="_blank" class="btn btn-link">Mehr Informationen im Blog</a>
</div>
