<div class="home-content-box">
  <h2 class="lead">Da dove cominciare?</h2>
  <p>swissbib Basel Bern si presenta</p>
  <p><a href="https://tube.switch.ch/videos/d8d59fc8" target="_blank" class="btn btn-link"><i class="fa fa-video-camera"></i> Come cercare nel catalogo</a></p>
  <p><a href="https://tube.switch.ch/videos/d2f4ff5e" target="_blank" class="btn btn-link"><i class="fa fa-video-camera"></i> Come accedere ai documenti</a></p>
  <p><a href="https://tube.switch.ch/videos/ea02c388" target="_blank" class="btn btn-link"><i class="fa fa-video-camera"></i> Cercare e scaricare e-book</a></p>
  <p><a href="https://tube.switch.ch/videos/0542438f" target="_blank" class="btn btn-link"><i class="fa fa-video-camera"></i> Articoli & più</a></p>
</div>
