<div class="home-content-box">
    <h2 class="lead">A proposito di swissbib Basel Bern</h2>

    <p>
        swissbib Basel Bern è il catalogo delle biblioteche accademiche di Basilea e Berna e della Biblioteca nazionale svizzera
    </p>
    <a href="http://swissbib-baselbern.blogspot.ch/search/label/Tipp" target="_blank" class="btn btn-link">Aktuell im Blog: Alles zum Thema Gebühren</a>
    <a href="<?= $this->url('help-page', ['topic' => 'about']); ?>" class="btn btn-link">Ulteriori informazioni</a><br/>
    <a href="<?= $this->url('help-page', ['topic' => 'faq']); ?>" class="btn btn-link"><?= $this->transEsc('helppage') ?></a>
</div>
