<li><a href="<?= $this->url('help-page', ['topic' => 'about']); ?>"><?= $this->transEsc('helppage.about') ?></a></li>
<li><a href="<?= $this->url('help-page', ['topic' => 'faq']); ?>"><?= $this->transEsc('helppage') ?></a></a></li>
<li><a href="http://swissbib-baselbern.blogspot.ch/" target="_blank">Blog</a></li>
<?php if ($this->feedback()->tabEnabled()): ?>
<li><a href="<?= $this->url('feedback-home') ?>"><?= $this->transEsc("menu.contact") ?></a></li>
<?php endif; ?>