<?php
/** @var VuFind\RecordDriver\SolrDefault $record */
$record = $this->driver;
/** @var Swissbib\View\Helper\Record $viewRecord */
$viewRecord = $this->record($record);

$id = $record->getUniqueId();
$shortTitle = $record->getShortTitle();
$titleStatement = $record->getTitleStatement(true);
$subtitle = $viewRecord->getSubtitle($titleStatement);
$responsible = $viewRecord->getResponsible($titleStatement, $record);
$publications = $record->getPublicationDetails();
$physicalDescriptions = $record->getPhysicalDescriptions(false);
$edition = $record->getEdition();
$cartMathData = $record->getCartMathData();
$formats = $viewRecord->getFormatList();
$hierarchicalLevel = $record->getHierachicalLevel();
$hostItems = $record->getHostItemEntry();
$journalTitle = $record->getContainerTitle();
$ref = $record->getContainerReference();
$highlightedFulltext = $record->getHighlightedFulltext();

$showFRBR = $this->configAccess()->Site->displayFrbr;
$groupID = $this->driver->getGroup(true);

$urls = $viewRecord->getExtendedLinkDetails();

$nl = null;
if($searchClassId != "Summon") {
    try {
        $nl = $this->nationalLicences()->getUrl($record);
    } catch (\Exception $e) {
        //this is the case for swissbib orange and jusbib
        $nl = null;
    }
}
if ($nl) {
    $linkNL = ['url' => $nl['url'], 'desc' => "Get it Online (National Licence)"];
    array_push($urls, $linkNL);
}
$link360 = $viewRecord->getLink360();
$linkSFX = $viewRecord->getLinkSFX();

?>

<div class="row" vocab="http://schema.org/" resource="#record" typeof="<?=$this->driver->getSchemaOrgFormats()?> Product">

  <div class="col-sm-3 hidden-xs">
    <div class="thumbDetailView hidden-print">
      <?php /* Display thumbnail if appropriate: */ ?>
      <?php $mediumThumb = $viewRecord->getThumbnail('medium'); ?>
          <img alt="<?=$this->transEsc('Cover Image')?>" class="recordcover" src="<?=$this->escapeHtmlAttr($mediumThumb);?>"/>

      <?php /* Display qrcode if appropriate: */ ?>
      <?php $QRCode = $viewRecord->getQRCode("core"); ?>
      <?php if($QRCode): ?>
        <span class="hidden-xs">
          <br/><img alt="<?=$this->transEsc('QR Code')?>" class="qrcode" src="<?=$this->escapeHtmlAttr($QRCode);?>"/>
        </span>
      <?php endif; ?>
    </div>

    <?php // if you have a preview tab but want to move or remove the preview link
    // from this area of the record view, this can be split into
    // getPreviewData() (should stay here) and
    // getPreviewLink() (can go in your desired tab) ?>
    <?=$viewRecord->getPreviews()?>
  </div>

  <div class="col-sm-9 col-xs-12">
    <h2 property="name"><?=$this->escapeHtml($shortTitle)?></h2>
    <?php if (isset($subtitle)): ?>
      <h4 class="resultViewSubTitle"><?= $this->escapeHtml($subtitle) ?></h4>
    <?php endif; ?>

    <?php if ($this->userlist()->getMode() !== 'disabled'): ?>
      <?php /* Display the lists that this record is saved to */ ?>
      <div class="savedLists hidden alert alert-info" id="savedLists">
        <strong><?=$this->transEsc("Saved in")?>:</strong>
      </div>
    <?php endif; ?>

    <?/* Display Main Details */?>
    <div class="meta" summary="<?=$this->transEsc('Bibliographic Details')?>">
    <?php if (!empty($responsible)): ?>
        <div class="row">
        <!-- Verfasser / Beitragende -->
        <div class="col-sm-4"><?=$this->transEsc('Author')?>:</div>
        <div class="col-sm-8"><?=$this->escapeHtml($responsible)?></div>
        </div>
    <?php endif; ?>

    <!-- Impressum -->
    <?php if (!empty($publications)): ?>
      <div class="row">
          <div class="col-sm-4"><?=$this->transEsc('Publication')?>: </div>
          <div class="col-sm-8">
              <?php foreach ($publications as $field): ?>
                  <span property="publisher" typeof="Organization">
                      <?php $pubPlace = $field->getPlace(); if (!empty($pubPlace)): ?>
                          <span property="location"><?=$this->escapeHtml($pubPlace)?> :</span>
                      <?php endif; ?>
                      <?php $pubName = $field->getName(); if (!empty($pubName)): ?>
                          <span property="name"> <?=$this->escapeHtml($pubName)?>, </span>
                      <?php endif; ?>
                  </span>
                  <?php $pubDate = $field->getDate(); if (!empty($pubDate)): ?>
                      <span property="publicationDate"><?=$this->escapeHtml($pubDate)?></span>
                  <?php endif; ?>
                  <?php if(!next($publications) === false){echo '<br />';} ?>
              <?php endforeach; ?>
          </div>
      </div>
    <?php endif; ?>

    <?php if (!empty($journalTitle)): ?>
      <div class="row">
      <div class="col-sm-4"><?=$this->transEsc('Journal Title')?>:</div>
          <div class="col-sm-8">
            <?=$this->escapeHtml($journalTitle) . ',' . ' '?>
            <?php if (!empty($ref)) { echo $this->escapeHtml($ref); } ?>
          </div>
      </div>
      <?php endif; ?>

      <?php if ($hostItems): ?>
        <div class="row">
        <div class="col-sm-4"><?= $this->transEsc('note_773') ?>: </div>
        <div class="col-sm-8">
          <?php foreach ($hostItems as $hostItem): ?>
              <?php $text = isset($hostItem['title']) ? (array_key_exists('related', $hostItem) ? $hostItem['title'] . ', ' . $hostItem['related'] : $hostItem['title']) : '' ?>
              <?= $this->escapeHtml($text) ?><br />
          <?php endforeach; ?>
        </div>
        </div>
      <?php endif; ?>

      <?php if ($cartMathData): ?>
        <div class="row">
          <div class="col-sm-4"><?= $this->transEsc('Map_Scale') ?>:</div>
          <div class="col-sm-8"><?= $this->escapeHtml($cartMathData) ?></div>
        </div>
      <?php endif; ?>

      <?php if ($physicalDescriptions): ?>
        <div class="row">
          <div class="col-sm-4"><?= $this->transEsc('Physical Description') ?>:</div>
          <div class="col-sm-8"><?= $this->physicalDescription($physicalDescriptions) ?></div>
        </div>
      <?php endif; ?>

      <?php if (!empty($formats)): ?>
        <div class="row">
          <div class="col-sm-4"><?=$this->transEsc('Format')?>: </div>
          <div class="col-sm-8"><?= $formats ?></div>
        </div>
      <?php endif; ?>

      <?php if (!empty($hierarchicalLevel)): ?>
        <div class="row">
          <div class="col-sm-4"><?=$this->transEsc('hierarchical_level')?>: </div>
          <div class="col-sm-8"><?= $this->laminasTranslate($hierarchicalLevel, 'formats') ?></div>
        </div>
      <?php endif; ?>

      <?php if (!empty($edition)): ?>
        <div class="row">
          <div class="col-sm-4"><?=$this->transEsc('Edition')?>: </div>
          <div class="col-sm-8"><?=$this->escapeHtml($edition)?></div>
        </div>
      <?php endif; ?>

      <?php if (!empty($urls)): ?>
        <div class="row">
          <div class="col-sm-4"><?=$this->transEsc('Online Access')?>: </div>
          <div class="col-sm-8">
            <?php foreach ($urls as $current): ?>
              <a href="<?=$this->escapeHtmlAttr($this->proxyUrl($current['url']))?>" target="_blank" title="<?=$this->escapeHtml($current['desc'])?>">
                  <?=$this->escapeHtml($current['desc'])?>
              </a><br/>
            <?php endforeach; ?>
            <?php if ($linkSFX): ?>
              <?= $linkSFX ?><br/>
            <?php endif; ?>
            <?php if(!empty($nl['message'])): ?>
            <div class="flash-message alert alert-info">
                <strong><?= $nl['message'] ?></strong>
            </div>
            <?php endif; ?>
          </div>
        </div>
      <?php endif; ?>

      <?php if (!empty($link360) || $linkSFX): ?>
        <div class="row">
          <div class="col-sm-4"><?= $this->transEsc('Online Access') ?>: </div>
          <div class="col-sm-8">
              <a title="<?= $this->transEsc('articles.link360') ?>" class="linkbutton primary icon_link_primary"
                 target="_blank" href="<?= $link360 ?>">get&#160;it</a><br/>
              <?=$linkSFX ?>
          </div>
        </div>
      <?php endif; ?>

      <?php if ($id): ?>
        <span class="label visible-print-inline"><?= $this->transEsc('Item_ID') ?>:</span>
        <span class="visible-print-inline"><?= $id ?></span>
      <?php endif; ?>

      <?php if (!empty($showFRBR) && $showFRBR && !empty($groupID)) : ?>
       <span class="hidden-xs">
         <a href="<?=
          $this->url('search-results') . '?lookfor=' . $groupID . "&type=FRBR&sort=publishDateSort+desc" ?>"
             class="btn btn-primary otherEditions" title="<?= $this->transEsc('Other Editions') ?>">
              <span><?= $this->transEsc('Other Editions') ?></span>
          </a>
       </span><br />
      <?php endif; ?>

      <?php if ($highlightedFulltext): ?>
              <span class="label"><?= $this->transEsc('fulltexthighlight') ?>: </span>
              <span><br />
              <?= $this->highlight($highlightedFulltext) ?></span>
      <?php endif; ?>

    </div>
    <?/* End Main Details */?>
  </div>
</div>