<?php $this->essubjectcollection()->setCollection($this->{$this->collection}); ?>

<?php if ($this->essubjectcollection()->hasItems()): ?>
    <div class="row metadata <?= $this->collection ?>">
        <div class="col-sm-3"><?= $this->translate('subject.metadata.subject.' . $this->collection) ?></div>
        <div class="col-sm-9"><?= $this->render('subjects/links.phtml'); ?></div>
    </div>
<?php endif; ?>