<div class="common">
    <ul class="metadata">
        <?= $this->context($this)->renderInContext('knowledgecard/common/metadata/list.phtml', ['list' => $this->essubject()->getMetadata()->getList('variants', 'definition')]) ?>
        <li class="entry section-end"><?= $this->render('knowledgecard/subject/parents.phtml'); ?></li>
        <li class="entry"><?= $this->render('knowledgecard/subject/children.phtml'); ?></li>
    </ul>
</div>