<li><a class="help-link" data-lightbox href="<?=$this->url('help-home')?>?topic=search"><?= $this->transEsc('Search Tips') ?></a></li>
<li><a href="<?= $this->url('help-page', ['topic' => 'about_jusbib']); ?>"><?= $this->transEsc('helppage.about_jusbib') ?></a></li>
<?php if ($this->feedback()->tabEnabled()): ?>
    <li><a href="<?= $this->url('feedback-home') ?>"><?= $this->transEsc("menu.contact") ?></a></li>
<?php endif; ?>