<?php if (count($this->records) > 0) : ?>
<div class="separator"></div>
<div class="tagcloud">
    <a id="detailpage-<?= $this->name ?>"></a>
    <h2><?= $this->headline ?></h2>
    <?php foreach ($this->records as $recordName => $recordValue): ?>
        <?php $record = $recordValue[strtolower($this->type)] ?>
        <span>
        <?= $this->render('/detailpage/common/tagcloud/link.phtml', [
                'name' => $recordName,
                'record' => $record,
                'weight' => $recordValue['weight'],
                'type' => $this->type
            ]);
        ?>
        <?php if ($record->hasSufficientData()): ?>
            <?= $this->render('/knowledgecard/common/link.phtml', [
                    'type' => strtolower($this->type),
                    'record' => $record
                ]);
            ?>
        <?php endif; ?>
        </span>
    <?php endforeach; ?>
</div>
<?php endif; ?>
