<? if ($this->esperson()->hasAbstract()): ?>
    <? $abstractInfo = $this->esperson()->getAbstractInfo(); ?>

    <li class="entry section-start">
        <span class="entry-label"><?= $abstractInfo->label ?></span>
        <span class="entry-value"><?= $abstractInfo->text ?></span>
        <? if ($abstractInfo->truncated): ?>
            <span class="ellipsis"></span>
            <?= $this->esperson()->getDetailPageLink('<a class="ref external more" data-lightbox-ignore href="%s">%s</a>', 'card.knowledge.common.more') ?>
        <? endif; ?>
    </li>
<? endif; ?>
