<h1>A proposito di swissbib Basel Bern</h1>
<p>swissbib Basel Bern comprende più di 7 mio. di notizie bibliografiche provenienti da oltre 200 <a href="<?= $this->basePath('Libraries') ?>" title="Liste der Institutionen">biblioteche accademiche di Basilea e Berna</a>. Tra queste vi sono le biblioteche universitarie di Basilea e Berna, la Biblioteca nazionale svizzera, alcune biblioteche specializzate e biblioteche di scuole universitarie professionali. Vi sono inoltre catalogate le collezioni di quattro biblioteche ubicate al di fuori delle regioni di Basilea e Berna, vale a dire la Kooperative Speicherbibliothek Schweiz, la Zentralbibliothek Solothurn e l'Istituto Universitario Federale per la Formazione Professionale di Losanna e Lugano.</p>
<p>Questo progetto, affidato al <a href="http://www.informationsverbund.ch/21.0.html" target="_blank">sistema bibliotecario IDS Basel Bern</a>, si serve dell'infrastruttura e del know-how del metacatalogo nazionale <a href="https://www.swissbib.ch" target="_blank" title="swissbib">swissbib</a>.</p>
<h2>Che cosa si trova in swissbib Basel Bern?</h2>
<p>swissbib Basel Bern è suddiviso in due banche dati separate:</p>
<p><strong>Libri & più</strong></p>
<ul>
    <li>per diversi tipi di documenti, come libri/ebook, riviste/ejournal, giornali, CD/DVD, banche dati, ecc. Vengono catalogati i <strong>titoli</strong> di questi documenti, <strong> ma di regola non i singoli articoli o capitoli</strong> in essi contenuti.</li>
    <li>per riviste scientifiche retrodigitalizzate in Svizzera (progetto E-Periodica), con accesso diretto ai testi integrali degli articoli.</li>
</ul>
<p><strong>Articoli & più</strong></p>
<ul>
    <li><strong>per singoli articoli, capitoli, contributi,</strong> ecc. estratti da numerosi ejournal, ebook e banche dati messi a disposizione dalle università di Basilea, risp. Berna. Nella maggior parte dei casi è possibile l'accesso diretto al testo integrale, se si è connessi con la rete del proprio ateneo.</li>
    <li>per risorse elettroniche disponibili gratuitamente in Internet, e dunque accessibili anche al di fuori della rete universitaria di Basilea e Berna.</li>
</ul>
<p>Gli articoli che non sono accessibili direttamente in versione elettronica possono essere ordinati presso la tua biblioteca tramite i <i class="fa fa-external-link"></i> servizi SFX.</p>
<h2>Guida video</h2>
<p><a href="https://tube.switch.ch/videos/d8d59fc8" target="_blank" class="btn btn-link"><i class="fa fa-video-camera"></i> Come cercare nel catalogo</a></p>
<p><a href="https://tube.switch.ch/videos/d2f4ff5e" target="_blank" class="btn btn-link"><i class="fa fa-video-camera"></i> Come accedere ai documenti</a></p>
<p><a href="https://tube.switch.ch/videos/ea02c388" target="_blank" class="btn btn-link"><i class="fa fa-video-camera"></i> Cercare e scaricare e-book</a></p>
<p><a href="https://tube.switch.ch/videos/0542438f" target="_blank" class="btn btn-link"><i class="fa fa-video-camera"></i> Articoli & più</a></p>
<h2>Contatto</h2>
<p>Siamo lieti di aiutarti nella ricerca o nell'ordinazione di documenti nel nostro catalogo, e di ricevere suggerimenti o critiche: <a href="<?= $this->url('feedback-home') ?>">modulo di contatto</a></p>
<h2>News</h2>
Iscriviti al nostro <a href="http://swissbib-baselbern.blogspot.ch" target="_blank">blog</a>.
