<div class="home-content-box">
    <h2 class="lead">Dataset</h2>
    <p>
        Currently the dataset which was delivered by swissbib for TL2 is available here.
        <br><br>
        IDSBB: data until 8.7.2019
        <br>
        IDSLU: data until 19.7.2019
        <br>
        IDSSG: data until 17.7.2019
        <br>
        NEBIS: data until 23.6.2019
        <br>
        RERO: data until 8.7.2019
        <br>
        SBT: data until 1.7.2019
    </p>
    <br>
    <p>
        Currently there is no difference in the deduplication configuration.
    </p>
</div>
