<div class="home-content-box">
    <h2 class="lead">Wie zufrieden sind Sie mit swissbib?</h2>
    <p>Wir wollen uns für Sie weiter entwickeln.
        Helfen Sie uns, mit ihrer Meinung die Zukunft von swissbib zu gestalten!</p>
    <a href="<?= $this->redirectProtocolWrapper()->getWrappedURL('https://admin.swissbib.ch/limesurvey/index.php/838924?newtest=Y&lang=de') ?>" target="_blank" class="btn btn-link">Zur Umfrage</a>
</div>