<div class="home-content-box">
    <h2 class="lead">Dataset</h2>
    <p>
        Currently the dataset which was delivered by swissbib for TL3 is available here. There are some exceptions due to selected updates, see <a href="https://here.slsp.ch/display/TES/Changes+in+the+matching+algorithm+for+TL3-1.5" target="_blank">documentation</a> for further information.
        <br><br>
        IDSBB: data until 15.1.2020
        <br>
        IDSLU: data until 24.1.2020
        <br>
        IDSSG: data until 17.1.2020
        <br>
        NEBIS: data until 19.1.2020
        <br>
        RERO: data until 6.1.2020
        <br>
        SBT: data until 10.12.2019
    </p>
    <br>
    <p>
        The deduplication configuration has been adapted for the second matching test phase.
    </p>
</div>
