<div class="home-content-box">
    <h2 class="lead">swissbib interface for testing deduplication for SLSP</h2>
    <p>
        This swissbib interface provides access to the data processed for SLSP and is used for testing the deduplication. This enables testers to test the deduplication in between the test migrations to Alma.<br/>
        <b>Please do not</b> use this interface for testing the migrated records. The marc fields should be checked in Alma/Primo, as some of the data might be displayed differently on the swissbib interface.
    </p>
</div>