<div class="home-content-box">
  <h2 class="lead">Die Zukunft des Schweizer Metakatalogs swissbib</h2>
  <p>Einiges wurde bereits berichtet, vieles blieb aber bislang noch offen: Wie geht es weiter mit swissbib nach dem Start der Swiss Library Service Platform SLSP am 1. Januar 2021? Nach einem Jahr intensiver Klärungsgespräche können wir nun erste konkrete Aussichten formulieren.</p>
  <a href="https://swissbib.blogspot.com/2020/01/die-zukunft-des-schweizer-metakatalogs.html" target="_blank" class="btn btn-link">Plus d'informations</a>
</div>