<div class="home-content-box">
    <h2 class="lead">swisscovery - neuer Sucheinstieg</h2>
    <p>Ab dem 7. Dezember 2020 stellt SLSP mit <a href="https://www.swisscovery.org/" target="_blank">swisscovery</a> das neue Discovery für wissenschaftliche Bibliotheksbestände in der Schweiz. swissbib wird ab diesem Zeitpunkt nur noch teilweise aktualisiert und per Ende März 2021 eingestellt.</p>
    <p>Weiterführende Infos auf der Webseite von <a href="https://slsp.ch/de"  target="_blank">SLSP</a> sowie auf den Webseiten der beteiligten Bibliotheken.</p>

  <a href="https://swissbib.blogspot.com/2020/11/zur-einstellung-der-swissbib.html" target="_blank" class="btn btn-link">Mehr Informationen</a>
</div>