<div class="home-content-box">
    <h2 class="lead">swisscovery - neuer Sucheinstieg</h2>
    <p>Ab dem 7. Dezember 2020 wird SLSP mit swisscovery das neue Discovery für wissenschaftliche Bibliotheksbestände in der Schweiz stellen. swissbib wird ab diesem Zeitpunkt nicht mehr aktualisiert und per Ende März 2021 eingestellt.</p>
    <p>Weiterführende Infos folgen auf der Webseite von <a href="https://slsp.ch/de"  target="_blank">SLSP</a> sowie auf den Webseiten der beteiligten Bibliotheken.</p>

  <a href="https://swissbib.blogspot.com/2020/01/die-zukunft-des-schweizer-metakatalogs.html" target="_blank" class="btn btn-link">Mehr Informationen</a>
</div>