<div class="home-content-box">
  <h2 class="lead">swissbib und Linked Open Data</h2>
  <p>In den letzten Wochen haben wir drei wesentliche Erweiterungen von swissbib online publiziert.</p>
  <ul class="home-box-list">
    <li>swissbib ist jetzt mit Wikidata verlinkt</li>
    <li>Zahlreiche weitere Verknüpfungen von swissbib mit externen Daten sind vorhanden</li>
    <li>Neue Version der <a href="https://data.swissbib.ch/">swissbib Linked Open Data API</a></li>
  </ul>
  <a href="https://swissbib.blogspot.com/2020/03/wikidata.html" target="_blank" class="btn btn-link">Mehr Informationen</a>
</div>