<div class="home-content-box">
  <h2 class="lead">swissbib and Linked Open Data</h2>
  <p>New developments for swissbib and Linked Open Data.</p>
  <ul class="home-box-list">
    <li>swissbib is linked with Wikidata</li>
    <li>There are much more links between swissbib and external data sources about persons and organisations</li>
    <li>New Version of the <a href="https://data.swissbib.ch/">swissbib Linked Open Data API</a></li>
  </ul>
  <a href="https://swissbib.blogspot.com/2020/03/wikidata.html" target="_blank" class="btn btn-link">More information</a>
</div>