<div class="home-content-box">
    <h2 class="lead">swisscovery - new discovery</h2>
    <p>As of December 7 2020 SLSP will provide swisscovery as the new discovery for resources of scientific libraries in Switzerland. swissbib will cease to update content in December and will be discontinued by the end of March 2021.</p>
    <p>Further information will be provided on the websites of <a href="https://slsp.ch/en"  target="_blank">SLSP</a> and of the participating libraries.</p>
</div>