<div class="home-content-box">
  <h2 class="lead">Search swissbib using Person information from Wikipedia</h2>
  <p>Looking for the latest books from Nobel Prizes in Literature ? Or from an author born in a specific city ? This is possible when you match the library catalog with Wikipedia.</p>
  <a href="https://swissbib.blogspot.com/2020/07/auf-wikipediawikidata-basierende-suchen.html" target="_blank" class="btn btn-link">More information</a>
</div>