<?php
  $this->headTitle($this->translate('Browse the Collection Alphabetically'));
  $this->layout()->breadcrumbs = '<a href="' . $this->url('alphabrowse-home') . '">' . $this->transEsc('Browse Alphabetically') . '</a>';
  $baseQuery = ['source' => $this->source, 'from' => $this->from];

  // Set up upper search box if necessary:
  if ($this->searchbox()->alphaBrowseOptionsEnabled()) {
    $this->layout()->searchbox = $this->context($this)->renderInContext(
        'search/searchbox.phtml',
        [
          'lookfor' => $this->from,
          'searchIndex' => 'AlphaBrowse:' . $this->source,
        ]
    );
  }
?>

<?php /* LOAD THE LINK INFORMATION INTO $pageLinks, similar to smarty's {capture} */ ?>
<?php ob_start(); ?>
  <ul class="pager">
    <?php if (isset($this->prevpage)): ?>
      <li>
        <a href="<?=$this->escapeHtmlAttr($this->url('alphabrowse-home', [], ['query' => $baseQuery + ['page' => $this->prevpage]]))?>" aria-label="<?=$this->transEsc('page_prev')?>">
          <i class="fa fa-angle-left" aria-hidden="true"></i>
          <?=$this->transEsc('Prev')?>
        </a>
      </li>
    <?php else: ?>
      <li class="disabled" aria-hidden="true"><i class="fa fa-angle-left"></i> <?=$this->transEsc('Prev')?></li>
    <?php endif; ?>

    <?php if (isset($this->nextpage)): ?>
      <li>
        <a href="<?=$this->escapeHtmlAttr($this->url('alphabrowse-home', [], ['query' => $baseQuery + ['page' => $this->nextpage]]))?>" aria-label="<?=$this->transEsc('page_next')?>">
          <?=$this->transEsc('Next')?>
          <i class="fa fa-angle-right" aria-hidden="true"></i>
        </a>
      </li>
    <?php else: ?>
      <li class="disabled" aria-hidden="true"><?=$this->transEsc('Next')?> <i class="fa fa-angle-right"></i></li>
    <?php endif; ?>
  </ul>
<?php $pageLinks = ob_get_contents(); ?>
<?php ob_end_clean(); ?>

<?php if (!empty($this->source)): ?>
<?php // TODO: Use roles/subcategories ?>
  <form class="form-inline" method="get" action="<?=$this->url('alphabrowse-home')?>" name="alphaBrowseForm" id="alphaBrowseForm">
    <select id="alphaBrowseForm_source" name="source" class="form-control">
      <?php foreach ($this->alphaBrowseTypes as $key => $item): ?>
        <option value="<?=$this->escapeHtmlAttr($key) ?>"<?php if ($this->source == $key): ?> selected="selected"<?php endif; ?>><?=$this->transEsc($item) ?></option>
      <?php endforeach; ?>
    </select>
    <label for="alphaBrowseForm_from"><?=$this->transEsc('starting from') ?></label>
    <input type="text" name="from" id="alphaBrowseForm_from" value="<?=$this->escapeHtmlAttr($this->from) ?>" class="form-control"/>
    <input class="btn btn-primary" type="submit" value="<?=$this->transEsc('Browse') ?>"/>
  </form>
<?php else: ?>
    <h2><?=$this->transEsc('Browse Alphabetically') ?></h2>
<ul>
    <?php foreach ($this->alphaBrowseTypes as $key => $item): ?>
    <li><a href="<?=$this->url('alphabrowse-home', [], [
              'query' => [
                'source' => $key
              ]
        ]
      )?>"><?=$this->transEsc($item)?></a></li>
    <?php endforeach; ?>
</ul>
<?php endif; ?>

<?php if ($this->result): ?>
  <?=$pageLinks ?>
  <table class="alphabrowse table table-striped">
    <thead>
      <tr>
        <th class="<?=$this->source ?>">
          <?=$this->transEsc("browse_" . $this->source) ?>
        </th>
        <th class="titles"><?=$this->transEsc("alphabrowse_matches") ?></th>
      </tr>
    </thead>
    <tbody>
      <?php $row = 0; ?>
      <?php foreach ($this->result as $item): ?>
        <?php if (isset($this->highlight_row) && $row == $this->highlight_row): ?>
          <tr class="browse-match">
          <?php if (isset($this->match_type) && ($this->match_type == "NONE")): ?>
            <?php // this is the right row but query doesn't match value ?>
            <td colspan="<?=count($this->extras) + 2;?>"><?=$this->transEsc('your_match_would_be_here')?></td>
            </tr>
            <tr>
          <?php endif; ?>
        <?php else: ?>
          <tr>
        <?php endif; ?>
          <td class="<?=$this->source ?>">
            <b>
              <?php if ($url = $this->alphabrowse()->getUrl($this->source, $item)): ?>
                <a href="<?=$this->escapeHtmlAttr($url)?>"><?=$this->escapeHtml($item['fieldvalue'])?></a>
              <?php else: ?>
                <?=$this->escapeHtml($item['fieldvalue'])?>
              <?php endif; ?>
            </b>

            <?php if (False && count($item['useInstead']) > 0): ?>
              <div>
                <?=$this->transEsc('Use instead') ?>:
                <ul>
                  <?php foreach ($item['useInstead'] as $heading): ?>
                  <li><a href="<?=$this->escapeHtmlAttr($this->url('alphabrowse-home', [], ['query' => ['from' => $heading] + $baseQuery]))?>"><?=$this->escapeHtml($heading)?></a></li>
                  <?php endforeach; ?>
                </ul>
              </div>
            <?php endif; ?>

            <?php if (False && count($item['seeAlso']) > 0): ?>
              <div>
                <?=$this->transEsc('See also') ?>:
                <ul>
                  <?php foreach ($item['seeAlso'] as $heading): ?>
                  <li><a href="<?=$this->escapeHtmlAttr($this->url('alphabrowse-home', [], ['query' => ['from' => $heading] + $baseQuery]))?>"><?=$this->escapeHtml($heading)?></a></li>
                  <?php endforeach; ?>
                </ul>
              </div>
            <?php endif; ?>

            <?php if ($item['note'] ?? false): ?>
              <div>
                <?=$this->transEsc('Note') ?>:
                <ul>
                  <li><?=$this->escapeHtml($item['note'])?></li>
                </ul>
              </div>
            <?php endif; ?>
          </td>

          <td class="titles">
            <?php if ($item['frequency'] > 0): ?>
              <?=$item['frequency']; ?>
            <?php endif; ?>
          </td>
        </tr>
        <?php $row++; ?>
        <?php endforeach; ?>
        <?php if (isset($this->highlight_end)): ?>
          <tr class="browse-match">
            <td colspan="<?=count($this->extras) + 2;?>"><?=$this->transEsc('your_match_would_be_here')?></td>
          </tr>
        <?php endif; ?>
    </tbody>
  </table>
  <?= $pageLinks ?>
<?php endif; ?>
