<p><p><?= $this->transEsc('logininfo.multi.text.2') ?> <a href="<?= $this->url('feedback-home') ?>"><?= $this->transEsc('contact_form') ?></a></p>
<div class="form-group hidden">
  <label class="col-sm-3 control-label" for="login_target"><?=$this->transEsc('login_target')?>:</label>
    <?$currentTarget = $this->request->get('target'); if (!$currentTarget) $currentTarget = $this->auth()->getManager()->getDefaultLoginTarget();?>
    <select id="login_target" name="target" class="form-control">
    <?php foreach ($this->auth()->getManager()->getLoginTargets() as $target):?>
      <option value="<?=$this->escapeHtmlAttr($target)?>"<?=($target == $currentTarget ? ' selected="selected"' : '')?>><?=$this->transEsc("source_$target", null, $target)?></option>
    <?php endforeach ?>
    </select>
</div>
<div class="form-group">
  <label class="col-sm-3 control-label" for="login_username"><?=$this->transEsc('UserID')?>:</label>
    <input id="login_username" type="text" name="username" value="<?=$this->escapeHtmlAttr($this->request->get('username'))?>" class="form-control"/>
</div>
<div class="form-group">
  <label class="col-sm-3 control-label" for="login_password"><?=$this->transEsc('Password')?>:</label>
    <input id="login_password" type="password" name="password" class="form-control"/>
</div>
