<div class="home-content-box">
    <h2 class="lead">swisscovery - Nouvelle interface de recherche</h2>
    <p>
        Dès le 7 décembre 2020, jusbib sera remplacé par le catalogue <a href="https://swisscovery.slsp.ch/" target="_blank">swisscovery</a> du nouveau réseau de bibliothèques suisse SLSP (Swiss Library Service Platform). swisscovery rend visible les collections scientifiques de plus de 475 institutions dans une seule et même interface de découverte.</p>
    <p>De plus amples informations sont disponibles sur les sites web de <a href="https://slsp.ch/fr"  target="_blank">SLSP</a> et de l’<a href="http://lawlibraries.ch"  target="_blank">ABJS</a>.</p>
</div>
