<div class="row">
    <div class="col-sm-4">
        <div class="row">
            <span class=""><?= $this->getVersion(); ?> on <?= $_SERVER['SERVER_ADDR'] ?></span>
        </div>
    </div>
    <div class="col-sm-4 powered-by">
        <div class="row">
            <a target="_blank" href="https://www.urz.unibas.ch" title="IT-Services der Universität Basel">
                <img alt="<?= $this->transEsc('powered_by') ?>" src="<?= $this->basePath('themes/sbvfrd/images/powered_by_universitaet_basel.svg') ?>">
            </a>
        </div>
    </div>
</div>

<button id="sidebar-offcanvas-trigger" class="hidden">
    <i class="fa fa-caret-left"></i>
</button>