<? if ($this->esperson()->hasAbstract()): ?>
    <? $abstractInfo = $this->esperson()->getAbstractInfo(30, false); ?>
    <div class="row">
        <div class="col-sm-2"><?= $abstractInfo->label ?></div>
        <div class="col-sm-10">
            <span class="abstract-text"><?= $abstractInfo->text ?></span>
            <? if ($abstractInfo->truncated): ?>
                <span class="ellipsis"></span>
                <span class="abstract-overflow"><?= $abstractInfo->overflow ?></span>
                <?= $this->esperson()->getDetailPageLink('<a class="ref external more" href="%s">%s</a>', 'common.more') ?>
            <? endif; ?>
        </div>
    </div>
<? endif; ?>
