<div class="home-content-box">
    <h2 class="lead">Mittels einer Einschreibung zu Milliarden</h2>
    <p>Damit Sie weiterhin Ihre Bibliothek (und noch viele weitere) nutzen können, ist eine einmalige Registrierung auf der Bibliotheksplatform SLSP notwendig. Auch für Universitätsangehörige- und studierende ist die Registrierung zwingend.        
    </p>

    <a href="http://swissbib-baselbern.blogspot.ch/search/label/Tipp" target="_blank" class="btn btn-link">Mehr Informationen im Blog</a>
</div>
