<div class="home-content-box">
    <h2 class="lead">Coronavirus</h2>
    <p>Aufgrund der Massnahmen der politischen Behörden sind zur Zeit diverse Bibliotheken nicht oder nur eingeschränkt zugänglich. <br/> Bitte informieren Sie sich auf der Website der Bibliothek über den aktuellen Stand.</p>
    <a href="https://ub.unibas.ch/de/aktuell-terminkalender/news-details/news/nutzung-der-universitaeren-bibliotheken-ab-dienstag-17-maerz-2020/" target="_blank" class="btn btn-link">Informationen der Universität Basel</a>
    <a href="https://www.unibe.ch/universitaet/dienstleistungen/universitaetsbibliothek/ub/corona/index_ger.html" target="_blank" class="btn btn-link">Informationen der Universität Bern</a>
</div>
