<div class="home-content-box">
  <h2 class="lead">How to get started?</h2>
  <p>Introducing swissbib Basel Bern</p>
  <p><a href="https://tube.switch.ch/videos/d8d59fc8" target="_blank" class="btn btn-link"><i class="fa fa-video-camera"></i> How to search?</a></p>
  <p><a href="https://tube.switch.ch/videos/d2f4ff5e" target="_blank" class="btn btn-link"><i class="fa fa-video-camera"></i> How to order?</a></p>
  <p><a href="https://tube.switch.ch/videos/ea02c388" target="_blank" class="btn btn-link"><i class="fa fa-video-camera"></i> Finding and downloading e-books</a></p>
  <p><a href="https://tube.switch.ch/videos/0542438f" target="_blank" class="btn btn-link"><i class="fa fa-video-camera"></i> How to use Articles & more?</a></p>
</div>