<div class="home-content-box">
    <h2 class="lead">swisscovery - neuer Sucheinstieg</h2>
    <p>Ab dem 7. Dezember 2020 wurde der Katalog des IDS Basel Bern durch <a href="https://swisscovery.slsp.ch/">swisscovery</a>, das neue Suchportal für wissenschaftliche Bibliotheksbestände in der Schweiz abgelöst.</p>
    <p>Die Daten in swissbib Basel Bern sind nicht mehr abrufbar, das Benutzerkonto hingegen ist bis zum 31. März 2021 einsehbar.</p>
    <p>Weiterführende Infos sind auf den Websites der <a href="https://ub.unibas.ch/de/swisscovery/" target="_blank">UB Basel</a> und <a href="https://www.unibe.ch/universitaet/dienstleistungen/universitaetsbibliothek/recherche/rechercheplattform/index_ger.html" target="_blank">UB Bern</a> einsehbar.</p>

</div>