<div class="home-content-box">
    <h2 class="lead">E-Books ausleihen? Das ist möglich, zum Beispiel bei ProQuest Ebook Central</h2>
    <p>Die Angebote von ProQuest Ebook Central werfen immer wieder Fragen auf. Deshalb widmen wir diesem Produkt einen Blogbeitrag.</p>

    <a href="http://swissbib-baselbern.blogspot.ch/search/label/Tipp" target="_blank" class="btn btn-link">Mehr Informationen im Blog</a>
</div>
