<div class="home-content-box">
  <h2 class="lead">Maintenance Work between Friday, 24.8., 12:00 and Sunday, 26.8.</h2>
  <img class="img-responsive" src="<?= $this->basePath('themes/sbvfrdmulti/images/underconstruction.jpg') ?>" width="200">
  <br/>
  <p>Because of maintenance work, your account and loan functionalities are not available between Friday, 24.8, 12:00 and until probably Monday at noon, 27.8.. All search functionalities are available. We apologize for any inconveniences.</p>
</div>