<div class="home-content-box">
    <h2 class="lead">About swissbib Basel Bern</h2>

    <p>
        swissbib Basel Bern is the collective catalog of the academic libraries in Basel and Berne, including the Swiss national library.
    </p>
    <a href="http://swissbib-baselbern.blogspot.ch/search/label/Tipp" target="_blank" class="btn btn-link">Aktuell im Blog: Alles zum Thema Gebühren</a>
    <a href="<?= $this->url('help-page', ['topic' => 'about']); ?>" class="btn btn-link">More Info</a><br/>
    <a href="<?= $this->url('help-page', ['topic' => 'faq']); ?>" class="btn btn-link"><?= $this->transEsc('helppage') ?></a>
</div>