    <?php if ($this->swissLibraryPersonResidence): ?>
        <?php if ($this->swissLibraryPersonResidence === 'CH'): ?>
            <?php if (!$this->hasVerifiedHomePostalAddress): ?>
                <?= $this->context($this)->renderInContext("nationallicences/fragments/verify_home_postal_address.phtml", []) ?>
            <?php else:; ?>
                <?= $this->context($this)->renderInContext("nationallicences/fragments/verified_address_in_switzerland.phtml", []) ?>
            <?php endif; ?>
        <?php else:; ?>
            <!-- User have a foreign adress -->
            <p>
                <span class="text-aligned-icon icon-danger"><i class="fa fa-times"></i></span>
                <?= $this->transEsc('snl.thisServiceIsOnlyForSwissResidents') ?>
            </p>
        <?php endif; ?>
    <?php else:; ?>
        <?php if ($this->homePostalAddress): ?>
            <?php if ($this->isHomePostalAddressInSwitzerland): ?>
                <?php if (!$this->hasVerifiedHomePostalAddress): ?>
                    <?= $this->context($this)->renderInContext("nationallicences/fragments/verify_home_postal_address.phtml", []) ?>
                <?php else:; ?>
                    <?= $this->context($this)->renderInContext("nationallicences/fragments/verified_address_in_switzerland.phtml", []) ?>
                <?php endif; ?>
            <?php else:; ?>
                <!-- User have a foreign adress -->
                <p>
                    <span class="text-aligned-icon icon-danger"><i class="fa fa-times"></i></span>
                    <?= $this->transEsc('snl.thisServiceIsOnlyForSwissResidents') ?>
                </p>
            <?php endif; ?>
        <?php else:; ?>
            <!-- User have to fill the homePostalAddress in the SWITCH edu-ID account -->
            <?= $this->context($this)->renderInContext("nationallicences/fragments/verify_home_postal_address.phtml", []) ?>
        <?php endif; ?>
    <?php endif; ?>



