<div class="home-content-box">
    <h2 class="lead">swisscovery - new discovery</h2>
    <p>
        As of 7 December 2020, jusbib will be replaced by the catalogue <a href="https://swisscovery.slsp.ch/" target="_blank">swisscovery</a> as a result of the new Swiss library network system SLSP (Swiss Library Service Platform). swisscovery makes the collections of more than 475 institutions searchable in one discovery.</p>
    <p>Further information can be found on the websites of <a href="https://slsp.ch/en"  target="_blank">SLSP</a> and <a href="http://lawlibraries.ch"  target="_blank">VJBS</a>.
    </p>
</div>