<div class="home-content-box">
  <h2 class="lead">swisscovery - neuer Sucheinstieg</h2>
    <p>Ab dem 7. Dezember wird swissbib Basel Bern durch swisscovery abgelöst.</p>
    <p>swisscovery macht die wissenschaftlichen Bestände von mehr als 475 Institutionen in einem Discovery sichtbar dank dem neuen Zusammenschluss zu SLSP (Swiss Library Service Plattform). Weiterführende Infos sind auf den Websites der <a href="https://ub.unibas.ch/de/swisscovery/" target="_blank">UB Basel</a> und <a href="https://www.unibe.ch/universitaet/dienstleistungen/universitaetsbibliothek/recherche/kataloge/neuer_katalog_und_registrierung/index_ger.html" target="_blank">UB Bern</a> einsehbar.</p>
    <p>Einige Institutionen, welche bei swissbib Basel Bern teilnehmen, werden nicht zu SLSP wechseln. Detaillierte Informationen finden Sie auf der Website der jeweiligen Institution.</p>
</div>