<div class="home-content-box">
    <h2 class="lead">Was finde ich eigentlich in swissbib Basel Bern?</h2>
    <p>Das Rechercheportal swissbib Basel Bern verzeichnet Milliarden (!) von gedruckten und elektronischen Dokumenten aus über 200 wissenschaftlichen Bibliotheken im Raum Basel und Bern.</p>

    <a href="<?= $this->redirectProtocolWrapper()->getWrappedURL('http://swissbib-baselbern.blogspot.ch/search/label/Tipp') ?>" target="_blank" class="btn btn-link">Mehr Informationen im Blog</a>
</div>