<div class="home-content-box">
    <h2 class="lead">SLSP: eine Platform, viele Möglichkeiten</h2>
    <p>Die Abkürzung SLSP steht für Swiss Library Service Platform. SLSP ist der Zusammenschluss von beinahe 500 wissenschaftlichen Bibliotheken aus allen drei Landesteilen der Schweiz.
    </p>

    <a href="http://swissbib-baselbern.blogspot.ch/search/label/Tipp" target="_blank" class="btn btn-link">Mehr Informationen im Blog</a>
</div>
