<div class="home-content-box">
  <h2 class="lead">Wartungsarbeiten Freitag, 24.8., ab 12:00 bis Sonntag, 26.8.</h2>
    <img class="img-responsive" src="<?= $this->basePath('themes/sbvfrdmulti/images/underconstruction.jpg') ?>" width="200">
    <br/>
    <p>Wegen Wartungsarbeiten stehen Ihre Konto- und Ausleihfunktionen vom Freitag, 24.8., ab 12:00 bis voraussichtlich Montag Mittag, 27.8. nicht zur Verfügung. Die Suche ist davon nicht betroffen. Wir bitten um Verständnis für die kurze Unterbrechung.</p>
</div>