<div class="home-content-box">
    <h2 class="lead">Über swissbib Basel Bern</h2>
    <p>swissbib Basel Bern ist der gemeinsame Katalog der Hochschulbibliotheken in Basel und Bern und der Schweizerischen Nationalbibliothek.</p>
    <a href="http://swissbib-baselbern.blogspot.ch/search/label/Tipp" target="_blank" class="btn btn-link">Aktuell im Blog: Effizient recherchieren - lassen Sie es sich kurz erklären </a>
    <a href="<?= $this->url('help-page', ['topic' => 'about']); ?>" class="btn btn-link">Mehr Informationen</a><br/>
    <a href="<?= $this->url('help-page', ['topic' => 'faq']); ?>" class="btn btn-link"><?= $this->transEsc('helppage') ?></a>
</div>
