<div class="home-content-box">
    <h2 class="lead">Wanderkarten finden – mittels Kartennummer</h2>
    <p>Medien finden in swissbib Basel Bern könnte auch einfacher gehen? Besuchen Sie eine Weiterbildung in einer unserer Bibliotheken. Unsere Informationsprofis verraten Ihnen gerne die nötigen Tipps und Tricks.</p>

    <a href="<?= $this->redirectProtocolWrapper()->getWrappedURL('http://swissbib-baselbern.blogspot.ch/search/label/Tipp') ?>" target="_blank" class="btn btn-link">Mehr Informationen im Blog</a>
</div>
