<div class="home-content-box">
  <h2 class="lead">Wie anfangen?</h2>
  <p>swissbib Basel Bern stellt sich vor</p>
  <p><a href="https://tube.switch.ch/videos/d8d59fc8" target="_blank" class="btn btn-link"><i class="fa fa-video-camera"></i> Wie suchen?</a></p>
  <p><a href="https://tube.switch.ch/videos/d2f4ff5e" target="_blank" class="btn btn-link"><i class="fa fa-video-camera"></i> Wie bestellen?</a></p>
  <p><a href="https://tube.switch.ch/videos/ea02c388" target="_blank" class="btn btn-link"><i class="fa fa-video-camera"></i> E-Books finden und herunterladen</a></p>
  <p><a href="https://tube.switch.ch/videos/0542438f" target="_blank" class="btn btn-link"><i class="fa fa-video-camera"></i> Artikel & mehr - wozu und wie weiter?</a></p>
</div>