<h3>leaflet</h3>

<?php
$this->headScript()->appendFile('vendor/leaflet/leaflet.js');
$this->headScript()->appendFile('vendor/leaflet/leaflet.latlng-graticule.js');
$this->headScript()->appendFile('vendor/leaflet/leaflet.markercluster.js');
$this->headLink()->appendStylesheet('vendor/leaflet/leaflet.css');
$this->headLink()->appendStylesheet('vendor/leaflet/MarkerCluster.css');
$this->headLink()->appendStylesheet('vendor/leaflet/MarkerCluster.Default.css');
$this->jsTranslations()->addStrings(
    ['Coordinates' => 'Coordinates', 'no_description' => 'no_description']
);
?>

<h4>circle marker</h4>
<div id="mapid" style="width: 800px; height: 600px;">
</div>

<h4>normal marker</h4>
<div id="mapid-2" style="width: 800px; height: 600px;">
</div>

<h4>cluster marker</h4>
<div id="mapid-3" style="width: 800px; height: 600px;">
</div>
<?= $this->inlineScript()->appendFile('map_fr.js'); ?>
<?= $this->inlineScript()->appendFile('libraries_map.js'); ?>
