<!-- <?php

use SwissCollections\Formatter\FieldFormatter\Inline;
use SwissCollections\Formatter\FieldFormatterData;
use SwissCollections\Formatter\FieldGroupFormatter;
use SwissCollections\RecordDriver\FieldRenderContext;
use SwissCollections\RenderConfig\FormatterConfig;

/** @var FieldFormatterData[] $fieldDataList */
/** @var string $fieldName */
/** @var Inline $formatter */
/** @var FieldRenderContext $context */
/** @var FormatterConfig $formatterConfig */
?> -->
<div class='field-value field-value-compound field-value-<?php echo $fieldName; ?>'>
    <?php foreach ($fieldDataList as $index => $fd) { ?>
        <?php $separator = $formatter->getSeparator($fd); ?>
        <?php if ($index > 0) {
            echo $separator;
        } ?>
        <span class='field-entry field-entry-<?php
        echo FieldGroupFormatter::labelKeyAsCssClass(
                $fd->renderConfig->labelKey
            ) . "-" . $fd->renderConfig->getMarcSubfieldName(); ?>'>
            <?php $formatter->outputValue($fd, $context); ?>
        </span>
    <?php } ?>
</div>
