<?php

namespace SwissCollections\templates\RecordDriver\SolrMarc\FieldFormatter;

use SwissCollections\Formatter\FieldFormatter;
use SwissCollections\Formatter\FieldFormatterData;
use SwissCollections\RecordDriver\FieldRenderContext;

class Line extends FieldFormatter {

    public function getName(): String {
        return "line";
    }

    /**
     * @param String $fieldName
     * @param FieldFormatterData[] $fieldDataList
     * @param FieldRenderContext $context ;
     */
    public function render($fieldName, $fieldDataList, $context): void {
        foreach ($fieldDataList as $fd) {
            echo "\t\t<div class='field-value field-value-" . $fieldName . "'>";
            // echo "\n\t\t\t<!-- marcInfo=" . $fd->renderConfig . " -->\n";
            echo "<span class='field-entry field-entry-" . $fd->renderConfig->labelKey . "'>";
            $this->outputValue($fd);
            echo "</span>\n";
            echo "\n\t\t</div>\n";
        }
    }
}