<!-- <?php

use SwissCollections\Formatter\FieldFormatter\Line;
use SwissCollections\Formatter\FieldFormatterData;
use SwissCollections\Formatter\FieldGroupFormatter;
use SwissCollections\RecordDriver\FieldRenderContext;
use SwissCollections\RenderConfig\FormatterConfig;

/** @var FieldFormatterData[] $fieldDataList */
/** @var string $fieldName */
/** @var Line $formatter */
/** @var FieldRenderContext $context */
/** @var FormatterConfig $formatterConfig */
?> -->
<?php foreach ($fieldDataList as $fd) { ?>
    <div class='field-value field-value-<?php echo $fieldName; ?>'>
        <span class='field-entry field-entry-"<?php
        echo FieldGroupFormatter::labelKeyAsCssClass(
                $fd->renderConfig->labelKey
            ) . "-" . $fd->renderConfig->getMarcSubfieldName(); ?>'>
            <?php $formatter->outputValue($fd, $context); ?>
        </span>
    </div>
<?php } ?>
