$(document).ready(function() {
  <?php if (isset($this->searchDetails) && is_object($this->searchDetails)): ?>
    <?php foreach ($this->searchDetails->getQueries() as $searchGroup): ?>
      <?php $i = 0; foreach ($searchGroup->getQueries() as $search): ?>
        <?php if (++$i == 1): ?>
          var new_group = swissbib.AdvancedSearch.addGroup('<?=addslashes($search->getString())?>', '<?=addslashes($search->getHandler())?>', '<?=$searchGroup->isNegated() ? 'NOT' : $searchGroup->getOperator()?>');
        <?php else: ?>
          swissbib.AdvancedSearch.addField(new_group, '<?=addslashes($search->getString())?>', '<?=addslashes($search->getHandler())?>');
        <?php endif; ?>
      <?php endforeach; ?>
    <?php endforeach; ?>
  <?php else: ?>
    swissbib.AdvancedSearch.addNewGroup();
  <?php endif; ?>
});
