<?php
$entry = $classification['entry'];
$hasChildren = count($classification['children']) > 0;
?>
<ul>
  <li data-jstree='{"icon":"fa fa-file"}' data-openChildren='<?= $hasChildren ? 'yes' : 'no' ?>'>
    <a>
      <ins>&nbsp;</ins>
      <input type="hidden" value="<?= $facetKey ?>:&quot;<?= $entry['queryValue'] ?>&quot;">
      <?= $entry['value'] ?> <?= $this->laminasTranslate($entry['value'], 'drsys') ?>
      <?php if ($entry['nestingLevel'] !== 0 || !$hasChildren): ?>
        (<?= $entry['count'] ?> <?= $this->transEsc('Showing') ?>)
      <?php endif; ?>
    </a>
    <?php if ($hasChildren): ?>
      <?php if ($entry['nestingLevel'] === 0): ?>
        <ul>
            <li data-jstree='{"icon":"fa fa-file"}' data-openChildren='no'>
                <a>
                    <ins>&nbsp;</ins>
                    <input type="hidden" value="<?= $facetKey ?>:&quot;<?= $entry['queryValue'] ?>&quot;">
                    <?= $entry['value'] ?> <?= $this->laminasTranslate($entry['value'], 'drsys') ?>
                    (<?= $entry['count'] ?> <?= $this->transEsc('Showing') ?>)
                </a>
            </li>
        </ul>
      <?php endif; ?>
      <?php foreach ($classification['children'] as $child): ?>
            <?= $this->render(
                'search/advanced/classificationTreeItem',
                [
                    'classification' => $child,
                    'facetKey' => $facetKey
                ]);
            ?>
      <?php endforeach; ?>
    <?php endif; ?>
  </li>
</ul>