<div id="tabbed-tree" class="tabs" role="tabpanel">
  <ul class="recordTabs nav nav-tabs" role="tablist">
    <?php $i = 0; ?>
    <?php foreach ($classificationTrees as $facetKey => $tree): ?>
      <li <?= $i++ === 0 ? 'class="active"' : '' ?> >
        <a href="#tab-tree-<?= $facetKey ?>"><?= $this->laminasTranslate($facetKey, 'drsys') ?></a>
      </li>
    <?php endforeach ?>
  </ul>
  <div class="tab-content">
  <?php $i = 0; ?>
  <?php foreach ($classificationTrees as $facetKey => $tree): ?>
    <div id="tab-tree-<?= $facetKey ?>" <?= $i++ === 0 ? 'class="active"' : '' ?> >
      <?php echo $this->render(
        'search/advanced/classificationTree',
        [
          'classificationTree' => $tree,
          'facetKey' => $facetKey
        ]
      );
      ?>
      <div class="clearfix"></div>
    </div>
  <?php endforeach ?>
  </div>
</div>