<?php
$favoriteLanguages = ['ger', 'eng', 'fre', 'ita'];
?>

<?php if (!empty($this->facetList) || !empty($this->checkboxFacets)): ?>
<div class="row">
  <fieldset class="col-sm-12">
    <legend><?=$this->transEsc('Limit To')?></legend>
    <?php if (!empty($this->checkboxFacets)): ?>
      <?=$this->render('search/advanced/checkbox-filters.phtml')?>
    <?php endif; ?>
    <div class="row">
      <div class="col-sm-6">
        <?php foreach ($this->facetList as $field => $list): ?>
            <br/>
            <label for="limit_<?=$this->escapeHtmlAttr(str_replace(' ', '', $field))?>"><?=$this->transEsc($list['label'])?></label>
            <br/>
            <select class="form-control chosen-select" data-placeholder="<?=$this->transEsc('Select' . $list['label'] . 'Placeholder')?>" id="limit_<?=$this->escapeHtmlAttr(str_replace(' ', '', $field))?>" name="filter[]" multiple="multiple" size="10">
              <?php
                // Sort the current facet list alphabetically; we'll use this data
                // along with the foreach below to display facet options in the
                // correct order.
                $sorted = [];
                foreach ($list['list'] as $i => $value) {
                  if (!empty($value['displayText'])) {
                    $sorted[$i] = $value['displayText'];
                  }
                }
                natcasesort($sorted);
              ?>

              <?php if (strtolower($field) === "language") : ?>
                <?php foreach ($sorted as $index => $display): ?>
                  <?php $value = $list['list'][$index]; ?>
                  <?php if (in_array($value['value'], $favoriteLanguages)) : ?>
                    <option value="<?=$this->escapeHtmlAttr(($value['operator'] == 'OR' ? '~' : '') . $field . ':"' . $value['value'] . '"')?>"><?=$this->escapeHtml($display)?></option>
                  <?php endif; ?>
                <?php endforeach; ?>

                <optgroup label="<?= $this->transEsc('all_languages') ?>">
              <?php endif; ?>

              <?php if (strtolower($field) === "format_str_mv") : ?>

                <option value='~format_str_mv:"BK01*"' title="article"><?= $this->laminasTranslate('BK01*', 'formats') ?></option>
                <option value='~format_str_mv:"BK02*"' title="book"><?= $this->laminasTranslate('BK02*', 'formats') ?></option>
                <option value='~format_str_mv:"CR03*"' title="continuing"><?= $this->laminasTranslate('CR03*', 'formats') ?></option>
                <option value='~format_str_mv:"CL0*"' title="collection"><?= $this->laminasTranslate('CL0*', 'formats') ?></option>
                <option value='~format_str_mv:"MU01*"' title="sheet_music"><?= $this->laminasTranslate('MU01*', 'formats') ?></option>
                <option value='~format_str_mv:"MU03*"' title="sound"><?= $this->laminasTranslate('MU03*', 'formats') ?></option>
                <option value='~format_str_mv:"MU04*"' title="music"><?= $this->laminasTranslate('MU04*', 'formats') ?></option>
                <option value='~format_str_mv:"MP0*"' title="map"><?= $this->laminasTranslate('MP0*', 'formats') ?></option>
                <option value='~format_str_mv:"VM01*"' title="film"><?= $this->laminasTranslate('VM01*', 'formats') ?></option>
                <option value='~format_str_mv:"VM02*"' title="picture"><?= $this->laminasTranslate('VM02*', 'formats') ?></option>
                <option value='~format_str_mv:"VM03*"' title="mx_game"><?= $this->laminasTranslate('VM03*', 'formats') ?></option>
                <option value='~format_str_mv:"VM04*"' title="object"><?= $this->laminasTranslate('VM04*', 'formats') ?></option>
                <option value='~format_str_mv:"CF0*"' title="software"><?= $this->laminasTranslate('CF0*', 'formats') ?></option>

                <optgroup label="<?= $this->laminasTranslate('all_formats', 'formats') ?>">
              <?php endif; ?>

              <?php foreach ($sorted as $index => $display): ?>
                <?php $value = $list['list'][$index]; ?>
                <option value="<?=$this->escapeHtmlAttr(($value['operator'] == 'OR' ? '~' : '') . $field . ':"' . $value['value'] . '"')?>"<?=(isset($value['selected']) && $value['selected'])?' selected="selected"':''?>><?=$this->escapeHtml($display)?></option>
              <?php endforeach; ?>

            </select>
        <?php endforeach; ?>
      </div>
      <?php endif; ?>
        <div class="col-sm-6">
        <?php if (isset($this->illustratedLimit)): ?>
          <div class="row">
              <fieldset>
                <legend><?=$this->transEsc("Illustrated")?>:</legend>
                  <?php foreach ($this->illustratedLimit as $current): ?>
                      <input class="form-control" id="illustrated_<?=$this->escapeHtmlAttr($current['value'])?>" type="radio" name="illustration" value="<?=$this->escapeHtmlAttr($current['value'])?>"<?=$current['selected']?' checked="checked"':''?>/>
                      <label for="illustrated_<?=$this->escapeHtmlAttr($current['value'])?>"><?=$this->transEsc($current['text'])?></label><br/>
                  <?php endforeach; ?>
              </fieldset>
          </div>
        <?php endif; ?>
        <?=$this->render('search/advanced/ranges.phtml')?>
        <?=$this->render('search/advanced/limit.phtml')?>
        </div>
      </div>
    </fieldset>
</div>
