<?php if ($this->esorganisation()->hasAbstract()): ?>
    <?php $abstractInfo = $this->esorganisation()->getAbstractInfo(true, 30); ?>
    <li class="entry section-start">
        <span class="entry-label"><?= $abstractInfo->label ?></span>
        <span class="entry-value"><?= $abstractInfo->text ?></span>
        <?php if ($abstractInfo->truncated): ?>
            <?= $this->esorganisation()->getDetailPageLink('<a class="ref external more" data-lightbox-ignore href="%s">%s</a>', 'common.more') ?>
        <?php endif; ?>
    </li>
<?php endif; ?>
