<?php
/** @var \Swissbib\RecordDriver\SolrMarc $record */
$record = $this->driver;
/** @var Swissbib\View\Helper\Record $viewRecord */
$viewRecord = $this->record($record);

$shortTitle = $record->getShortTitle();
$titleStatement = $record->getTitleStatement(true);
$responsible = $viewRecord->getResponsible($titleStatement, $record);

// Set page title.
$this->headTitle($this->translate('request_place_text') . ': ' . $this->driver->getBreadcrumb());

// Set up breadcrumbs:
$this->layout()->breadcrumbs = '<li>' . $this->searchMemory()->getLastSearchLink($this->transEsc('Search'), '', '</li> ')
    . '<li>' . $this->recordLink()->getBreadcrumb($this->driver) . '</li> '
    . '<li class="active">' . $this->transEsc('request_place_text') . '</li>';

$today = strtotime('now');

$unsetPickup[] = 'POPA';

// unterdrückt Pickup locations während Schliesszeiten
if ($today > strtotime('2020-06-29') && $today < strtotime('2020-08-28')):
    $unsetPickup[] = 'LUMHS';
endif;

?>
<p class="lead"><?=$this->transEsc('request_place_text')?></p>
<p><?=$this->transEsc('request_title') ?>: <a href="<?=$this->recordLink()->getUrl($this->driver) ?>" target="_blank" data-lightbox-ignore> <?= $this->escapeHtml($shortTitle) ?> <?php if (!empty($responsible)): ?> <?=' / ' . $this->escapeHtml($responsible)?><?php endif; ?></a><p>
<p><?=$this->transEsc('hold_text4') ?> <a href="<?= $this->url('help-page', ['topic' => 'delivery']); ?>" target="_blank" data-lightbox-ignore><?=$this->transEsc('hold_text5')?></a>.</p><br/>
<?php if ($this->helpText): ?>
    <p class="helptext"><?=$this->helpText?></p>
<?php endif; ?>

<?=$this->flashmessages()?>
<div class="hold-form">
    <form action="" class="form-horizontal" method="post" name="placeHold">
        <?php if (in_array("pickUpLocation", $this->extraHoldFields)): ?>
            <?php
            if (isset($this->gatheredDetails['pickUpLocation']) && $this->gatheredDetails['pickUpLocation'] !== "") {
                $selected = $this->gatheredDetails['pickUpLocation'];
            } elseif (isset($this->homeLibrary) && $this->homeLibrary !== "") {
                $selected = $this->homeLibrary;
            } else {
                $selected = $this->defaultPickup;
            }
            ?>
            <?php if ($this->requestGroupNeeded): ?>
                <div class="form-group">
                    <label id="pickUpLocationLabel" class="col-sm-3 control-label"><i></i> <?=$this->transEsc("pick_up_location")?>:
                        <?php if (in_array("requestGroup", $this->extraHoldFields)): ?>
                            <noscript> (<?=$this->transEsc("Please enable JavaScript.")?>)</noscript>
                        <?php endif; ?>
                    </label>
                    <div class="col-sm-9">
                        <select id="pickUpLocation" name="gatheredDetails[pickUpLocation]" data-default="<?=$this->escapeHtmlAttr($selected)?>" class="form-control">
                            <?php if ($selected === false): ?>
                                <option value="" selected="selected">
                                    <?=$this->transEsc('select_pickup_location')?>
                                </option>
                            <?php endif; ?>
                        </select>
                    </div>
                </div>
            <?php elseif (count($this->pickup) >= 1): ?>
                <?php
                $institutionIsPresent = true;
                $institutionOfItem = $_GET['institution'];
                foreach ($this->pickup as $lib):
                    if ($lib['locationID'] === "POPA")
                    {
                        $institutionIsPresent = false;
                        break;
                    }
                endforeach;
                ?>
                <div class="form-group">
                    <label class="col-sm-3 control-label"><?=$this->transEsc("pick_up_location")?>:</label>
                    <div class="col-sm-9">
                        <select id="pickUpLocation" name="gatheredDetails[pickUpLocation]" class="form-control" onchange="handleChange();">
                            <option value="" selected="selected">[<?=$this->transEsc('select pickup location')?>:]</option>
                            <?php if (!$institutionIsPresent): ?><option value="DUMMY"><?= $this->laminasTranslate($institutionOfItem, 'institution') ?></option><?php endif; ?>
                            <?php foreach ($this->pickup as $lib): ?>
                                <?php if(in_array($lib['locationID'], $unsetPickup)): ?>
                                    <?php unset($lib); ?>
                                <?php else: ?>
                                    <option value="<?=$this->escapeHtml($lib['locationID'])?>">
                                        <?=$this->transEsc($lib['locationDisplay'])?>
                                    </option>
                                <?php endif; ?>
                            <?php endforeach; ?>
                        </select>
                        <br/>
                    </div>
                </div>
            <?php else: ?>
                <input type="hidden" name="gatheredDetails[pickUpLocation]" value="<?=$this->escapeHtmlAttr($this->defaultPickup)?>" />
            <?php endif; ?>
        <?php endif; ?>

        <?php if (in_array("comments", $this->extraHoldFields)): ?>
            <div class="form-group">
                <label class="col-sm-3 control-label"><?=$this->transEsc("hold_text2")?>:</label>
                <div class="col-sm-9">
                    <textarea rows="1" cols="20" name="gatheredDetails[comment]" class="form-control"><?=isset($this->gatheredDetails['comment']) ? $this->escapeHtml($this->gatheredDetails['comment']) : ''?></textarea>
                </div>
            </div>
        <?php endif; ?>

        <?php if (in_array("requiredByDate", $this->extraHoldFields)): ?>
            <?php // hide box ?>
            <div class="form-group hidden">
                <label class="col-sm-3 control-label"><?=$this->transEsc("hold_required_by")?>:</label>
                <div class="col-sm-9">
                    <input id="requiredByDate" type="text" name="gatheredDetails[requiredBy]" value="<?=(isset($this->gatheredDetails['requiredBy']) && !empty($this->gatheredDetails['requiredBy'])) ? $this->escapeHtmlAttr($this->gatheredDetails['requiredBy']) : $this->escapeHtmlAttr($this->defaultRequiredDate)?>" size="8" class="form-control"/>
                    (<?=$this->dateTime()->getDisplayDateFormat()?>)
                </div>
            </div>
        <?php endif; ?>

        <?php $showRequestGroups = in_array("requestGroup", $this->extraHoldFields)
            && (empty($this->gatheredDetails['level'])
                || $this->gatheredDetails['level'] != 'copy');
        ?>
        <?php if ($this->requestGroupNeeded): ?>
            <div class="form-group">
                <?php
                if (isset($this->gatheredDetails['requestGroupId']) && $this->gatheredDetails['requestGroupId'] !== "") {
                    $selected = $this->gatheredDetails['requestGroupId'];
                } else {
                    $selected = $this->defaultRequestGroup;
                }
                ?>
                <label class="col-sm-3 control-label"><?=$this->transEsc("hold_request_group")?>:</label>
                <div class="col-sm-9">
                    <select id="requestGroupId" name="gatheredDetails[requestGroupId]" class="form-control">
                        <?php if ($selected === false): ?>
                            <option value="" selected="selected">
                                <?=$this->transEsc('select_request_group')?>
                            </option>
                        <?php endif; ?>
                        <?php foreach ($this->requestGroups as $group): ?>
                            <option value="<?=$this->escapeHtmlAttr($group['id'])?>"<?=($selected == $group['id']) ? ' selected="selected"' : ''?>>
                                <?=$this->escapeHtml($group['name'])?>
                            </option>
                        <?php endforeach; ?>
                    </select>
                </div>
            </div>
        <?php endif; ?>

        <div class="form-group">
            <div class="col-sm-9 col-sm-offset-3">
                <input class="btn btn-primary" type="submit" name="placeHold" value="<?=$this->transEsc('request_submit_text')?>"/>
            </div>
        </div>
    </form>
</div>


<?php
// Set up hold script; we do this inline instead of in the header for lightbox compatibility:
$this->inlineScript()->appendFile('hold.js');

$js = <<<JS
        if ($.isReady) {
            setUpHoldRequestForm("{$this->escapeHtml($this->driver->getUniqueId())}");
        } else {
            $(document).ready(function(){
                setUpHoldRequestForm("{$this->escapeHtml($this->driver->getUniqueId())}");
            });
        }
JS;

echo $this->inlineScript()->appendScript($js);
?>

<?php
$hold_text3 = $this->transEsc('hold_text3');
$js = <<<JS
        function handleChange() {
            dropDownBox = document.getElementById('pickUpLocation');
            selectedValue = dropDownBox.options[dropDownBox.selectedIndex].value;
            if (selectedValue == 'DUMMY')
            {
                alert("{$hold_text3}");
            }
        }
JS;

echo $this->inlineScript()->appendScript($js);
?>
