<?php
    // Set up page title:
    $this->headTitle($this->translate('Checked Out Items'));

    // Set up breadcrumbs:
    $this->layout()->breadcrumbs = '<li><a href="' . $this->url('myresearch-home') . '">' . $this->transEsc('Your Account') . '</a></li> <li class="active">' . $this->transEsc('Checked Out Items') . '</li>';
?>

<div class="<?=$this->layoutClass('mainbody')?>">
<h2><?=$this->transEsc('Your Checked Out Items')?></h2>
<?=$this->flashmessages()?>

<?php if (!empty($this->transactions)): ?>
    <div>
        <p><?= '<a href="' . $this->url('help-page', array('topic' => 'delivery')) . '">' . $this->transEsc('info returns') . '</a>'; ?></p>
    </div>
  <?php if ($this->renewForm): ?>
  <form name="renewals" action="" method="post" id="renewals">
    <div class="toolbar">
      <input type="submit" class="btn btn-default hidden-print" name="renewSelected" value="<?=$this->transEsc("renew_selected")?>" />
<!--          <input type="submit" class="btn btn-default" name="renewAll" value="--><?//=$this->transEsc('renew_all')?><!--" />-->
    </div>
  <?php endif; ?>

    <?php if ($paginator): ?>
    <div class="hidden-print search-controls clearfix row" >
    <div class="col-lg-6 col-md-7 col-sm-7">

    <?php $start = $paginator->getAbsoluteItemNumber(1);
    $end = $paginator->getAbsoluteItemNumber($paginator->getItemCountPerPage());
    $total = $paginator->getTotalItemCount();
    ?>
    <div class="hidden-sm hidden-xs">
        <?=$this->transEsc("Showing")?>
        <strong><?=$this->localizedNumber($start)?></strong> - <strong><?=$this->localizedNumber($end > $total ? $total : $end)?></strong>
        <?=$this->transEsc('of')?> <strong><?=$this->localizedNumber($total)?></strong>
    </div>
    <div class="hidden-md hidden-lg">
        <strong><?=$this->localizedNumber($total)?></strong> <?=$this->transEsc("Results")?>
    </div>
        <?=$paginator ? $this->paginationControl($paginator, 'Sliding', 'Helpers/pagination.phtml') : ''?>
    </div>
    </div>
        <?php foreach ($hiddenTransactions as $ilsDetails): ?>
            <?php if (isset($this->renewResult[$ilsDetails['item_id']])): ?>
                <?php $renewDetails = $this->renewResult[$ilsDetails['item_id']]; ?>
                <?php $prefix = $ilsDetails['title'] ?? $ilsDetails['item_id']; ?>
                <?php if (isset($renewDetails['success']) && $renewDetails['success']): ?>
                    <div class="alert alert-success"><?=$this->escapeHtml($prefix . ': ') . $this->transEsc('renew_success')?></div>
                <?php else: ?>
                    <div class="alert alert-danger"><?=$this->escapeHtml($prefix . ': ') . $this->transEsc('renew_fail')?><?// if (isset($renewDetails['sysMessage'])): ?> <?//=$this->escapeHtml($renewDetails['sysMessage'])?><?php //endif; ?></div>
                <?php endif; ?>
            <?php endif; ?>
            <?php if (isset($ilsDetails['renewable']) && $ilsDetails['renewable'] && isset($ilsDetails['renew_details'])): ?>
                <?php $safeId = preg_replace('/[^a-zA-Z0-9]/', '', $ilsDetails['renew_details']); ?>
                <input class="pull-left flip" type="hidden" name="renewAllIDS[]" value="<?=$this->escapeHtmlAttr($ilsDetails['renew_details'])?>" />
            <?php endif; ?>
        <?php endforeach; ?>
    <?php endif; ?>

    <?php foreach ($this->transactions as $resource): ?>
        <?php $ilsDetails = $resource->getExtraDetail('ils_details'); ?>
        <?php if (isset($this->renewResult[$ilsDetails['item_id']])): ?>
            <?php $renewDetails = $this->renewResult[$ilsDetails['item_id']]; ?>
            <?php $prefix = $ilsDetails['title'] ?? $ilsDetails['item_id']; ?>
            <?php if (isset($renewDetails['success']) && $renewDetails['success']): ?>
                <div class="alert alert-success"><?=$this->escapeHtml($prefix . ': ') . $this->transEsc('renew_success')?></div>
            <?php else: ?>
                <div class="alert alert-danger"><?=$this->escapeHtml($prefix . ': ') . $this->transEsc('renew_fail')?><?// if (isset($renewDetails['sysMessage'])): ?> <?//=$this->escapeHtml($renewDetails['sysMessage'])?><?php //endif; ?></div>
            <?php endif; ?>
        <?php endif; ?>
        <?php if (isset($ilsDetails['renewable']) && $ilsDetails['renewable'] && isset($ilsDetails['renew_details'])): ?>
            <?php $safeId = preg_replace('/[^a-zA-Z0-9]/', '', $ilsDetails['renew_details']); ?>
            <input class="pull-left flip" type="hidden" name="renewAllIDS[]" value="<?=$this->escapeHtmlAttr($ilsDetails['renew_details'])?>" />
        <?php endif; ?>
    <?php endforeach; ?>

    <?php
    $headers = [
        'title' => $this->transEsc('Title'),
        'library_callno' => $this->transEsc('Institution'),
        'checkedout' => $this->transEsc('Checked Out'),
        'renewals' => $this->transEsc('Renewals'),
        'action' => $this->transEsc('renew_select'),
    ];

    $flippedContent = '';
    ?>

    <br />
    <table class="table table-striped hidden-xs hidden-sm">
    <thead>
    <tr>
        <th><?=$headers['title']?></th>
        <th><?=$headers['library_callno']?></th>
        <th><?=$headers['checkedout']?></th>
        <th><?=$headers['renewals']?></th>
        <th class="hidden-print"><?= $headers['action'] ?? '' ?></th>
    </tr>
    </thead>
    <tbody>



  <?php $i = 0; foreach ($this->transactions as $resource): ?>
    <?php $ilsDetails = $resource->getExtraDetail('ils_details'); ?>
        <tr>
          <?php
          $flippedContent .= $this->render('myresearch/checkedout-flipped.phtml', [
          'ilsDetails' => $ilsDetails,
          'resource' => $resource,
          'renewForm' => $this->renewForm,
          'renewResult' => $this->renewResult,
          'headers' => $headers
          ]);
          ?>
         <td>
             <?php
             // If this is a non-missing Solr record, we should display a link:
             if (is_a($resource, 'VuFind\\RecordDriver\\SolrDefault') && !is_a($resource, 'VuFind\\RecordDriver\\Missing')) {
                 $title = $resource->getTitle();
                 $title = empty($title) ? $this->transEsc('Title not available') : $this->escapeHtml($title);
                 echo '<a href="' . $this->recordLink()->getUrl($resource) .
                     '" class="title">' . $title . '</a>';
             } elseif (isset($ilsDetails['id']) && !empty($ilsDetails['id'])){
                  // If ID is available link to the record
                 echo '<a href="' . $this->url('search-results') . "?lookfor=" . str_replace('.DSV01-', '', $ilsDetails['id']) . "&jumpto=1" .
                     '" class="title">' . $this->escapeHtml($ilsDetails['title']) . '</a>';
             } elseif (isset($ilsDetails['title']) && !empty($ilsDetails['title'])) {
                 // If the record is not available in Solr, perhaps the ILS driver sent us a title we can show...
                 echo $this->escapeHtml($ilsDetails['title']);
             } else {
                 // Last resort -- indicate that no title could be found.
                 echo $this->transEsc('Title not available');
             }
             ?>
         </td>
         <td>
             <?php if (!empty($ilsDetails['library'])): ?> <?=$this->escapeHtml($ilsDetails['library'])?><br />
             <?php endif; ?>

             <?php if (!empty($ilsDetails['callnum'])): ?> <?=$this->escapeHtml($ilsDetails['callnum'])?>
             <?php endif; ?>
         </td>
         <td>
             <?=$this->escapeHtml($ilsDetails['loandate']) ?> <?=$this->transEsc('Due')?> <?=$this->escapeHtml($ilsDetails['duedate'])?><?php if (isset($ilsDetails['dueTime'])): ?> <?=$this->escapeHtml($ilsDetails['dueTime'])?><?php endif; ?>
         </td>
         <td>
             <?php $isRenewable = $ilsDetails['renewable'];
             if ($isRenewable)
             {
                 $renewalLimit = preg_replace('/^\d+ \(out of (\d+)\).*$/', '$1', $ilsDetails['renew_info']);
                 if (is_numeric($renewalLimit))
                 {
                     $Renewals = $ilsDetails['renewals'] . ' ' . $this->transEsc('of') . ' ' . $renewalLimit;
                 }
                 else
                 {
                     $renewalInfo = preg_replace('/^\d+ \((.*)\).$/', '$1', $ilsDetails['renew_info']);
                     $Renewals = $ilsDetails['renewals'] . ' (' . $this->translate($renewalInfo) . ')';
                     //$Renewals = $ilsDetails['renew_info'];
                 }
             }
             else
             {
                 $Renewals = $this->translate('no_renewal');
             }
             ?>
             <?=$this->escapeHtml($Renewals)?>
         </td>
         <td>
             <?php if ($this->renewForm): ?>
                 <?php if (isset($ilsDetails['renewable']) && $ilsDetails['renewable'] && isset($ilsDetails['renew_details'])): ?>
                     <?php $safeId = preg_replace('/[^a-zA-Z0-9]/', '', $ilsDetails['renew_details']); ?>
                     <input class="pull-left hidden-print col-xs-1"  type="checkbox" name="renewSelectedIDS[]" value="<?=$this->escapeHtmlAttr($ilsDetails['renew_details'])?>" id="checkbox_<?=$safeId?>" />
                     <input class="pull-left" type="hidden" name="renewAllIDS[]" value="<?=$this->escapeHtmlAttr($ilsDetails['renew_details'])?>" />
                 <?php endif; ?>
             <?php endif; ?>

             <?php $showStatus = true; ?>
             <?php if (isset($this->renewResult[$ilsDetails['item_id']])): ?>
                 <?php $renewDetails = $this->renewResult[$ilsDetails['item_id']]; ?>
                 <?php if (isset($renewDetails['success']) && $renewDetails['success']): ?>
                     <?php $showStatus = false; ?>
                     <!--            --><?//=$this->transEsc('Due')?><!-- --><?//=$this->escapeHtml($renewDetails['new_date'])?><!-- --><?// if (isset($renewDetails['new_time'])): ?><!----><?//=$this->escapeHtml($renewDetails['new_time'])?><!----><?// endif; ?>
                     <br /><div class="alert alert-success"><?=$this->transEsc('renew_success')?></div>
                 <?php else: ?>
                     <!--            --><?//=$this->transEsc('Due')?><!-- --><?//=$this->escapeHtml($ilsDetails['duedate'])?><!----><?// if (isset($ilsDetails['dueTime'])): ?><!-- --><?//=$this->escapeHtml($ilsDetails['dueTime'])?><!----><?// endif; ?>
                     <br /><div class="alert alert-danger"><?=$this->transEsc('renew_fail')?><?php //if (isset($renewDetails['sysMessage'])): ?> <?//=$this->escapeHtml($renewDetails['sysMessage'])?><?php //endif; ?></div>
                 <?php endif; ?>
             <?php else: ?>
                 <!--          --><?//=$this->transEsc('Due')?><!-- --><?//=$this->escapeHtml($ilsDetails['duedate'])?><!----><?// if (isset($ilsDetails['dueTime'])): ?><!-- --><?//=$this->escapeHtml($ilsDetails['dueTime'])?><!----><?// endif; ?><!--<br />-->
                              <?php if ($showStatus): ?>
                     <?php if (isset($ilsDetails['dueStatus']) && $ilsDetails['dueStatus'] == "overdue"): ?>
                         <br /><div class="alert alert-danger"><?=$this->transEsc("renew_item_overdue")?></div>
                     <?php elseif (isset($ilsDetails['dueStatus']) && $ilsDetails['dueStatus'] == "due"): ?>
                         <br /><div class="alert alert-info"><?=$this->transEsc("renew_item_due")?></div>
                     <?php endif; ?>
                     <?php endif; ?>
                 <?php endif; ?>

         </td>


        </tr>

<?php endforeach; ?>
    </tbody>
    </table>
    <?=$flippedContent;?>
    <?php if ($this->renewForm): ?></form><?php endif; ?>

    <?php if ($paginator): ?>
        <?=$paginator ? $this->paginationControl($paginator, 'Sliding', 'Helpers/pagination.phtml') : ''?>
    <?php endif; ?>

<?php else: ?>
    <?=$this->transEsc('You do not have any items checked out')?>.
<?php endif; ?>
</div>

<div class="<?=$this->layoutClass('sidebar')?>">
    <?=$this->context($this)->renderInContext("myresearch/menu.phtml", ['active' => 'checkedout'])?>
</div>