<?php
    // Set up page title:
    $this->headTitle($this->translate('My Fines'));

    // Set up breadcrumbs:
    $this->layout()->breadcrumbs = '<li><a href="' . $this->url('myresearch-home') . '">' . $this->transEsc('Your Account') . '</a></li> <li class="active">' . $this->transEsc('Fines') . '</li>';
?>
<div class="<?=$this->layoutClass('mainbody')?>">
  <h2><?=$this->transEsc('Your Fines')?></h2>
  <?php if (empty($this->fines)): ?>
    <?=$this->transEsc('You do not have any fines')?>
  <?php else: ?>
        <?php $totalDue = 0; ?>
        <?php foreach ($this->fines as $record): ?>
            <?php if (!empty($record['balance'])): ?>
                <?$totalDue += $record['amount']; ?>
            <?php endif; ?>
        <?php endforeach; ?>
        <p><span><strong><?=$this->transEsc('Total Balance Due') ?>:</strong></span> CHF <?=isset($totalDue) ? number_format($totalDue, 2, '.', '\'') : ''?></p>

    <?php
    $headers = [
        'title' => $this->transEsc('Title'),
        'library_callno' => $this->transEsc('Institution'),
        'date' => $this->transEsc('Date'),
        'fee' => $this->transEsc('Fee'),
    ];

    $flippedContent = '';
    ?>

    <br />
    <table class="table table-striped hidden-xs hidden-sm">
        <thead>
        <tr>
            <th><?=$headers['title']?></th>
            <th><?=$headers['library_callno']?></th>
            <th><?=$headers['date']?></th>
            <th><?=$headers['fee']?></th>
        </tr>
        </thead>
        <tbody>

        <?php foreach ($this->fines as $record): ?>
        <tr>
            <?php
            $flippedContent .= $this->render('myresearch/fines-flipped.phtml', [
                'record' => $record,
                'headers' => $headers
            ]);
            ?>
            <td>
                <?php if (empty($record['title'])): ?>
                    <?=$this->transEsc('not_applicable')?>
                <?php elseif (!isset($record['id'])): ?>
                    <?=$this->escapeHtml(trim($record['title'], '/:'))?>
                <?php else: ?>
                    <a href="<?=$this->url('record', ['id' => $record['id']])?>"><?=$this->escapeHtml(trim($record['title'], '/:'))?></a>
                <?php endif; ?>
            </td>
            <td>
                <?php if (!empty($record['institution'])): ?>
                    <?=$this->escapeHtml($this->laminasTranslate($record['institution'], 'institution'))?><br />
                <?php endif; ?>

                <?php if (!empty($record['signature'])): ?>
                    <?=$this->escapeHtml($record['signature'])?>
                <?php endif; ?>
            </td>
            <td>
                <?=$this->escapeHtml($record['checkout']) ?>
            </td>
            <td>
                CHF <?=isset($record['amount']) ? number_format($record['amount'], 2, '.', '\'') : ''?> (<?=isset($record['description']) ? $this->escapeHtml($record['description']) : ''?>)
            </td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
    <?=$flippedContent;?>
  <?php endif; ?>
</div>


<div class="<?=$this->layoutClass('sidebar')?>">
  <?=$this->context($this)->renderInContext("myresearch/menu.phtml", ['active' => 'fines'])?>
</div>