<?php
    // Set up page title:
    $this->headTitle($this->translate('My Holds'));

    // Set up breadcrumbs:
    $this->layout()->breadcrumbs = '<li><a href="' . $this->url('myresearch-home') . '">' . $this->transEsc('Your Account') . '</a></li> <li class="active">' . $this->transEsc('My Holds') . '</li>';
?>

<div class="<?=$this->layoutClass('mainbody')?>">
<h2><?=$this->transEsc('Your Holds and Recalls') ?></h2>

<?=$this->flashmessages()?>

<?php if (!empty($this->recordList)): ?>
  <?php if ($this->cancelForm): ?>
    <form name="cancelForm" class="inline" action="" method="post" id="cancelHold">
      <input type="hidden" id="submitType" name="cancelSelected" value="1"/>
      <input type="hidden" id="cancelConfirm" name="confirm" value="0"/>
      <div class="btn-group">
        <input id="cancelSelected" name="cancelSelected" type="submit" value="<?=$this->transEsc("hold_cancel_selected") ?>" class="btn btn-default dropdown-toggle" data-toggle="dropdown"/>
        <ul class="dropdown-menu">
          <li class="disabled"><a><?=$this->transEsc("confirm_hold_cancel_selected_text") ?></a></li>
          <li><a href="#" onClick="$('#cancelConfirm').val(1);$('#submitType').attr('name','cancelSelected');$(this).parents('form').submit(); return false;"><?=$this->transEsc('confirm_dialog_yes') ?></a></li>
          <li><a href="#" onClick="return false;"><?=$this->transEsc('confirm_dialog_no')?></a></li>
        </ul>
      </div>
      <!--<div class="btn-group">
        <input id="cancelAll" name="cancelAll" type="submit" value="<?/*=$this->transEsc("hold_cancel_all") */?>" class="btn btn-default dropdown-toggle" data-toggle="dropdown"/>
        <ul class="dropdown-menu">
          <li class="disabled"><a><?/*=$this->transEsc("confirm_hold_cancel_all_text") */?></a></li>
          <li><a href="#" onClick="$('#cancelConfirm').val(1);$('#submitType').attr('name','cancelAll');$(this).parents('form').submit(); return false;"><?/*=$this->transEsc('confirm_dialog_yes') */?></a></li>
          <li><a href="#" onClick="return false;"><?/*=$this->transEsc('confirm_dialog_no')*/?></a></li>
        </ul>
      </div>-->
  <?php endif; ?>

    <?php
    $headers = [
        'title' => $this->transEsc('Title'),
        'library_callno' => $this->transEsc('Institution'),
        'pick_up_location' => $this->transEsc('pick_up_location'),
        'created' => $this->transEsc('Created'),
        'status' => $this->transEsc('Status'),
        'action' => $this->transEsc('cancel_select'),
    ];

    $flippedContent = '';
    ?>

    <br /><br />
    <table class="table table-striped hidden-xs hidden-sm">
    <thead>
    <tr>
        <th><?=$headers['title']?></th>
        <th><?=$headers['library_callno']?></th>
        <th><?=$headers['pick_up_location']?></th>
        <th><?=$headers['created']?></th>
        <th><?=$headers['status']?></th>
        <th class="hidden-print"><?= $headers['action'] ?? '' ?></th>
    </tr>
    </thead>
    <tbody>

  <?php foreach ($this->recordList as $resource): ?>
    <?php $ilsDetails = $resource->getExtraDetail('ils_details'); ?>
        <tr>
            <?php
            $flippedContent .= $this->render('myresearch/holds-flipped.phtml', [
                'ilsDetails' => $ilsDetails,
                'resource' => $resource,
                'cancelForm' => $this->cancelForm,
                'cancelResults' => $this->cancelResults,
                'headers' => $headers
            ]);
            ?>
            <td><?php
                // If this is a non-missing Solr record, we should display a link:
                if (is_a($resource, 'VuFind\\RecordDriver\\SolrDefault') && !is_a($resource, 'VuFind\\RecordDriver\\Missing')) {
                    $title = $resource->getTitle();
                    $title = empty($title) ? $this->transEsc('Title not available') : $this->escapeHtml($title);
                    echo '<a href="' . $this->recordLink()->getUrl($resource)
                        . '" class="title">' . $title . '</a>';
                } elseif (isset($ilsDetails['title']) && !empty($ilsDetails['title'])){
                    // If the record is not available in Solr, perhaps the ILS driver sent us a title we can show...
                    echo $this->escapeHtml($ilsDetails['title']);
                } else {
                    // Last resort -- indicate that no title could be found.
                    echo $this->transEsc('Title not available');
                }
                ?>
            </td>
            <td>
                <?php if (!empty($ilsDetails['institution'])): ?>
                    <?=$this->escapeHtml($this->laminasTranslate($ilsDetails['institution'], 'institution'))?>
                    <br />
                <?php endif; ?>

                <?php if (!empty($ilsDetails['signature'])): ?>
                    <?=$this->escapeHtml($ilsDetails['signature'])?>
                <?php endif; ?>
            </td>
            <td>
                <?php /* Depending on the ILS driver, the "location" value may be a string or an ID; figure out the best
           value to display... */ ?>
                <?php $pickupDisplay = ''; ?>
                <?php $pickupTranslate = false; ?>
                <?php if (isset($ilsDetails['location'])): ?>
                    <?php if ($this->pickup): ?>
                        <?php foreach ($this->pickup as $library): ?>
                            <?php if ($library['locationID'] == $ilsDetails['location']): ?>
                                <?php $pickupDisplay = $library['locationDisplay']; ?>
                                <?php $pickupTranslate = true; ?>
                            <?php endif; ?>
                        <?php endforeach; ?>
                    <?php endif; ?>
                    <?php if (empty($pickupDisplay)): ?>
                        <?php $pickupDisplay = $ilsDetails['location']; ?>
                    <?php endif; ?>
                <?php endif; ?>
                <?php if (!empty($pickupDisplay)): ?>
                    <?=$pickupTranslate ? $this->transEsc($pickupDisplay) : $this->escapeHtml($pickupDisplay)?>
                <?php endif; ?>
            </td>
            <td>
                <?=$this->escapeHtml($ilsDetails['create']) ?>
            </td>
            <td>
                <?if (preg_match('/due date/', $ilsDetails['status']))
                {
                    $status = $this->transEsc('Waiting in queue') . ': ' . $ilsDetails['position'] . '; ' .
                        $this->transEsc('Due Date') . ': ' . $ilsDetails['duedate'];
                }
                elseif (preg_match('/queue$/', $ilsDetails['status']))
                {
                    $status = $this->transEsc('Waiting in queue') . ': ' . $ilsDetails['position'];
                }
                elseif (preg_match('/On hold until:/', $ilsDetails['status']))
                {
                    $status = $this->transEsc('On hold until') . ': ' . preg_replace('/On hold until: /', '',  $ilsDetails['status']);
                }
                else
                {
                    $status = $this->transEsc($ilsDetails['status']);
                }
                ?>
                <?=$this->escapeHtml($status)?>
            </td>
            <td>
                <?php if ($this->cancelForm && isset($ilsDetails['cancel_details'])): ?>
                    <?php $safeId = preg_replace('/[^a-zA-Z0-9]/', '', $resource->getUniqueId()); ?>
                    <input type="hidden" name="cancelAllIDS[]" value="<?=$this->escapeHtmlAttr($ilsDetails['cancel_details']) ?>" />
                    <div class="pull-left">
                        <input type="checkbox" name="cancelSelectedIDS[]" value="<?=$this->escapeHtmlAttr($ilsDetails['cancel_details']) ?>" id="checkbox_<?=$safeId?>" />
                    </div>
                <?php endif; ?>

                <?php if (isset($this->cancelResults['items'])): ?>
                    <?php foreach ($this->cancelResults['items'] as $itemId => $cancelResult): ?>
                        <?php if ($itemId == $ilsDetails['item_id'] && $cancelResult['success'] == false): ?>
                            <br /><div class="alert alert-danger"><?=$this->transEsc($cancelResult['status']) ?><?php if ($cancelResult['sysMessage']) echo ' : ' . $this->transEsc($cancelResult['sysMessage']); ?></div>
                        <?php endif; ?>
                    <?php endforeach; ?>
                <?php endif; ?>

                <?php if (isset($ilsDetails['available']) && $ilsDetails['available'] == true): ?>
                    <br /><div class="text-success"><?=$this->transEsc("hold_available") ?></div>
                <?php endif; ?>
                <?php if (isset($ilsDetails['cancel_link'])): ?>
                    <p><a href="<?=$this->escapeHtmlAttr($ilsDetails['cancel_link']) ?>"><?=$this->transEsc("hold_cancel") ?></a></p>
                <?php endif; ?>
            </td>
    </tr>
    <?php endforeach; ?>

        </tbody>
    </table>
    <?=$flippedContent;?>
    <?php if ($this->cancelForm): ?></form><?php endif; ?>
<?php else: ?>
    <?=$this->transEsc('You do not have any holds or recalls placed') ?>.
<?php endif; ?>
</div>

<div class="<?=$this->layoutClass('sidebar')?>">
<?=$this->context($this)->renderInContext("myresearch/menu.phtml", ['active' => 'holds'])?>
</div>