<?php
/** @var array $headers */
/** @var mixed $ilsDetails */
/** @var mixed $resource */
?>
<table class="table table-flipped hidden-md hidden-lg">
    <tbody>
    <tr>
        <th><?=$headers['title']?></th>
        <td><?php
            // If this is a non-missing Solr record, we should display a link:
            if (is_a($resource, 'VuFind\\RecordDriver\\SolrDefault') && !is_a($resource, 'VuFind\\RecordDriver\\Missing')) {
                $title = $resource->getTitle();
                $title = empty($title) ? $this->transEsc('Title not available') : $this->escapeHtml($title);
                echo '<a href="' . $this->recordLink()->getUrl($resource)
                . '" class="title">' . $title . '</a>';
            } elseif (isset($ilsDetails['title']) && !empty($ilsDetails['title'])){
                // If the record is not available in Solr, perhaps the ILS driver sent us a title we can show...
                echo $this->escapeHtml($ilsDetails['title']);
            } else {
                // Last resort -- indicate that no title could be found.
                echo $this->transEsc('Title not available');
            }
            ?>
        </td>
    </tr>
    <tr>
        <th><?=$headers['library_callno']?></th>
        <td>
            <?php if (!empty($ilsDetails['institution'])): ?>
                <?=$this->escapeHtml($this->zendTranslate($ilsDetails['institution'], 'institution'))?>,
            <?php endif; ?>

            <?php if (!empty($ilsDetails['signature'])): ?>
                <?=$this->escapeHtml($ilsDetails['signature'])?>
            <?php endif; ?>
        </td>
    </tr>
    <tr>
        <th><?=$headers['pick_up_location']?></th>
        <td>
            <?php /* Depending on the ILS driver, the "location" value may be a string or an ID; figure out the best
           value to display... */ ?>
            <?php $pickupDisplay = ''; ?>
            <?php $pickupTranslate = false; ?>
            <?php if (isset($ilsDetails['location'])): ?>
                <?php if ($this->pickup): ?>
                    <?php foreach ($this->pickup as $library): ?>
                        <?php if ($library['locationID'] == $ilsDetails['location']): ?>
                            <?php $pickupDisplay = $library['locationDisplay']; ?>
                            <?php $pickupTranslate = true; ?>
                        <?php endif; ?>
                    <?php endforeach; ?>
                <?php endif; ?>
                <?php if (empty($pickupDisplay)): ?>
                    <?php $pickupDisplay = $ilsDetails['location']; ?>
                <?php endif; ?>
            <?php endif; ?>
            <?php if (!empty($pickupDisplay)): ?>
                <?=$pickupTranslate ? $this->transEsc($pickupDisplay) : $this->escapeHtml($pickupDisplay)?>
            <?php endif; ?>
        </td>
    </tr>
    <tr>
        <th><?=$headers['created']?></th>
        <td>
            <?=$this->escapeHtml($ilsDetails['create']) ?>
        </td>
    </tr>
    <tr>
        <th><?=$headers['status']?></th>
        <td>
            <?if (preg_match('/due date/', $ilsDetails['status']))
            {
                $status = $this->transEsc('Waiting in queue') . ': ' . $ilsDetails['position'] . '; ' .
                    $this->transEsc('Due Date') . ': ' . $ilsDetails['duedate'];
            }
            elseif (preg_match('/queue$/', $ilsDetails['status']))
            {
                $status = $this->transEsc('Waiting in queue') . ': ' . $ilsDetails['position'];
            }
            elseif (preg_match('/On hold until:/', $ilsDetails['status']))
            {
            $status = $this->transEsc('On hold until') . ': ' . preg_replace('/On hold until: /', '',  $ilsDetails['status']);
            }
            else
            {
                $status = $this->transEsc($ilsDetails['status']);
            }
            ?>
            <?=$this->escapeHtml($status)?>
        </td>
    </tr>
    <?php if ($this->cancelForm && isset($ilsDetails['cancel_details']) || (isset($this->cancelResults['items']))): ?>
    <tr>
        <th><?= $headers['action'] ?? '' ?></th>
        <td>
            <?php if ($this->cancelForm && isset($ilsDetails['cancel_details'])): ?>
                <?php $safeId = preg_replace('/[^a-zA-Z0-9]/', '', $resource->getUniqueId()); ?>
                <input type="hidden" name="cancelAllIDS[]" value="<?=$this->escapeHtmlAttr($ilsDetails['cancel_details']) ?>" />
                <div class="pull-left">
                    <input type="checkbox" name="cancelSelectedIDS[]" value="<?=$this->escapeHtmlAttr($ilsDetails['cancel_details']) ?>" id="checkbox_<?=$safeId?>" />
                </div>
            <?php endif; ?>

            <?php if (isset($this->cancelResults['items'])): ?>
                <?php foreach ($this->cancelResults['items'] as $itemId => $cancelResult): ?>
                    <?php if ($itemId == $ilsDetails['item_id'] && $cancelResult['success'] == false): ?>
                        <br /><div class="alert alert-danger"><?=$this->transEsc($cancelResult['status']) ?><?php if ($cancelResult['sysMessage']) echo ' : ' . $this->transEsc($cancelResult['sysMessage']); ?></div>
                    <?php endif; ?>
                <?php endforeach; ?>
            <?php endif; ?>

            <?php if (isset($ilsDetails['available']) && $ilsDetails['available'] == true): ?>
                <br /><div class="text-success"><?=$this->transEsc("hold_available") ?></div>
            <?php endif; ?>
            <?php if (isset($ilsDetails['cancel_link'])): ?>
                <p><a href="<?=$this->escapeHtmlAttr($ilsDetails['cancel_link']) ?>"><?=$this->transEsc("hold_cancel") ?></a></p>
            <?php endif; ?>
        </td>
    </tr>
    <?php endif; ?>
    </tbody>
</table>