<?php if ($this->organisationOfSameGenreTotal > 0): ?>
<div class="carousel-container">
    <a id="detailpage-coauthors"></a>
    <div class="separator"></div>
    <div class="row">
        <div class="col-xs-8">
            <h2><?= $this->esorganisation()->getSearchResultHeadline('page.detail.authors.coauthors', $this->organisationOfSameGenreTotal, true) ?></h2>
        </div>
        <div class="col-xs-4">
            <span class="all-results-link">
                <a href="<?= $this->esorganisation()->getCoauthorsSearchLink() ?>"><?= $this->translate('common.show.results.all') ?></a>
            </span>
        </div>
    </div>

    <div class="row">
        <div class="col-xs-12">
            <?= $this->render(
                '/detailpage/carousel.phtml', [
                    'id' => 'coauthors',
                    'pagination' => ['xs' => 2, 'sm' => 4, 'md' => 6, 'lg' => 6],
                    'thumbnail' => $this->imageLink('person-placeholder.png'),
                    'total' => $this->organisationOfSameGenreTotal,
                    'templates' => [
                        'ajax' => $this->ajax([
                            'method' => 'getCoAuthors',
                            'person' => $this->page.detail.authors.coauthors()->escapeUrl($this->driver->getUniqueId()),
                            'page' => '{page}',
                            'size' => '{size}'
                        ], '{}'),
                        'page' => urldecode($this->url('page-detail-organisation', ['id' => '{id}'])),
                        'info' => urldecode($this->url('card-knowledge-organisation', ['id' => '{id}']))
                    ]
                ]
            ) ?>
        </div>
    </div>
</div>
<?php endif; ?>
