<?php if ($this->sameHierarchicalSuperiorOrganisationsTotal > 0): ?>
<div class="carousel-container">
    <a id="detailpage-sameHierarchicalSuperiorOrganisations"></a>
    <div class="separator"></div>
    <div class="row">
        <div class="col-xs-8">
            <h2><?= $this->esorganisation()->getSearchResultHeadline('page.detail.organisation.sameHierarchicalSuperiorOrganisations', $this->sameHierarchicalSuperiorOrganisationsTotal, true) ?></h2>
        </div>
        <div class="col-xs-4">
            <span class="all-results-link">
                <a href="< ?= $this->esorganisation()->getSuperiorOrganisationsSearchLink() ?>">< ?= $this->translate('common.show.results.all') ?></a>
            </span>
        </div>
    </div>

    <div class="row">
        <div class="col-xs-12">
            <?php
            $superiorOrgIds = $this->esorganisation()->escapeUrl($this->driver->getHierarchicalSuperiorOrganisationIds());
            $superiorOrgIds = $this->esorganisation()->getHierarchicalSuperiorOrganisationIds();
            ?>
            <?= $this->render(
                '/detailpage/carousel.phtml', [
                    'id' => 'sameHierarchicalSuperiorOrganisations',
                    'pagination' => ['xs' => 2, 'sm' => 4, 'md' => 6, 'lg' => 6],
                    'thumbnail' => $this->imageLink('person-placeholder.png'),
                    'total' => $this->sameHierarchicalSuperiorOrganisationsTotal,
                    'superiorOrgIds' => $superiorOrgIds,
                    'templates' => [
                        'ajax' => $this->ajax([
                            'method' => 'getSameHierarchicalSuperiorOrganisations',
                            'superiorOrgIds' => $superiorOrgIds,
                            'page' => '{page}',
                            'size' => '{size}'
                        ], '{}'),
                        'page' => urldecode($this->url('page-detail-organisation', ['id' => '{id}'])),
                        'info' => urldecode($this->url('card-knowledge-organisation', ['id' => '{id}']))
                    ]
                ]
            ) ?>
        </div>
    </div>
</div>
<?php endif; ?>
