<div class="home-content-box">
  <h2 class="lead">Travaux de maintenance entre Vendredi, 24.8., 12:00 et Lundi, 26.8.</h2>
  <img class="img-responsive" src="<?= $this->basePath('themes/sbvfrdmulti/images/underconstruction.jpg') ?>" width="150">
  <br/>
  <p>En raison de travaux de maintenance votre compte usager et les fonctions de prêt ne sont pas disponibles entre Vendredi, 24.8., 12:00 et jusqu'à lundi midi, 27.8.. La recherche n'est pas affecté. Veuillez nous excuser pour tout désagrément causé.</p>
</div>