<div class="home-content-box">
    <h2 class="lead">À propos de swissbib Basel Bern</h2>

    <p>
        swissbib Basel Bern est le catalogue des bibliothèques académiques de Bâle et Berne, y compris la Bibliothèque nationale suisse.
    </p>
    <a href="http://swissbib-baselbern.blogspot.ch/search/label/Tipp" target="_blank" class="btn btn-link">Aktuell im Blog: Effizient recherchieren - lassen Sie es sich kurz erklären </a>
    <a href="<?= $this->url('help-page', ['topic' => 'about']); ?>" class="btn btn-link">Plus d'informations</a><br/>
    <a href="<?= $this->url('help-page', ['topic' => 'faq']); ?>" class="btn btn-link"><?= $this->transEsc('helppage') ?></a>
</div>
