<div class="home-content-box">
    <h2 class="lead">Gezielte Suche nach alten Drucken</h2>
    <p>Bei der Suche nach alten Drucken lohnt es sich, fit in den üblichen Suchstrategien in der erweiterten Suche zu sein. Deshalb greifen wir in diesem Blogpost einige davon auf.</p>

    <a href="<?= $this->redirectProtocolWrapper()->getWrappedURL('http://swissbib-baselbern.blogspot.ch/search/label/Tipp') ?>" target="_blank" class="btn btn-link">Mehr Informationen im Blog</a>
</div>
