<div class="home-content-box">
    <h2 class="lead">Recherche-Workshop, Klasseneinführung oder geführter Rundgang - willkommen in der Universitätsbibliothek!</h2>
    <p>Die Universitätsbibliotheken in Basel und Bern bieten auch diesen Herbst und Winter wieder ein vielfältiges (Ein)Führungs- und Kursprogramm an.</p>

    <a href="http://swissbib-baselbern.blogspot.ch/search/label/Tipp" target="_blank" class="btn btn-link">Mehr Informationen im Blog</a>
</div>
