<div class="home-content-box">
  <h2 class="lead">Comment commencer?</h2>
  <p>Introduction de swissbib Basel Bern</p>
  <p><a href="https://tube.switch.ch/videos/d8d59fc8" target="_blank" class="btn btn-link"><i class="fa fa-video-camera"></i> Comment rechercher?</a></p>
  <p><a href="https://tube.switch.ch/videos/d2f4ff5e" target="_blank" class="btn btn-link"><i class="fa fa-video-camera"></i> Comment réserver?</a></p>
  <p><a href="https://tube.switch.ch/videos/ea02c388" target="_blank" class="btn btn-link"><i class="fa fa-video-camera"></i> Trouver des livres numériques</a></p>
  <p><a href="https://tube.switch.ch/videos/0542438f" target="_blank" class="btn btn-link"><i class="fa fa-video-camera"></i> Comment utiliser Articles & plus?</a></p>
</div>
