<div class="home-content-box">
    <h2 class="lead">Mein gesuchtes Buch befindet sich in einer NEBIS-Bibliothek – wie kann ich es bestellen?</h2>
    <p>Der NEBIS-Verbund verfügt über einen Kurier, der die dem NEBIS-Ausleihverbund angeschlossenen Bibliotheken beliefert. Hier erfahren Sie, wie Sie diesen nutzen können.</p>

    <a href="<?= $this->redirectProtocolWrapper()->getWrappedURL('http://swissbib-baselbern.blogspot.ch/search/label/Tipp') ?>" target="_blank" class="btn btn-link">Mehr Informationen im Blog</a>
</div>
