# seachspecsES.yaml for linked-swissbib
# search target ElasticSearch
# ###########

# author for id
AuthorForId:
  Multisearch:
    - BibliographicResourceForAuthor
  UsedTypes:
    - person
  UsedIndex:
    - lsb
  query:
    multi_match:
      fields:
        - @id
      type: cross_fields
      operator: and

# subject by id
SubjectById:
  Multisearch:
    - BibliographicResourceForSubject
  UsedTypes:
    - DEFAULT
  UsedIndex:
    - gnd
  query:
    multi_match:
      fields:
        - @id
      type: cross_fields
      operator: and

# AuthorByIdMulti : see /usr/local/vufind/httpd/module/LinkedSwissbib/src/LinkedSwissbib/Backend/Elasticsearch/ESQueryBuilder.php

# SubjectByIdMulti : see /usr/local/vufind/httpd/module/LinkedSwissbib/src/LinkedSwissbib/Backend/Elasticsearch/ESQueryBuilder.php

# bibliographicResource for Author
BibliographicResourceForAuthor:
  UsedTypes:
    - bibliographicResource
  UsedIndex:
    - lsb
  query:
    multi_match:
      fields:
        - dct:contributor
      type: cross_fields
      operator: and

# bibliographicResource for Subject
BibliographicResourceForSubject:
  UsedTypes:
    - bibliographicResource
  UsedIndex:
    - lsb
  query:
    multi_match:
      fields:
        - dct:subject
      type: cross_fields
      operator: and


AutocompleteAuthor:
  Multisearch:
    - AutocompleteInstance
  UsedTypes:
    - person
  UsedIndex:
    - lsb
  query:
    multi_match:
      fields:
        - foaf:name
        - foaf:firstName
        - foaf:lastName
        - dbp:pseudonym.de
        - dbp:pseudonym.en
        - dbp:pseudonym.fr
        - dbp:pseudonym.it
        - schema:alternateName
        #- rdfs:label
      type: cross_fields
      operator: or

AutocompleteInstance:
  Multisearch:
    - AutocompleteSubject
  UsedTypes:
    - bibliographicResource
  UsedIndex:
    - lsb
  query:
    multi_match:
      fields:
        - dct:title
        - dct:contributor
      type: cross_fields
      operator: and

AutocompleteSubject:
  UsedTypes:
    - DEFAULT
  UsedIndex:
    - gnd
  query:
    multi_match:
      fields:
        #- http://d-nb_info/standards/elementset/lsb#preferredNameForTheConferenceOrEvent.@value
        - http://d-nb_info/standards/elementset/gnd#preferredNameForTheSubjectHeading.@value
        - http://d-nb_info/standards/elementset/gnd#variantNameForTheSubjectHeading.@value
        - @type
      type: cross_fields
      operator: and

AllFields:
  UsedTypes:
    - bibliographicResource
  UsedIndex:
    - lsb
  query:
    bool:
      should:
        multi_match:
          type: cross_fields
          operator: and
          fields:
            - dct:title
            - rdau:publicationStatement
            - @type
            - dct:contributor
            - rdau:noteOnResource
            - dct:bibliographicCitation
            - bibo:isbn13
            - bibo:isbn10
#        nested:
#          path:
#            - dc:contributor
#          query:
#            multi_match:
#              fields:
#                - dc:contributor.foaf:firstName
#                - dc:contributor.foaf:lastName
#              type:
#                - cross_fields #should be default
#              operator:
#                - and # should be default

#Used for result list authors
Person:
  UsedTypes:
    - person
  UsedIndex:
    - lsb
  query:
    multi_match:
      fields:
        - foaf:name
        - foaf:firstName
        - foaf:lastName
        - dbp:pseudonym.de
        - dbp:pseudonym.en
        - dbp:pseudonym.fr
        - dbp:pseudonym.it
        - schema:alternateName
        #- rdfs:label
      type: cross_fields
      operator: and
