<div class="home-content-box">
    <h2 class="lead">swisscovery - Nouvelle interface de recherche</h2>
  <p>A partir du 7 décembre 2020, SLSP mettra à disposition <a href="https://www.swisscovery.org/" target="_blank"">swisscovery</a>, la nouvelle interface de recherche pour les collections des bibliothèques scientifiques suisses. A partir de ce moment, les informations dans swissbib ne seront plus actualisées. Fin mars 2021, swissbib cessera de fonctionner.</p>
  <p>De plus amples informations vont suivre sur les sites web de <a href="https://slsp.ch/fr"  target="_blank">SLSP</a> et des bibliothèques concernées.</p>

  <a href="https://swissbib.blogspot.com/2020/11/zur-einstellung-der-swissbib.html" target="_blank" class="btn btn-link">Plus d'informations</a>
</div>
