<div class="home-content-box">
    <h2 class="lead">Informations sur les personnes et les sujets dans swissbib</h2>
    <p>Trois nouvelles fonctionnalités, des Knowledge Cards et des pages pour des personnes et des sujets et une amélioration des suggestions lors de la frappe, élargissent les possibilités de recherche et de découverte d’informations sur swissbib.
</p>
    <a href="<?= $this->redirectProtocolWrapper()->getWrappedURL('https://swissbib.blogspot.com/2018/03/swissbib-mit-personen-und.html') ?>" target="_blank" class="btn btn-link">Plus d'informations</a>
</div>