<div class="home-content-box">
    <h2 class="lead">Interface</h2>
    <p>
        You can use this interface to look up migrated bibliographic records both in their deduplicated form (as they were delivered to Ex Libris) as well as in their pre-deduplication form, with the swissbib mass corrections already being applied. It is not intended as a discovery platform for patron library users.
    </p>
</div>