<div class="home-content-box">
  <h2 class="lead">Nouvelles fonctionnalités</h2>
  <p>Grâce aux améliorations suivantes, vos recherches dans swissbib sont désormais plus simples :</p>
      <a href="https://swissbib.blogspot.com/2019/05/bessere-bibliothekssuche-meilleure.html" target="_blank">Meilleure recherche par bibliothèques</a> (y compris par canton)<br/>
      <a href="https://swissbib.blogspot.com/2019/05/verfugbarkeitsanzeige-disponibilite.html" target="_blank">Disponibilité des documents dans la liste des résultats</a><br/>
      <a href="https://swissbib.blogspot.com/2019/07/verfugbarkeit-der-medien-von-rero.html" target="_blank">Disponibilité des documents du réseau romand RERO</a> et de la bibliothèque nationale<br/>
      <a href="https://swissbib.blogspot.com" target="_blank">Autocomplétion</a> lors de la frappe
</div>